import test from 'node:test';
import assert from 'node:assert/strict';
import {activities} from '../src/content.ts';
import {blankDraft,checkAnswer,fresh,parseState,suggestedLevel,safeURL} from '../src/model.ts';
test('All 186 challenges have complete learning guidance',()=>{
 assert.equal(activities.length,62);
 for(const a of activities){assert.equal(a.tasks.length,3);assert.ok(a.objective);for(const t of a.tasks){assert.ok(t.hint&&t.prompt&&t.explanation);assert.ok(t.answer!==undefined||t.checklist?.length);if(t.options)assert.equal(t.options.filter(v=>v===t.answer).length,1);}}
});
test('Money uses integer pence, quantities and exact change',()=>{
 for(const t of activities.find(a=>a.id==='shop').tasks){const cost=t.items.reduce((v,i)=>v+i.price*i.quantity,0);assert.equal((t.budget-cost)/100,t.answer);const d={...blankDraft(),counts:t.items.map(i=>i.quantity),answer:String((t.budget-cost)/100)};assert.ok(checkAnswer('shop',t,d));assert.ok(!checkAnswer('shop',t,{...d,counts:[0,0,0]}));assert.ok(!checkAnswer('shop',t,{...d,answer:'£'+d.answer}));}
});
test('Garden: independent area, perimeter and remaining area calculations',()=>{
 const ts=activities.find(a=>a.id==='garden').tasks;const values=[ts[0].width*ts[0].height,2*(ts[1].width+ts[1].height),ts[2].width*ts[2].height*.75];
 ts.forEach((t,i)=>{assert.equal(t.answer,values[i]);const d={...blankDraft(),width:t.width,height:t.height,answer:String(values[i])};assert.ok(checkAnswer('garden',t,d));assert.ok(!checkAnswer('garden',t,{...d,width:1}));});
});
test('Fractions and data agree with independently computed values',()=>{
 for(const t of activities.find(a=>a.id==='fractions').tasks){assert.equal(t.total/t.parts,t.answer);assert.ok(checkAnswer('fractions',t,{...blankDraft(),tiles:Array.from({length:t.answer},(_,i)=>i),answer:String(t.answer)}));assert.ok(!checkAnswer('fractions',t,{...blankDraft(),answer:String(t.answer)}));}
 const ts=activities.find(a=>a.id==='data').tasks;assert.equal(ts[0].answer,ts[0].bars[0].value-ts[0].bars[1].value);assert.equal(ts[1].answer,ts[1].bars.reduce((s,b)=>s+b.value,0));assert.equal(ts[2].answer,ts[2].bars.reduce((s,b)=>s+b.value,0)/ts[2].bars.length);
});
test('Word order is checked, not merely selected word count',()=>{for(const t of activities.find(a=>a.id==='words').tasks.filter(t=>t.words)){const order=t.answer.split(' ').map(w=>t.words.indexOf(w));assert.ok(checkAnswer('words',t,{...blankDraft(),words:order}));assert.ok(!checkAnswer('words',t,{...blankDraft(),words:[...order].reverse()}));}});
test('Blank, nonfinite and malformed numeric values never count as correct',()=>{for(const answer of ['', ' ', 'Infinity','NaN','3abc','3,00','0x3'])assert.ok(!checkAnswer('data',{answer:3}, {...blankDraft(),answer}));});
test('Adaptation is transparent and does not treat reflections as mastery',()=>{const s=fresh();assert.equal(suggestedLevel(s,'shop'),0);s.results['shop:0']={activity:'shop',level:0,attempts:1,assisted:false,mode:'checked',at:'2026-09-26T12:00:00Z'};assert.equal(suggestedLevel(s,'shop'),0);s.history=[0,1,2].map(i=>({...s.results['shop:0'],practiceId:`shop:0:${i}`}));assert.equal(suggestedLevel(s,'shop'),1);s.history=[];s.results['shop:0'].assisted=true;assert.equal(suggestedLevel(s,'shop'),0);s.results['shop:2']={activity:'shop',level:2,attempts:3,assisted:false,mode:'checked',at:'2026-09-26T13:00:00Z'};assert.equal(suggestedLevel(s,'shop'),1);s.results['story:1']={activity:'story',level:1,attempts:1,assisted:false,mode:'reflection',at:'2026-09-26T14:00:00Z'};assert.equal(suggestedLevel(s,'story'),0);});
test('Progress round trips and corrupt data is rejected without overwriting it',()=>{const s=fresh();s.drafts['shop:0']={...blankDraft(),answer:'3',counts:[2,1,0]};s.last='shop:0';assert.deepEqual(parseState(JSON.stringify(s)),s);for(const raw of ['garbage','{}',JSON.stringify({...s,version:2}),JSON.stringify({...s,last:'missing:9'}),JSON.stringify({...s,drafts:{'shop:0':{}}})])assert.throws(()=>parseState(raw));});
test('Business links require safe HTTPS addresses',()=>{assert.ok(safeURL('https://example.org'));for(const u of ['http://example.org','javascript:alert(1)','https://user:secret@example.org','oops',''])assert.ok(!safeURL(u));});

test('Every curriculum register entry resolves to an implemented activity',async()=>{const {coverage}=await import('../src/coverage.ts');assert.equal(new Set(coverage.map(r=>r.id)).size,coverage.length);assert.equal(new Set(activities.map(a=>a.id)).size,activities.length);for(const row of coverage){assert.ok(row.activities.length);for(const id of row.activities)assert.ok(activities.some(a=>a.id===id),`${row.id}: missing ${id}`);}for(const a of activities)assert.ok(coverage.some(r=>r.activities.includes(a.id)),`Unmapped ${a.id}`);});
test('All closed questions accept their solution and reject an incorrect answer',()=>{for(const a of activities){for(const t of a.tasks){if(t.answer===undefined)continue;const d={...blankDraft(),answer:String(t.answer),width:t.width||1,height:t.height||1,counts:t.items?.map(i=>i.quantity)||[],tiles:t.total?Array.from({length:Number(t.answer)},(_,i)=>i):[],words:t.words?String(t.answer).split(' ').map(w=>t.words.indexOf(w)):[]};assert.ok(checkAnswer(a.kind,t,d),a.id+': '+t.prompt);const bad={...d,answer:typeof t.answer==='number'?String(t.answer+1):'Incorrect',words:[]};assert.ok(!checkAnswer(a.kind,t,bad),a.id);}}});
test('Expanded numeric answers independently agree with domain calculations',()=>{const expected={
'place-value':[7*100,null,40000+600+8+3/100], 'decimal-scaling':[34*10,7.25*100,643/100], estimate:[Math.round(347/10)*10,Math.round(198/100)*100+Math.round(403/100)*100,null],negative:[null,3-(-4),null],sequences:[18+4,24*2,null],factors:[[1,2,3,4,6,12].length,null,4**3-5**2],machines:[8+7,6*2+3,(19+2)/3],unknown:[15-8,36/4,(26-5)/3],mental:[38+9,203-98,4.75+2.99],tables:[4*5,7*8,90/10],operations:[(12+8)/4,1.25*3,9.6/4-.35],'fraction-links':[null,20*3/4,null],currency:[null,5*1.2,10/1.25],units:[2*100,1.75*1000,2000-650],volume:[3,4*3*2,60/(5*4)],scale:[4*2,35/5,null],time:[null,null,12+25],solids:[6,8,null],angles:[null,180-50-60,null],frequency:[5+5+3,6+9,7+5],averages:[9-3,(4+6+8)/3,4*8-(6+7+9)]};for(const [id,values] of Object.entries(expected)){values.forEach((value,i)=>{if(value!==null)assert.ok(Math.abs(activities.find(a=>a.id===id).tasks[i].answer-value)<1e-9,`${id}:${i}`);});}});
test('Adult feedback adapts only the reviewed topic and persists',()=>{const s=fresh();s.results['story:1']={activity:'story',level:1,attempts:1,assisted:false,mode:'reflection',at:'2026-09-26T15:00:00Z',adultRating:'secure'};assert.equal(suggestedLevel(s,'story'),2);assert.equal(suggestedLevel(s,'shop'),0);s.results['story:1'].adultRating='support';assert.equal(suggestedLevel(parseState(JSON.stringify(s)),'story'),0);s.results['story:1'].adultRating='developing';assert.equal(suggestedLevel(s,'story'),1);});
test('Two children using independent devices retain independent progress',()=>{const robin=fresh(),wren=fresh();robin.nickname='Robin';robin.drafts['story:0']={...blankDraft(),answer:'An original unfinished story.'};const reopened=parseState(JSON.stringify(robin));assert.equal(reopened.drafts['story:0'].answer,'An original unfinished story.');assert.equal(wren.nickname,'');assert.deepEqual(wren.drafts,{});});

test('Turtle programs draw correct paths and reject executable or excessive input',async()=>{const {runTurtle}=await import('../src/turtle.ts');const r=runTurtle('FORWARD 3\nRIGHT 90\n'.repeat(4));assert.equal(r.error,undefined);assert.equal(r.points.length,5);assert.ok(Math.abs(r.points.at(-1).x)<1e-10);assert.ok(Math.abs(r.points.at(-1).y)<1e-10);assert.ok(runTurtle('alert(1)').error);assert.ok(runTurtle('FORWARD 100').error);assert.ok(runTurtle('RIGHT 90\n'.repeat(41)).error);});
