import { maths } from './maths.ts';
import { english } from './english.ts';
export type Level = 0 | 1 | 2;
export const levels = ['Getting started', 'Finding your stride', 'Extra challenge'];
export type Task = { prompt:string; hint:string; explanation:string; answer?:number|string; options?:string[]; passage?:string; words?:string[]; checklist?:string[]; budget?:number; items?:{name:string;price:number;quantity:number}[]; width?:number;height?:number; bars?:{label:string;value:number}[]; total?:number;parts?:number; };
export type Activity = {id:string;title:string;subject:'Maths'|'English';strand:string;kind:'shop'|'garden'|'detective'|'words'|'story'|'data'|'talk'|'fractions'|'practice'|'practical';icon:string;colour:string;description:string;objective:string;source:'maths'|'english';tasks:Task[]};
export const sources = {maths:'https://ccea.org.uk/document/2066',english:'https://ccea.org.uk/document/2054'};
const coreActivities: Activity[] = [
 {id:'shop',title:'The little market',subject:'Maths',strand:'Number · Money',kind:'shop',icon:'✿',colour:'#F9E5C7',description:'Pack a picnic. Keep an eye on your pennies.',objective:'Use money calculations and plan spending within a budget.',source:'maths',tasks:[
 {prompt:'Buy 2 apples and 1 juice. You have £5. How much change will you get? Enter pounds.',budget:500,items:[{name:'Apple',price:50,quantity:2},{name:'Juice',price:100,quantity:1},{name:'Bun',price:75,quantity:0}],answer:3,hint:'First add 50p + 50p + £1. Then subtract the total from £5.',explanation:'The picnic costs £2. £5 − £2 = £3 change.'},
 {prompt:'Buy 2 sandwiches and 1 juice. You have £10. How much change will you get? Enter pounds.',budget:1000,items:[{name:'Sandwich',price:235,quantity:2},{name:'Juice',price:125,quantity:1},{name:'Apple',price:65,quantity:0}],answer:4.05,hint:'Two sandwiches cost £4.70. Add the juice, then subtract from £10.',explanation:'£4.70 + £1.25 = £5.95. £10 − £5.95 = £4.05.'},
 {prompt:'Buy 3 rolls and 2 milks. You have £12. How much change will you get? Enter pounds.',budget:1200,items:[{name:'Roll',price:185,quantity:3},{name:'Milk',price:140,quantity:2},{name:'Pear',price:80,quantity:0}],answer:3.65,hint:'Work in pence: 3 × 185 and 2 × 140. Add, then subtract from 1,200.',explanation:'The rolls cost £5.55 and milk £2.80. Total £8.35; change £3.65.'}]},
 {id:'garden',title:'Build a pocket garden',subject:'Maths',strand:'Measures · Shape and Space',kind:'garden',icon:'▦',colour:'#DFEDCE',description:'Make a garden grow, one square at a time.',objective:'Construct rectangles and calculate their perimeter and area.',source:'maths',tasks:[
 {prompt:'Build a rectangle 3 m wide and 2 m high. Each square is 1 m². What is its area in m²?',width:3,height:2,answer:6,hint:'Count the squares, or multiply the number of columns by rows.',explanation:'3 columns and 2 rows make 6 squares. Area = 3 × 2 = 6 m².'},
 {prompt:'Build a rectangle 4 m wide and 3 m high. How many metres of fence go all the way around it?',width:4,height:3,answer:14,hint:'Perimeter is the outside edge. Add width + height + width + height.',explanation:'4 + 3 + 4 + 3 = 14 metres. Area would be 12 m², but fencing measures perimeter.'},
 {prompt:'Build a rectangle 6 m wide and 4 m high. One quarter is a pond. How many m² remain for plants?',width:6,height:4,answer:18,hint:'Find the total area, divide it by 4 for the pond, then subtract.',explanation:'6 × 4 = 24 m². The pond uses 24 ÷ 4 = 6 m². Plants have 24 − 6 = 18 m².'}]},
 {id:'fractions',title:'The sharing patch',subject:'Maths',strand:'Number · Fractions',kind:'fractions',icon:'◒',colour:'#F6DED7',description:'See how small parts make a whole.',objective:'Represent fractions and connect them to quantities and percentages.',source:'maths',tasks:[
 {prompt:'Tap exactly half of the 8 tiles. How many tiles is that?',total:8,parts:2,answer:4,hint:'Half means two equal groups. Split 8 into 2 groups.',explanation:'8 ÷ 2 = 4. Four of eight equal tiles represent one half.'},
 {prompt:'Tap exactly one quarter of the 12 tiles. How many tiles is that?',total:12,parts:4,answer:3,hint:'One quarter is one of four equal groups.',explanation:'12 ÷ 4 = 3. Three of twelve equal tiles represent one quarter.'},
 {prompt:'Tap 25% of the 20 tiles. How many tiles is that?',total:20,parts:4,answer:5,hint:'25% = 25/100 = 1/4. Divide 20 by 4.',explanation:'20 ÷ 4 = 5. One quarter, 0.25 and 25% describe the same share.'}]},
 {id:'data',title:'Wildlife watch',subject:'Maths',strand:'Handling Data',kind:'data',icon:'▥',colour:'#DCEBEA',description:'Look closer. What can the numbers tell you?',objective:'Interpret charts, compare counts and calculate a mean.',source:'maths',tasks:[
 {prompt:'These are sightings in a pretend garden survey. How many more robins than wrens were seen?',bars:[{label:'Robins',value:6},{label:'Wrens',value:2},{label:'Blackbirds',value:4}],answer:4,hint:'Compare the robin and wren counts using subtraction.',explanation:'6 − 2 = 4. Four more robins than wrens were recorded. Sightings do not necessarily mean different birds.'},
 {prompt:'Each count is from one equal-length watch. How many sightings were recorded altogether?',bars:[{label:'Monday',value:8},{label:'Tuesday',value:5},{label:'Wednesday',value:7}],answer:20,hint:'Add all three counts.',explanation:'8 + 5 + 7 = 20 sightings. The equal watch lengths make the daily comparison more useful.'},
 {prompt:'What is the mean number of sightings per watch?',bars:[{label:'Watch 1',value:6},{label:'Watch 2',value:10},{label:'Watch 3',value:5},{label:'Watch 4',value:7}],answer:7,hint:'Mean = total divided by the number of watches.',explanation:'6 + 10 + 5 + 7 = 28. There are 4 watches, so the mean is 28 ÷ 4 = 7.'}]},
 {id:'detective',title:'The lighthouse mystery',subject:'English',strand:'Reading',kind:'detective',icon:'⌕',colour:'#E2E3F6',description:'Follow the clues. Read between the lines.',objective:'Retrieve information and justify inferences with textual evidence.',source:'english',tasks:[
 {passage:'Orla carried a red notebook to the old lighthouse. At the gate, she found a small brass key tied to blue string. A note said, “For the keeper.” Orla put the key in her pocket and knocked on the door.',prompt:'What was tied to the key?',options:['A red ribbon','Blue string','A paper map'],answer:'Blue string',hint:'Look again at the sentence that begins “At the gate”.',explanation:'The story says the brass key was tied to blue string. The notebook, not the string, was red.'},
 {passage:'Orla knocked. No one answered, but warm light slipped beneath the door. Two wet footprints crossed the dry floor inside. Then she heard a chair scrape. She tucked the key safely into her pocket and waited.',prompt:'Which clue most strongly suggests someone is inside right now?',options:['The key is in her pocket','A chair scrapes inside','The floor is dry'],answer:'A chair scrapes inside',hint:'Which clue suggests a movement happening now?',explanation:'The sound of the chair suggests someone has just moved it. The footprints could have been left earlier. This is an inference, not absolute proof.'},
 {passage:'“The lamp has gone out,” whispered the keeper. Orla looked at the bright beam sweeping over the sea. Then she noticed the small, dark desk lamp beside his map. “I can fetch a candle,” she said. The keeper smiled.',prompt:'Why does Orla change her understanding of “the lamp”?',options:['She notices the dark desk lamp','The lighthouse beam stops moving','The keeper asks her to leave'],answer:'She notices the dark desk lamp',hint:'Compare the bright beam with the small lamp on the desk.',explanation:'The bright beam shows that the lighthouse lamp still works. The dark desk lamp provides new evidence, so Orla revises her interpretation.'}]},
 {id:'words',title:'The word tinkerer',subject:'English',strand:'Writing · Grammar and spelling',kind:'words',icon:'Aa',colour:'#F9E5C7',description:'Put words together and make meaning shine.',objective:'Use sentence structure, punctuation and spelling to communicate clearly.',source:'english',tasks:[
 {prompt:'Tap the words in order to make a sentence that starts with “The”.',words:['sang.','robin','The'],answer:'The robin sang.',hint:'Begin with the capital letter. Finish with the word that has a full stop.',explanation:'“The robin sang.” starts with a capital letter, names who did the action, and ends with a full stop.'},
 {prompt:'Build the question starting with “Where”. Keep its question mark.',words:['key?','the','Where','is'],answer:'Where is the key?',hint:'A question can begin with Where. The question mark goes at the end.',explanation:'“Where is the key?” asks for information. Its capital letter and question mark help the reader.'},
 {prompt:'Choose the correctly spelled word to complete: “The boats carried their ___ safely home.”',options:['passengers','passangers','pasengers'],answer:'passengers',hint:'Start with passenger, then add s. Notice the double s and the e after g.',explanation:'Passenger + s = passengers. Breaking the word into chunks can help you remember its spelling.'}]},
 {id:'story',title:'The story studio',subject:'English',strand:'Writing',kind:'story',icon:'✎',colour:'#F6DED7',description:'A small idea. A world only you can make.',objective:'Plan, compose and revise imaginative writing for an audience.',source:'english',tasks:[
 {prompt:'A tiny door appears in a tree. Plan a character and a place, then write an opening for a friend to read. Read it aloud and improve one word.',hint:'Try: “Under the oldest tree, …” What does your character notice?',checklist:['I introduced a character and place','I checked capitals and full stops','I improved one word after rereading'],explanation:'A clear opening helps your reader picture the scene. There is no single right story; your checklist records reflection, not a mark.'},
 {prompt:'Write a short adventure for a younger reader. Plan a character, a problem and a solution. Draft it, then revise a sentence to make events clearer.',hint:'Use three parts: what the character wants, what goes wrong, and how they respond.',checklist:['My events have a clear order','I described a problem and a response','I revised a sentence for my reader'],explanation:'Writers plan and revise. Ask a reader which moment they pictured most clearly, then decide what to improve.'},
 {prompt:'Write a mysterious scene for a class anthology. Plan a setting and a hidden secret. Use a sensory detail and vary your sentence lengths. Revise to build suspense.',hint:'Reveal clues slowly. A short sentence after a long one can change the pace.',checklist:['I chose details to create a mood','I varied sentence lengths intentionally','I revised with my audience in mind'],explanation:'Different choices create different effects. Discuss which words create suspense and why; an adult can help review your choices.'}]},
 {id:'talk',title:'Listen, imagine, share',subject:'English',strand:'Talking and Listening',kind:'talk',icon:'“ ”',colour:'#DFEDCE',description:'Big ideas begin with a good conversation.',objective:'Listen, give instructions and discuss ideas with reasons.',source:'english',tasks:[
 {prompt:'With an adult or partner: ask them to read this while you listen. Ask to hear it again whenever helpful. “A fox found a blue scarf by the river. It took the scarf to the owl, who hung it on a branch.” Retell what happened, then ask your partner a question.',hint:'Listen for who, what and where. It is fine to ask to hear it again.',checklist:['My partner read the story aloud','I retold the events in order','I asked and listened to a question or answer'],explanation:'Adult guidance: listen for the fox, scarf, river and owl in a sensible sequence. Invite a retry if details are missing. No recording is made.'},
 {prompt:'With a partner and paper: secretly draw a house using a square, triangle and two rectangles. Describe how to draw it without showing it. Compare pictures, swap roles and discuss which instructions helped.',hint:'Name shapes and use position words such as above, inside, left and right.',checklist:['We both gave and followed instructions','We asked for clarification when needed','We discussed one way to improve our instructions'],explanation:'Adult guidance: look for clear order and position words, listening and useful clarification. Different pictures start a discussion; they do not mean failure.'},
 {prompt:'With an adult or partner: should a school garden have more flowers or more space to play? Take different views. Give a reason, listen, summarise their view fairly, then suggest a compromise.',hint:'Try “I understand your point that … My reason is … Could we …?”',checklist:['I supported my view with a reason','I summarised my partner’s view fairly','We discussed a possible compromise'],explanation:'Adult guidance: attend to turn-taking, respectful listening and reasons. There is no single correct opinion. Discuss how each person responded to the other.'}]}
];
export const activities: Activity[] = [...coreActivities,...maths,...english];
export const planned = ['Detailed teacher review of every objective and challenge','Larger banks of equivalent tasks for robust adaptive practice','Richer in-app drawing, spreadsheets and media composition','Optional progress backup and shared-device child profiles'];
