export type CoverageRow={id:string;source:'maths'|'english';page:number;topic:string;activities:string[]};
const rows=(source:'maths'|'english',page:number,entries:[string,string,string[]][]):CoverageRow[]=>entries.map(([id,topic,activities])=>({id,source,page,topic,activities}));
// Topic labels are concise paraphrases, not an official assessment framework.
export const coverage:CoverageRow[]=[
 ...rows('maths',1,[
 ['MP1','Select resources',['reasoning']],['MP2','Find task information',['reasoning','collect-data']],['MP3','Work systematically',['reasoning','budget']],['MP4','Problem-solving strategies',['reasoning','mental']],['MP5','Mathematical language',['reasoning','garden']],['MP6','Compare methods',['reasoning']],['MP7','Symbols and diagrams',['coordinates','unknown','directions']],['MP8','Present results',['collect-data','data-tools']],['MP9','Patterns and predictions',['sequences','machines']],['MP10','Explain open problems',['reasoning']],['MP11','Generalisations',['reasoning','machines']],['MP12','Check reasonableness',['estimate','reasoning']],
 ['MN1','Whole-number notation',['place-value']],['MN2','Decimal place value',['decimal-scaling','place-value']],['MN3','Estimation',['estimate']],['MN4','Fraction equivalence',['fractions','fraction-links']],['MN5','Negative numbers',['negative']]]),
 ...rows('maths',2,[
 ['MN6','Sequences',['sequences']],['MN7','Number properties',['factors','tables']],['MN8','Function relationships',['machines']],['MN9','Unknown quantities',['unknown']],['MN10','Mental calculation',['mental']],['MN11','Times tables',['tables']],['MN12','Operations and brackets',['operations']],['MN13','Money calculations',['shop','budget']],['MN14','Budgeting and payments',['budget']],['MN15','Saving and value',['budget']],['MN16','Foreign currency',['currency']],
 ['MM1','Estimate measures',['measure-estimate']],['MM2','Measurement accuracy',['measure-estimate']],['MM3','Metric conversions',['units']],['MM4','Perimeter, area, volume',['garden','volume']],['MM5','Scale',['scale']],['MM6','Clocks and timetables',['time']]]),
 ...rows('maths',3,[
 ['MS1','2-D properties and patterns',['shapes','symmetry']],['MS2','3-D properties and nets',['solids']],['MS3','Movement and coding',['directions']],['MS4','Angles',['angles']],['MS5','Coordinates',['coordinates']],['MD1','Collect and present',['collect-data']],['MD2','Explain conclusions',['data','collect-data']],['MD3','Tables and graphs',['frequency','data']],['MD4','Data sheets and tools',['collect-data','data-tools']],['MD5','Mean and range',['averages','data']],['MD6','Chance vocabulary',['chance']],['MD7','Possible outcomes',['chance']],['MD8','Likelihood comparisons',['chance']]]),
 ...rows('english',1,[
 ['EL1','Respond to heard texts',['listen-texts']],['EL2','Retell and interpret',['talk','retell-drama']],['EL3','Discussion participation',['discussion']],['EL4','Discussion conventions',['discussion']],['EL5','Reasoned viewpoints',['discussion','talk']],['EL6','Give and follow guidance',['instructions','talk']],['EL7','Drama experiences',['retell-drama']],['EL8','Improvisation',['retell-drama']],['EL9','Describe experiences',['retell-drama']],['EL10','Oral presentations',['presentations']],['EL11','Purposeful questions',['questions']],['EL12','Conversation contexts',['questions']],['EL13','Voice and register',['voice','presentations']],['EL14','Expressive reading',['voice']],['EL15','Spoken variation',['voice']],
 ['ER1','Supported reading',['reading-habits']],['ER2','Varied texts',['reading-library']],['ER3','Sustained independent reading',['reading-habits']],['ER4','Reading preferences',['reading-habits']],['ER5','Evaluate sources',['source-detective']],['ER6','Represent understanding',['reading-response']]]),
 ...rows('english',2,[
 ['ER7','Language effects',['media','reading-library']],['ER8','Media comparison',['media']],['ER9','Evidence and inference',['detective']],['ER10','Revise interpretations',['detective']],['ER11','Prepared reading aloud',['voice']],['ER12','Word-reading strategies',['word-strategies']],['ER13','Reading purposes',['reading-purpose']],
 ['EW1','Supported and digital composition',['story','factual-writing']],['EW2','Text layout',['layout']],['EW3','Poetry and wordplay',['poetry']],['EW4','Audience and purpose',['factual-writing','layout']],['EW5','Plan and redraft',['story','writers-style']],['EW6','Ideas and opinions',['story','factual-writing']],['EW7','Mood and effect',['writers-style']],['EW8','Personal style',['writers-style']],['EW9','Multimodal presentation',['digital-composition']],['EW10','Speech and writing',['spoken-written']],['EW11','Spelling strategies',['spelling','words']],['EW12','Grammar and punctuation',['grammar','words']],['EW13','Handwriting',['handwriting']]])
];
