/** Original AI-authored resources. NI KS2 professional sign-off and pupil observation pending. */
export type EnglishProject = {title:string;source:'english';goal:string;materials:string[];steps:string[];model:string;evidence:string[];rubric:{support:string;developing:string;secure:string};tool?:'reading'|'writing'|'table'|'coordinates';text?:string;stages?:string[];audio?:string;starterRows?:string[][]};
export type LibraryText = {id:string;title:string;genre:string;text:string};
export const readingLibrary:LibraryText[]=[
{id:'blue-box',title:'The Blue Box at the Bridge',genre:'Mystery fiction',text:`Niamh noticed the blue box on her third journey across the little footbridge. On the first journey she had been carrying a football. On the second, she had been thinking about the match. Now she had time to look.

The box stood beneath the bridge noticeboard. Somebody had painted a white bird on its lid. A small card read, “Please leave something worth keeping.”

“Treasure,” said Dara, who had followed her. He felt in his pocket and produced a smooth stone. “I could leave this.”

Niamh lifted the lid. Inside were a photograph of an empty bench, a folded piece of paper and a button with a piece of red thread still attached. There were no coins or jewels.

The photograph puzzled her. Why keep a picture of a bench with nobody on it? She turned it over. On the back, somebody had written, “Where Granny taught me to whistle.”

Dara stopped rolling his stone between his fingers.

Niamh unfolded the paper. It was a recipe for soup, covered in little corrections. “More pepper,” said one note. “Less pepper!” said another, in different handwriting.

Then a woman carrying a shopping bag paused beside them. She pointed to the button. “My first coat,” she said. “My dad sewed that on so badly that it lasted only a week. We laughed about it for years.”

Niamh looked again at the ordinary objects. The box had not changed, but her idea of treasure had.

Dara placed his stone beside the button. On a blank card he wrote, “The stone I found when my little brother finally dared to cross the bridge.”

Niamh had nothing to add yet. She closed the lid carefully and decided that, on her next journey, she would pay more attention.`},
{id:'survey-guide',title:'A Fair Question for the Reading Corner',genre:'Explanatory information text',text:`A class wants to improve its reading corner. Before buying anything, the children decide to ask readers what would help. A survey can collect useful information, but its question and method matter.

Start with one clear purpose. “What should we buy?” is too broad when nobody knows the budget. A more useful question might be, “Which of these three additions would you use most: a cushion, a book stand or a small lamp?” An adult should first check that all three choices would be suitable for the space.

Give each person the same question and choices. If one child hears “Would you like a lovely cushion?” while another hears “Would you like a book stand?”, the wording may influence the answers. Ask neutrally and allow people to say that none of the choices suits them.

Decide who will answer. Five friends in one group cannot speak for every reader in a school. Record how many people took part and explain who they were. Do not write their names unless there is a genuine, agreed need. For a simple class survey, anonymous totals are usually enough.

Make a record sheet before collecting answers. Use one mark for each response. Check the marks with a partner and convert them into totals. Label any chart clearly so that another person can understand what was counted.

Finally, separate a finding from a decision. If eight of twelve respondents choose a cushion, that is a finding about those twelve people. It does not prove that everyone loves cushions. Cost, access, safety and other readers’ needs may still affect the decision.

A useful report states the question, method, results and limits. It can also suggest a next step, such as trying a borrowed book stand before spending money.`},
{id:'practice-diary',title:'The Day I Asked to Start Again',genre:'Fictional diary',text:`Tuesday

I thought I knew my presentation. At breakfast I explained the whole thing to the cereal box: how our group made a model harbour, where the boats would go and why we added a wide path beside the water. The cereal box seemed impressed. It did not ask any questions.

At school, things felt different. When I stood beside the model, all I could see were faces waiting for me to begin. I said, “This is our harbour,” and then forgot what came next.

My teacher waited. Nobody laughed. Still, the silence felt enormous.

I looked at our plan. Three little drawings sat at the top: a boat, a path and a bench. I remembered why we had made them. They were not decorations. They were reminders.

“Could I start that part again?” I asked.

This time I pointed to the boat. I explained where it would stop. Then I pointed to the path and described how people could move around without squeezing past the bench. I did not use the exact words I had practised, but the explanation made sense.

Afterwards, Róisín asked why our path had no steps. I knew that answer. We had wanted a route that more people could use. Her question helped me say the most important thing in our plan.

I am not suddenly someone who loves standing in front of a room. My hands were still shaky when I sat down. But I know something now that I did not know at breakfast: beginning again is allowed.

Tomorrow I will change my reminder card. Fewer sentences. Clearer pictures. And at the bottom, in small letters, I will write, “Pause. Look. Begin again.”`},
{id:'fable-bell',title:'The Bell That Nobody Rang',genre:'Original fable',text:`In a village beside a wood, a hare hung a bell outside the meeting hut. “Ring this whenever you need help,” she told the other animals.

The mole could not reach the rope. The tortoise needed so long to cross the square that the meeting often ended before he arrived. The owl slept during the bright afternoon, when most meetings took place.

Yet the hare was pleased. “Everyone has a bell now,” she said.

For a week, nobody rang it.

One morning a squirrel found the hare polishing the brass. “Perhaps nobody needs help,” the hare said.

“Perhaps,” said the squirrel. “Or perhaps you have given everybody the same thing without asking whether they can use it.”

The hare frowned. The bell was large. The rope was strong. What else could a bell need?

They visited the mole, who showed them how high the rope hung. They walked with the tortoise and discovered how far the hut was from his home. They spoke to the owl at dusk and learned that an afternoon meeting was no use to her.

So the animals made a new plan. They lowered a second loop of rope. They agreed that a message could be delivered instead of a visit. They varied the meeting time and left a clear record of decisions for anyone who could not attend.

The next day, the bell rang twice. Three messages arrived. At dusk, the owl came with a question that nobody else had considered.

The hare still polished the bell, but less often. She spent more time listening.

“A bell is an invitation,” she told the squirrel. “It is not proof that everyone has been heard.”

The squirrel nodded. In the square, the mole reached the new loop and gave it a careful tug.`},
{id:'poem-platform',title:'When the Platform Wakes',genre:'Narrative poem',text:`Before the first traveller opens the gate,
Before there is anyone early or late,
The platform lies quiet, a page without print,
With puddles that hold the first sunlight’s hint.

A porter arrives with a brush and a key.
He whistles a tune to the listening tree.
The tree does not answer; its branches just sway,
As if they are waving the darkness away.

Then footsteps come tapping, first two and then four.
A bag bumps a knee by the newspaper door.
A child counts the windows, a grown-up the time,
While somebody practises words for a rhyme.

A sparrow lands lightly beside a small crumb.
The rails wait below with their faraway hum.
An engine is coming; the morning grows wide.
The platform draws people towards either side.

One traveller carries a parcel of wool.
One carries a notebook with pages half full.
One carries a question too large for a bag:
Will anyone notice my bright yellow tag?

A friend spots the traveller standing alone.
The question grows smaller; the friend is well known.
They talk about nothing, then something, then more,
And laugh at a story they both heard before.

The train gives a shiver. The doors slide apart.
A journey begins with the lift of a heart.
There are places to visit and people to meet,
And the rhythm of wheels under each waiting seat.

Soon quiet returns to the brush and the key.
A sparrow looks down from the listening tree.
The puddles reflect what the travellers missed:
A cloud like a mitten, a twist of white mist.

The platform is empty, but not quite the same.
It has carried each greeting and whispered each name.
A page has been written in footsteps and rain.
Tomorrow the morning will write it again.`},
{id:'play-shelter',title:'Room Beneath the Shelter',genre:'Short play script',text:`Characters: Asha, Ben and a caretaker. Setting: an imaginary school yard during a sudden shower. A covered shelter has a bench, a large model and several bags.

[Asha carries the model towards the shelter. Ben stands beside the bench.]

ASHA: Please move those bags. The model is getting wet.

BEN: I cannot put them on the ground. The ground is wet too.

ASHA: Then move them somewhere else!

[Ben folds his arms. Asha grips the model more tightly.]

CARETAKER: Pause for a moment. What does each thing need?

ASHA: The model needs a dry, flat place. We made it from card.

BEN: The bags need somewhere dry. Two have books inside.

CARETAKER: And what do the people need?

[There is a short silence.]

BEN: Room to stand without blocking the entrance.

ASHA: I did not think about that. Could the model go at one end of the bench?

BEN: It is too long. But we could put the bags on the hooks behind us.

ASHA: Are the hooks strong enough?

CARETAKER: Those hooks are for bags. Keep the straps away from the doorway and I can help you reach.

[Ben moves the bags with help. Asha places the model on the bench. They step back from the entrance.]

BEN: I thought you only cared about the model.

ASHA: I thought you were refusing to help. I should have explained why I was worried.

CARETAKER: You both had useful information. It was difficult to hear while you were giving each other orders.

[A large drop splashes onto the edge of the bench.]

BEN: There is one more problem.

ASHA: The roof?

BEN: A tiny gap, right above the cardboard tower.

[They look at the model, then at each other.]

ASHA: This time, shall we start with a question?

BEN: Yes. Where could the tower stay dry?`},
{id:'report-display',title:'Model Exhibition Draws Different Ideas',genre:'Imaginary news report',text:`An imaginary primary school held a model exhibition on Friday afternoon. Four groups displayed their designs for a small public garden. Twenty-four invited visitors attended, according to a count made at the entrance. The count recorded visits, so the organisers could not be certain that every visit represented a different person.

Each design included a place to sit and a route through the garden. The groups made different choices about how to use the remaining space. One added a pond, another a growing area, a third a patch for games and a fourth a quiet corner with shelter.

Visitors could leave an anonymous comment beside each model. “I like having a sheltered place to read,” one comment said. Another asked how the paths would be kept clear. Several comments raised questions rather than choosing a favourite.

The organisers did not hold a vote. “We wanted to understand the ideas before judging them,” a pupil organiser explained. “A beautiful model might still leave practical questions unanswered.”

During the exhibition, one group changed its display label. It had described its route as suitable for everyone. After a visitor asked about the narrow entrance, the group replaced this with a more careful statement: the route was intended to improve access, but its dimensions still needed checking.

No real garden will be built from the models this week. The next activity is a discussion about costs, maintenance, safety and access. An adult will help the class distinguish features that can be tested with the models from questions requiring specialist advice.

The comments and revised labels will be kept with the class plans. Organisers hope the record will show how the designs changed as people listened to one another.`},
{id:'letter-books',title:'A Proposal for a Book-Trying Basket',genre:'Persuasive letter',text:`Dear School Council,

I would like our class to try a book-trying basket beside the reading corner. It would hold a small, changing selection of books that children could explore before choosing something for longer reading. I think this could help readers who find it difficult to decide where to begin.

My proposal is not to buy a new collection immediately. We could first borrow suitable books from shelves we already use. A mixture might include a story, a poetry book, an information book and a text with pictures that contribute to its meaning. Readers could suggest other kinds of text too.

Each book could have a short recommendation card. The card should explain what a reader might enjoy, rather than say that everyone must like it. For example, “This story has a puzzle that changes when a new clue appears” is more useful than “The best book ever”. Children could recommend books through words, symbols or a short supported conversation.

I understand that a basket might become untidy or block the path. We should choose a safe position with an adult and agree a simple return routine. We should also make sure that reaching or lifting a book is not a barrier. If the basket is unsuitable, a labelled shelf might serve the same purpose.

After a fortnight, we could ask whether the selection helped people discover something new. We should include readers who did not use it, because their reasons may help us improve the idea. Counting borrowed books alone would not tell us whether the reading was enjoyable or useful.

Please could we discuss a small trial before deciding whether to continue? I would be happy to help prepare the first recommendation cards.

Yours sincerely,

A reader with too many possible favourites`}
];

const text=(id:string)=>{const item=readingLibrary.find(x=>x.id===id);if(!item)throw new Error(`Missing reading resource ${id}`);return item.text;};
const access='Use your usual access tools and comfortable response method. An unavailable partner or resource means observation is pending, not low ability. Reading/spelling/handwriting goals require a note of what was read, spelled or written independently; listening to a text is not evidence of independent decoding.';
const project=(title:string,goal:string,materials:string[],steps:string[],model:string,evidence:string[],first:string,next:string,extra:Partial<EnglishProject>={}):EnglishProject=>({title,source:'english',goal,materials:[...materials,access],steps,model,evidence,rubric:{support:`After accessible modelling, needs a learning prompt to ${first}. Record the prompt and teach that part again.`,developing:`Can ${first}, but needs a learning prompt to ${next}. Record an example and the next teaching step.`,secure:`Can ${first} and ${next}, using usual access supports without a prompt that supplies the idea. Record the observed evidence; one project does not establish lasting mastery.`},...extra});
const listeningBank=`FICTION: Niamh found a box beneath the bridge. It contained a button and a photograph of an empty bench. The photograph mattered because it showed where somebody had learned to whistle with their granny.\n\nPOEM: “The platform lies quiet, a page without print.” Imagine the platform before anybody arrives.\n\nDRAMA: ASHA: “Please move the bags. The model is getting wet.” BEN: “The bags have books inside. They need to stay dry too.”\n\nANNOUNCEMENT: “The imaginary exhibition opens at two in the hall. Please leave the doorway clear. Visitors may write an anonymous comment beside each model.”`;
export const englishProjects:Record<string,EnglishProject>={
EL1:project('Four ways to listen','Compare meaning across fiction, poetry, drama and an announcement.',['Built-in read-aloud or a willing reader; headphones optional'],['Listen to one section of the supplied bank without looking at the transcript, if that access method suits you. Request another hearing whenever useful.','Record two things heard and one response: a picture, question, feeling or requested action.','Repeat with a different section on another visit. Explain which features tell you it is a story, poem, dialogue or announcement.','Compare all four entries. Ask an adult to record what they observed rather than infer listening from typed answers alone.'], 'The announcement gives a place and time, then asks visitors to keep a doorway clear. The drama gives two people’s different needs. I can respond by explaining both needs rather than choosing a winner.', ['Four dated responses, including any access method','One comparison of information, imagery and speaker purpose','Adult observation of listening where available'], 'retell the main meaning from one heard section','compare the purposes or effects of two different kinds of heard text',{tool:'reading',text:listeningBank,audio:listeningBank}),
EL2:project('Retell across three visits','Retell and interpret a story, an experience and a curriculum account.',['The supplied library text; a partner for feedback if available'],['Visit 1: read The Blue Box. Make a beginning/change/ending plan and retell it in your own words.','Visit 2: describe a real or invented occasion when something ordinary became important. Do not include private locations or other people’s personal details.','Visit 3: explain how the class in A Fair Question might collect survey answers. Distinguish what the source says from details you invent.','Keep all three entries. Ask a listener which event or step was unclear; revise that part and record the change.'], 'Blue Box plan: Niamh expects valuable treasure → the notes explain personal memories → she rethinks what is worth keeping. A retelling should preserve this change even if the exact wording differs.', ['Three dated retellings from different contexts','Source detail supporting an interpretation','A listener’s specific feedback and a revision'], 'sequence the important events or steps','interpret a change and adjust the retelling for a listener',{tool:'writing',text:text('blue-box')+'\n\nSECOND SOURCE\n'+text('survey-guide')}),
EL3:project('A group decision with real constraints','Participate in discussions for English, maths and design purposes.',['Two or more willing participants; a teacher is needed to observe actual class participation'],['Round 1, reading: use the three supplied proposals to choose which would encourage reading. Each participant contributes through speech, AAC, typing or a chosen representative.','Round 2, maths: use a pretend £20 budget. Cushion £8; book stand £12; recommendation-card pack £4. Consider at least two affordable combinations.','Round 3, design: check a proposed position against a clear doorway and access to shelves. Ask what information is still missing.','Save each decision with reasons, one response to someone else and any unresolved disagreement. Class participation remains pending until a teacher observes it.'], 'One book stand plus two card packs costs £20. That is affordable, but cost alone does not show whether the stand is reachable or whether readers want it.', ['A record for each curricular purpose','Evidence of responding to another contribution','Teacher observation or clearly marked not yet observed'], 'make a relevant contribution and acknowledge another idea','adapt a reason or question to the discussion’s curricular purpose',{tool:'table',text:'Proposals: a comfortable reading position; an easier way to hold a book; short cards helping readers choose. All prices and situations are imaginary.',starterRows:[['Purpose','My contribution','Response to another idea','Decision / unanswered question'],['Reading','','',''],['Budget','','',''],['Design','','','']]}),
EL4:project('A discussion people can join','Use and evaluate explicit discussion conventions.',['A willing discussion group or supported role play; optional turn card'],['Agree three rules before discussing whether a fictional reading corner needs quiet times. Suggested rules: one contribution at a time; ask before assuming; invite a contribution without forcing it.','Assign rotating roles: opening question, invitation, summary. Nobody must speak aloud to have a role.','An observer records one exact example of listening, clarification and building on an idea. Avoid ratings based on confidence or speaking speed.','Pause halfway. Check whether the rules helped everybody participate, change one if necessary, then finish and review.'], 'Invitation: “We have heard two ideas. Does anyone want to add something through a message or a turn?” Summary: “We agree on quiet reading times, but have not decided when partner reading fits.”', ['Agreed rules and one later change','Three specific observed examples','A participant’s view of whether the process was fair'], 'follow an agreed turn-taking and listening convention','notice a participation barrier and help adapt the process',{tool:'table',starterRows:[['Convention','Observed words or action','Effect / next change'],['Listening','',''],['Clarification','',''],['Inviting / building on ideas','','']]}),
EL5:project('Reasons that travel','Build and respond to reasons in three different decisions.',['Partner, or two written role positions for solo preparation'],['Decision 1: choose a mystery or information text for a fictional group. Give a reason tied to their interest in finding out how something works.','Decision 2: respond to the book-basket letter. Identify a reason, a concern and an answer to that concern using the text.','Decision 3: decide between a sheltered reading spot and an open play area. Represent both views fairly before offering a proposal.','After each round record claim → reason/evidence → other view → response. Compare whether your later responses engage with the other view more directly.'], 'Claim: try the basket. Reason: it offers several kinds of text without immediate purchases. Concern: it may block access. Response: choose an adult-checked position, or use a labelled shelf instead.', ['Three reason chains across contexts','A fair summary of an alternative view','A response that addresses rather than ignores that view'], 'support a claim with a relevant reason','evaluate and respond fairly to a counterargument',{tool:'writing',text:text('letter-books')}),
EL6:project('Directions your partner can check','Give and repair instructions using a shared map and a making task.',['Paper or an accessible grid representation; partner for information-gap test'],['Share this map: columns A–D left to right, rows 1–4 bottom to top; library A1, pond A3, bakery C3, park C2. Start at A1 facing increasing row numbers.','Give a route to pond, bakery and park, ending facing D2. Partner repeats the instructions before moving a counter or naming each square. Record any clarification needed.','Then explain making a label from paper and a pencil: write a title, add a border, put it beside a model. Let the partner identify any missing information.','Revise both instructions and test them again. An unavailable partner means preparation complete, observation pending.'], 'Map route: forward two to A3; right, forward two to C3; right, forward one to C2; left to face D2. “Put it there” is weaker than “Put the label beside the model’s front edge”.', ['Original and revised directions','Partner’s route or repeated sequence','One clarification and the repair it prompted'], 'give a followable sequence with fixed reference points','use a listener’s clarification to repair ambiguity',{tool:'writing',text:'Map key: A1 library; A3 pond; C3 bakery; C2 park. All positions are imaginary. Both partners use the same orientation.'}),
EL7:project('A small drama programme','Try several drama forms across stories and curricular decisions.',['Willing partners if possible; seated, symbolic or written role alternatives'],['Session 1: use The Bell That Nobody Rang. Create three freeze frames or labelled still pictures: the unused bell, the listening visits, the changed meeting. Explain the turning point.','Session 2: read Room Beneath the Shelter as a role play. Pause before the caretaker’s first question and imagine what each character is thinking.','Session 3: hold a mock garden-design meeting. Roles: designer, visitor asking about access, and person maintaining the space. Each must ask one useful question.','Keep a dated entry for each form. Reflect on how you responded to another role. Actual participation and development need adult observation across sessions.'], 'A freeze frame of the hare polishing while others stand far away can represent the gap between an invitation and usable access. It is an interpretation supported by the fable, not a measure of acting talent.', ['Three dated drama forms and their purposes','One supported interpretation in each session','Observed response to another role, or pending marker'], 'represent a relevant situation or character','adapt a contribution in response to another role across more than one drama form',{tool:'writing',text:text('fable-bell')+'\n\nPLAY\n'+text('play-shelter')}),
EL8:project('What happens after the last line?','Improvise a responsive scene with clear character knowledge.',['A partner, or alternating written/symbolic role contributions'],['Read the supplied play. Start a new scene after “Where could the tower stay dry?” Do not write the whole ending first.','Role cards: Asha knows the model has a removable tower; Ben knows there is a clear shelf; caretaker knows the shelf must be checked before loading it. Share each fact naturally during the scene.','Introduce one change: the shelf is too narrow for the whole model. Respond to what the other characters actually say rather than recite a prepared speech.','Save the scene or a sequence summary. Identify one moment when another contribution changed your response.'], 'Ben: “The shelf is clear.” Asha: “The whole model will not fit, but the tower lifts off.” Caretaker: “Let us check the shelf before putting it there.” Each turn uses new information.', ['Scene or sequence record','At least one responsive change','Observation of participation or explicit pending marker'], 'contribute consistently from a role’s knowledge','develop the scene in response to another contribution or new constraint',{tool:'writing',text:text('play-shelter')}),
EL9:project('Describe so somebody can picture it','Describe a place, event, object and imagined experience using relevant detail.',['An ordinary safe object; text descriptions can replace physical handling'],['Object: describe a button without naming it. Possible details: round, two holes, smooth edge, used on clothing. Partner guesses and explains which details helped.','Place: describe the empty platform from the poem before travellers arrive, distinguishing quoted clues from your imagined additions.','Event: describe the moment the diary writer asks to begin again, using sequence and feelings supported by the text.','Experience: invent a journey carrying an unusual but ordinary object. Keep four separate entries and compare which details help a listener most.'], 'Instead of “a nice thing”, say “a small round disc with two holes, sewn to a coat”. The details identify function and appearance without needing colour alone.', ['Four kinds of description','A detail chosen for a listener’s purpose','Source-based and invented details labelled separately'], 'select relevant descriptive details','organise and adapt them so another person can picture or identify the subject',{tool:'writing',text:text('poem-platform')+'\n\nDIARY\n'+text('practice-diary')}),
EL10:project('A presentation inside the app','Prepare and refine a short message with a visual planning aid.',['A familiar listener or group for observed delivery; accessible communication method'],['Use the supplied report to plan a presentation explaining why the models were not ranked by a vote.','Prepare three panels in your saved writing: title/question; two important facts; conclusion/next step. Use a labelled table or a simple graphic in the workspace where available.','Add speaker notes that explain rather than duplicate every visual word. Rehearse with your preferred communication method; a simulated rehearsal can prepare but cannot replace an observed presentation.','Present to a familiar audience when available. Record a question, your answer and a change you would make for younger listeners.'], 'Panel title: “More than a favourite”. Two facts: visitors left comments; an access claim was revised. Conclusion: practical questions should be investigated before selecting a design.', ['Presentation panels and notes','Audience question and response','Specific observer comment and revision, or pending delivery'], 'organise accurate content for a stated audience','use a visual purposefully and adapt an explanation after a question',{tool:'writing',text:text('report-display')}),
EL11:project('From a leading question to a useful one','Refine questions and follow actual answers.',['Partner for interview; supplied answers for independent rehearsal'],['Study this model: “You hated the long silence, didn’t you?” assumes a feeling. Replace it with “How did the silence feel?”','Use the diary. Write one question about an event, one about an opinion and one about a feeling without suggesting answers.','Rehearsal answer: “The drawings helped me remember.” Ask a follow-up connected to drawings. New answer: “The path picture reminded me about access.” Ask another relevant follow-up.','If a partner is available, interview them in a fictional role. Preserve questions, actual answers and a fair summary; do not collect private information.'], 'Question: “What helped when your words stopped?” Answer: “The drawings.” Follow-up: “Which drawing helped most, and why?” This follows the answer rather than switches topic.', ['Before/after versions of a leading question','A linked sequence of at least two follow-ups','Summary checked against the supplied or actual answers'], 'ask a relevant question without supplying its answer','refine or follow up the question in response to information heard',{tool:'writing',text:text('practice-diary')}),
EL12:project('One need, four conversations','Adapt language to several formal and informal situations.',['Partner optional; written dialogue supports solo preparation'],['Need: find out whether a fictional exhibition has a quiet visiting time. Write or role-play a request to a friend, school office, museum guide and small class group.','For each, state what the listener already knows and what you must explain. Both formal and informal language can be respectful.','Add a follow-up when the answer is “I am not sure”. Decide how to ask for help without making demands or disclosing unnecessary personal details.','Compare the four versions. Explain two context-driven changes; do not rank people’s accents or home language varieties.'], 'Friend: “Do you know when the hall is quieter?” Office: “Could you tell me whether the exhibition has a quieter visiting time, or who I could ask?” The second gives more context to an unfamiliar listener.', ['Four context-labelled exchanges','Two explanations for language choices','Observation of actual conversations, if performed'], 'make a clear request in more than one context','explain and adapt wording when the listener’s knowledge or relationship changes',{tool:'writing'}),
EL13:project('A voice that carries meaning','Adapt message, pace and emphasis using a comfortable communication method.',['Voice, AAC, signing with appropriate support, typed delivery or annotated script; listener optional'],['Use the message “The entrance must stay clear so everyone can get through.” Mark which words carry its main meaning.','Prepare one version for a younger group and another for an adult organiser. Explain any vocabulary change.','Try pauses, emphasis or AAC chunking. Ask a listener whether the reason is easy to understand; comfortable audibility is the goal, not volume or speed.','Save the two scripts and one specific improvement. If speech production itself is not accessible, record the demonstrated audience/language decisions rather than claiming a speech assessment.'], 'Younger audience: “Leave a clear way in. People need room to pass.” A pause separates the action from the reason. An adult version can retain entrance and explain the access purpose.', ['Two audience-labelled versions','Annotated emphasis, pauses or message chunks','Feedback on clarity and an accurate access-method note'], 'communicate the main idea in a comfortable accessible form','adapt register or delivery choices to audience feedback',{tool:'writing',audio:'Please leave a clear way in. People need room to pass. The entrance must stay clear so everyone can get through.'}),
EL14:project('Listen, mark, rehearse, reflect','Prepare expressive reading and retain observation evidence.',['Supplied poem; optional built-in synthetic read-aloud; a human reader for expressive modelling if available'],['Listen to the optional device voice while following the text. It models access to words and punctuation, not a professionally acted or validated expressive performance.','Select one stanza. Mark a pause with / and an emphasis choice with capital letters. Explain what each choice adds to meaning.','Ask a willing adult to model two different interpretations, or discuss two annotated alternatives if a voice model is unavailable. Then read or rehearse using your access method.','Record the observer’s exact comment and your revised annotation. Note which evidence concerns interpretation and which concerns actually heard reading.'], '“The platform lies QUIET, / a page without print.” Stressing quiet and pausing can convey stillness. A quicker later stanza may convey arrivals. There is no single correct performance.', ['Original and revised marked stanza','Reason for two delivery choices','Human reading observation or clear pending status'], 'choose pauses or emphasis that fit the words','explain their effect and refine a reading after specific feedback',{tool:'reading',text:text('poem-platform'),audio:text('poem-platform')}),
EL15:project('Language choices and belonging','Compare register, colloquial expressions and language variation respectfully.',['Supplied context cards; optional adult discussion of familiar expressions'],['Compare pairs: “Could you pass the book?” / “Give us a hand with that book”; “Please wait a moment” / “Hang on a wee minute”; “That was enjoyable” / “That was good fun”.','For each pair invent two contexts where it might fit, noting relationship, tone and shared meaning. No expression always belongs to just one setting.','Explain that wee can mean small or, in “a wee minute”, a short time; “give us a hand” is an everyday expression for help, not necessarily several people asking. Confirm any unfamiliar expression with a knowledgeable speaker.','Write a short dialogue with a chosen expression, then a version for a reader unfamiliar with it. Optional home expressions are welcomed, never required.'], '“Hang on a wee minute” may sound natural between familiar speakers. “Please wait a moment” may help an unfamiliar visitor. Either can be polite or impatient depending on tone and context.', ['Three contextual comparisons','One expression explained in its context','Dialogue and an accessible alternative, without ranking varieties'], 'explain a familiar expression in context','justify context-sensitive choices while respecting language varieties',{tool:'writing'}),
ER1:project('A guided visit to the Blue Box','Experience modelled, shared, guided and independent reading with explicit prompts.',['The supplied story; an adult or more experienced reader for observed supported reading'],['Before reading: inspect the title. Predict what kind of box might matter and record one question. Preview noticeboard (a board displaying notices) and recipe (instructions for making food).','Model: adult reads the opening paragraph, pauses after the second journey and thinks aloud: “The repeated journeys explain why Niamh did not notice the box at first.” Child follows the words using their access supports.','Shared: take the next three paragraphs together. Ask “What does worth keeping suggest?” Reread the card; allow a tentative idea without telling the later answer.','Guided: child reads the photograph paragraph at a comfortable pace. Ask what is literally shown, then why a person might value it. Prompt a return to the writing on the back before offering an answer.','Independent: finish the story if this is an appropriate accessible text. Explain how Niamh’s idea changes and identify two supporting details. Discuss one word-reading difficulty and the check used. Record the type of help, not a reading age.'], 'Literal: the photograph shows an empty bench. Inference: it matters because of a remembered relationship, supported by the note about Granny and whistling. A reader may need decoding help while still offering a strong interpretation.', ['Prediction and final response','A prompted and an independent response with text evidence','Adult record identifying which reading modes were actually observed'], 'locate and explain a detail during supported reading','independently connect later information to an interpretation using evidence',{tool:'reading',text:text('blue-box')}),
ER2:project('Explore the eight-text shelf','Read and use a wider range of original complete short texts.',['Built-in library; optional read-aloud for access'],['Browse all eight supplied texts: mystery, explanatory information, diary, fable, narrative poem, play, report and persuasive letter. They are original app texts, not excerpts from named authors.','Choose one literary and one information/persuasive text. Read in manageable portions and save a brief gist for each.','Compare organisation, language and purpose with two exact examples. Then choose a different genre and explain how your reading approach changes.','Use the library again on later visits; these eight texts broaden access but do not represent the whole range of reading expected across KS2.'], 'The play labels speakers and uses stage directions so readers can follow interaction. The report leads with an event and separates reported observations from the organiser’s hopes.', ['Three genre-labelled reading entries','Accurate gist statements','Feature comparisons supported by examples'], 'identify the purpose and main ideas of different genres','use specific features to compare them and choose a suitable reading approach',{tool:'reading',text:readingLibrary.map(t=>`${t.title.toUpperCase()} — ${t.genre}\n${t.text}`).join('\n\n────────\n\n')}),
ER3:project('A reading habit over several visits','Build sustained independent reading without speed or streak targets.',['Built-in eight-text library; optional further suitable books chosen with an adult'],['Choose a complete library text that you can access without constant conceptual help. Set a natural stopping point such as a paragraph or scene, not a speed target.','Read silently and independently where appropriate. Save where you stopped, one idea you followed and what you want to read next. If read-aloud was used, label listening or supported reading accurately.','On another visit resume, reread the last part if helpful and continue. Repeat with different genres across several occasions.','Look back with an adult at enjoyment, understanding and useful support. More pages or minutes alone do not establish reading attainment. Observation remains pending until reading actually occurs.'], 'Entry: “Stopped after the photograph note in Blue Box. I realised the picture matters because of a memory. Next I want to learn what the button means.”', ['Dated reading/resume entries','A response showing understanding at each chosen stopping point','An accurate independent/supported/listened access note'], 'follow and describe meaning during a comfortable reading period','resume independently and reflect on a useful next reading step',{tool:'table',text:text('blue-box'),starterRows:[['Date / text','Stopping point','Meaning / interest noticed','Next step / access method'],['','','','']]}),
ER4:project('Recommend without saying “everyone”','Develop and explain preferences across available genres.',['Built-in library; partner optional'],['Read the diary, fable and report supplied here on separate visits. Note a moment or feature you responded to in each.','Rank them for your own current purpose, or explain why ranking is unhelpful. A preference is not a test with one right answer.','Write two recommendation cards: one for a reader who likes characters changing their minds, another for a reader interested in how designs are evaluated. Use specific evidence.','Read a different person’s recommendation when available. Decide whether it changes your next choice and explain why; without a partner, compare your two cards.'], '“Try the diary if you like a character solving a personal difficulty. The reminder drawings help the writer start again.” This is more informative than “Everybody will love it”.', ['Three text-linked preferences','Two audience-specific recommendations','A reasoned next reading choice'], 'give a specific reason for a reading preference','recommend a text for another reader’s purpose and consider a different preference',{tool:'writing',text:text('practice-diary')+'\n\n'+text('fable-bell')+'\n\n'+text('report-display')}),
ER5:project('Two notices, one careful answer','Compare a supplied source set for relevance, date and limits.',['Two fictional sources below; no live website or account needed'],['Question: Can a family bring a dog to the imaginary garden exhibition on 12 June? Read both source cards.','Record who produced each, its date, the relevant wording and any conflict. Do not assume an attractive layout establishes reliability.','Write a cautious answer for a parent, naming the source and the remaining question. Separate general policy from the special event rule.','Discuss what an adult should check with the organiser before a real visit. Do not contact anyone: this is a fictional source exercise.'], 'The newer event notice excludes pet dogs on 12 June, while explicitly welcoming assistance dogs. The older general leaflet allows dogs on leads. For this event use the specific newer notice, and ask the organiser if any access arrangements remain unclear.', ['Source comparison table','Attributed answer with relevant conditions','A remaining check rather than invented certainty'], 'select information relevant to the question from each source','resolve or report a conflict using scope and date while retaining uncertainty',{tool:'table',text:'SOURCE A — Imaginary Garden Friends general leaflet, printed 3 March: “The garden welcomes visitors daily. Dogs on leads may accompany visitors. Owners should keep paths clear and take litter home.”\n\nSOURCE B — Imaginary exhibition organiser’s event notice, issued 8 June: “Model exhibition, 12 June, 2–4 pm. Space will be limited during this event. Please leave pet dogs at home for this session. Assistance dogs are welcome. Contact the organiser through your school office for access questions.”\n\nBoth sources are invented for this activity; no real event or contact is implied.',starterRows:[['Source / producer','Date and scope','Relevant information','Limit / question'],['A','','',''],['B','','','']]}),
ER6:project('One story, three representations','Represent understanding through visual, verbal, dramatic and digital choices.',['Supplied fable; paper optional; workspace graphic tools if available'],['Read the fable. Make a three-frame storyboard: original plan, discovered barriers, revised plan. Use drawings, symbols or clearly labelled descriptions.','Prepare a spoken/AAC or typed explanation of the turning point, using one detail from the text.','Create a still pose, symbol arrangement or short role exchange showing why the mole could not use the first bell. Label the inference and its evidence.','Save a digital summary and explain what each representation makes easier to understand. If paper or physical performance was used, record an adult observation; do not claim an unsaved image is stored.'], 'A low loop beside the mole can show improved access visually. The summary explains that the animals changed more than the rope: messages and varied times also helped.', ['Storyboard or accessible equivalent','Text-supported explanation','Digital summary and reflection on format choices'], 'represent the important events accurately','justify an interpretation and explain why different formats help different aspects of meaning',{tool:'writing',text:text('fable-bell')}),
ER7:project('Look beyond the name of a device','Explain and compare how language shapes a reader’s response.',['Supplied poem and two rewritten extracts'],['Read the platform poem. Choose “a page without print”, “listening tree” and “a question too large for a bag”. Explain the picture or idea each suggests, not only the technique name.','Compare “The platform lies quiet, a page without print” with “No passengers have arrived yet”. What is gained or lost in the rewrite?','Track how the poem moves from stillness to activity and back. Use evidence from at least three stanzas.','Write a paragraph explaining an effect and a plausible alternative interpretation. Revise if you have made a claim without supporting words.'], '“A page without print” suggests a space waiting for the day’s events. “No passengers…” gives similar information more directly but loses the image of events becoming a written story.', ['Three language-effect explanations','A comparison of two versions','A supported account of change across the whole poem'], 'link a specific language choice to a plausible effect','develop an interpretation across several parts of the text while considering alternatives',{tool:'writing',text:text('poem-platform')}),
ER8:project('One exhibition in three media forms','Compare a report, poster and spoken announcement about the same event.',['Supplied media set; optional device voice for announcement'],['Read the news report. Then inspect the poster text and listen to or read the announcement. Identify which information is shared and which is selected or omitted.','Create a comparison table for purpose, audience, timing, emphasis and evidence. A poster can persuade without making false claims.','Identify the report’s caution about visit counts. Decide why the poster need not include every report detail, but must still give accurate essential information.','Write a fair two-sentence caption for the set and one question a visitor might still need answered.'], 'The poster invites attendance before an event; the report records what happened afterwards; the announcement gives immediate directions. “Brilliant for everyone” would be an unsupported guarantee in any form.', ['Comparison across three forms','One omission explained by purpose','A fair caption and a remaining information need'], 'identify factual and presentational differences','explain how audience, purpose and timing influence the choices',{tool:'table',text:text('report-display')+'\n\nFICTIONAL POSTER\nMODEL GARDEN EXHIBITION\nFriday, 2–4 pm · school hall\nExplore four designs. Leave a thoughtful comment.\nAsk the school office about access arrangements.\n\nANNOUNCEMENT\nThe model exhibition is now open in the hall. Please keep the entrance clear. You may leave an anonymous comment beside each model. There is no vote today.',audio:'The model exhibition is now open in the hall. Please keep the entrance clear. You may leave an anonymous comment beside each model. There is no vote today.',starterRows:[['Form','Purpose / audience','Selected information','Effect / missing information'],['Report','','',''],['Poster','','',''],['Announcement','','','']]}),
ER9:project('An inference needs a reason','Write and reconsider evidence-based interpretations.',['Supplied story and diary; optional read-aloud recorded as access support'],['Read the blue-box story. Claim 1: Niamh’s understanding of treasure changes. Select two supporting details and explain how each supports it.','Claim 2: Dara’s stone matters for its monetary value. Decide whether this is supported, contradicted or not established. Explain using the card he writes.','Read the diary. Infer why the writer changes the reminder card, using evidence rather than simply naming a feeling.','For one inference, give another possible interpretation and explain which the text supports more strongly. Save claim → evidence → explanation separately.'], 'Dara’s note connects the stone to his brother crossing the bridge. That supports personal meaning; it does not tell us a price. A quotation without an explanation is not yet a complete justification.', ['Three claim/evidence/explanation entries','One alternative interpretation','A revision after checking the source'], 'select evidence relevant to an inference','explain its connection and weigh an alternative without claiming certainty beyond the text',{tool:'writing',text:text('blue-box')+'\n\n'+text('practice-diary')}),
ER10:project('Keep your first idea, then reconsider','Record a personal interpretation before and after new evidence.',['Progressively revealed text; saved notes or draft snapshots'],['Read only the first revealed section. Save what you think is happening, a supporting clue and at least one uncertainty before moving on.','Reveal the next section. Preserve the earlier entry; write what you keep or change and why. A sensible unchanged view is allowed when supported.','Reveal the final section. Compare all three interpretations, pointing to the new evidence that mattered.','Do not replace the first entry with your final answer. The purpose is to see your thinking change, not to guess the ending immediately.'], 'Response structure: “At first I thought ___ because ___. After the new detail ___, I now think ___. One thing the text still does not tell me is ___.” More than one early prediction may be plausible.', ['Saved initial interpretation before reveal','Intermediate revision with new clue','Final comparison of original and later evidence'], 'state a plausible interpretation supported by the revealed text','reconsider it explicitly in response to new information while preserving earlier reasoning',{tool:'reading',stages:['At the community hall, Leo heard a loud growl behind a closed curtain. A bowl stood on the floor nearby. He stopped and whispered, “Should we fetch somebody?” What might be behind the curtain?','Then the growl came again, exactly the same length and pitch. A small red light blinked beneath the curtain. Leo noticed that the bowl contained spare cables rather than food. What does this change?','The caretaker drew back the curtain. A speaker was playing sound effects for a play. The animal costume lay folded on a chair. “We are checking the loudspeaker,” she explained. Which early clues were useful, and which had more than one possible meaning?']}),
ER11:project('Read prepared words for a listener','Prepare source and self-authored text, then use feedback to refine meaning.',['A willing listener for observed reading; accessible communication arrangements'],['Choose a short paragraph from the diary and copy it into your preparation notes. Mark pauses and emphasis, explaining two choices.','Rehearse at a comfortable pace. Read it to a familiar listener when possible and ask what meaning or feeling came across.','Write your own short paragraph about starting something again, real or imaginary. Prepare and share that too.','Keep both marked texts and exact feedback. Revise one reading choice; record separately if you annotated meaning without performing a read-aloud.'], 'A pause before “Could I start that part again?” can make the request stand out. A different choice can work if it conveys the intended meaning; accent and speed are not the rubric.', ['Prepared source paragraph','Prepared own composition','Observed feedback and changed annotation or pending marker'], 'prepare delivery choices that suit the text’s meaning','refine those choices using listener feedback on both source and own writing',{tool:'writing',text:text('practice-diary')}),
ER12:project('Try, cross-check, confirm','Practise a systematic unfamiliar-word routine with supplied text and mini glossary.',['Supplied sentences and glossary; adult pronunciation model or device voice if helpful'],['For each target word, first inspect its letters and meaningful parts. Attempt a reading using known sound patterns; ask for a model when needed. Do not substitute a different word that merely fits the context.','Reread the whole sentence and propose a meaning. Then check the glossary and, where needed, pronunciation with a suitable model. Record whether the check confirmed or changed your attempt.','Set A: unnoticed, reusable, disagreement. Set B on a later visit: cautiously, miniature, reliable. Use each in a new sentence that shows its meaning.','Revisit two words in a new context without looking at the glossary first. Note actual support separately from word-meaning understanding.'], 'Unnoticed: un + noticed helps suggest “not noticed”. In “The small note remained unnoticed”, that fits. I still check all the written letters rather than read unseen, which would be a different word.', ['Attempt / parts / context / confirmed meaning for six words','Any corrected pronunciation or meaning','Later fresh sentences and support record'], 'combine a written-word strategy with a context check','confirm or correct the result using a reliable model and transfer it to a fresh context',{tool:'table',text:'SENTENCES\n1. The small note remained unnoticed.\n2. We kept the reusable box for another model.\n3. Their disagreement concerned the best place for a bench.\n4. She moved cautiously across the slippery stones.\n5. A miniature boat fitted in his palm.\n6. A reliable record could be checked against the original count.\n\nMINI GLOSSARY\nUnnoticed: not noticed. Reusable: able to be used again. Disagreement: a difference of opinion. Cautiously: carefully to avoid risk or mistakes. Miniature: much smaller than the usual full-size version. Reliable: able to be trusted for the purpose; in this context supported by accurate, checkable recording.',starterRows:[['Word','Letters / parts and first meaning','Check / correction','New sentence / support'],['unnoticed','','',''],['reusable','','',''],['disagreement','','',''],['cautiously','','',''],['miniature','','',''],['reliable','','','']]}),
ER13:project('Skim an article, scan a timetable, read closely','Perform different reading strategies using supplied resources.',['Article and fictional timetable below'],['Skim the article title and section headings. Save a one-sentence overview before reading every paragraph.','Scan the timetable for a bus leaving Market Square no earlier than 09:15 and arriving at the Museum by 10:00. Identify the service, then check both relevant cells closely.','Read the article’s final paragraph closely. Explain why counting borrowed books alone would not answer whether a display helped readers.','Compare what each strategy supplied. Record a detail you needed to reread rather than claiming faster reading is always better.'], 'Service B leaves Market Square at 09:20 and reaches the Museum at 09:50, meeting both conditions. Service A leaves too early; C arrives too late. Scanning locates candidates; close reading checks the conditions.', ['Initial overview','Selected service with both supporting times','Explanation based on the article, plus strategy reflection'], 'locate relevant information using an appropriate strategy','check the detail against all conditions and explain when close reading was needed',{tool:'table',text:'ARTICLE: Testing a Book Display\n\nPurpose\nA display can help readers notice unfamiliar books. To find out whether it helps, first decide what you want to learn: whether people notice it, use it or discover something they enjoy.\n\nA small trial\nChoose several kinds of text. Keep the display reachable and the route past it clear. Ask readers what they noticed and whether a recommendation helped them choose.\n\nLook beyond a total\nA count of borrowed books shows use, but it does not tell us whether readers enjoyed or understood them. Some may borrow and return unread books. Other readers may enjoy a short poem without borrowing anything. Combine a count with carefully asked questions.\n\nFICTIONAL TIMETABLE\nService | Market Square | Park Gate | Museum\nA | 09:00 | 09:10 | 09:30\nB | 09:20 | 09:30 | 09:50\nC | 09:40 | 09:50 | 10:10\nAll times are same-day morning departures/arrivals in this invented timetable.',starterRows:[['Question','Strategy first used','Answer and supporting detail','What needed checking'],['Main topic','','',''],['Suitable bus','','',''],['Meaning of borrowing count','','','']]}),
EW1:project('Watch a writer, write together, then try','Move through modelled, shared, guided and independent onscreen composition.',['Saved writing workspace; willing adult for actual shared/guided sessions'],['Model: read the supplied plan, draft and think-aloud. Notice how the writer makes choices rather than copying a perfect answer.','Shared writing: with a partner, change the setting to a quiet station and the found object to a glove. Jointly choose an opening and explain two decisions. Save it as Shared version. If no partner is available, prepare ideas and mark observation pending.','Guided writing: plan a different character finding an ordinary object. Adult prompts: What matters to the character? Which detail helps the reader picture the place? How will the next event connect? The adult should not dictate the sentences.','Independent writing: compose a new opening for a friend using your own choices. Save it separately from the models. Reread, revise one part and record which support was used.'], 'Plan: Mina + workshop + a key that seems unimportant. Draft: “Mina found a key. She was in the workshop.” Think-aloud: I can join the ideas and add a precise location. Revised: “Under the workshop bench, Mina found a tiny key tied to fraying thread.” This is one possible opening, not a required template.', ['Separate shared, guided and independent versions','Two explained composition choices','Adult record of support and actual participation'], 'compose an opening with a clear character and setting','explain and revise choices for a reader in a separate independent draft',{tool:'writing',text:'Writer’s planning frame: Who? Where? What changes? What should the reader wonder?\nGuided prompts: point to a detail that establishes place; identify an unclear reference; read two possible verbs and choose the meaning you want.\nIndependent mission: an ordinary object is found in an unexpected place. Write for a friend who has not heard your plan.'}),
EW2:project('A poster, a procedure and a report','Use actual source material to organise different written forms.',['Writing workspace with headings/line breaks; paper or layout tools optional'],['Procedure source: “Take a strip of card and a pencil. Write a title near the top. Draw a small picture below it. Put the card between two pages to mark your place.” Transform this into a materials list and numbered steps without losing information.','Poster facts, all imaginary: bookmark workshop; school hall; 6 June, 2 pm; bring a pencil; card supplied. Arrange a heading and labelled essential details so they are easy to find.','Report facts: afterwards, twelve participants made bookmarks and displayed them. Write a short heading and paragraph in past tense. Do not turn the invitation into a claim about success.','Compare layouts. Ask someone to find where/when on the poster and follow a step in the procedure; record any change made.'], 'Materials: card strip, pencil. Steps: 1 Write a title near the top. 2 Draw beneath it. 3 Place between pages. The materials list separates preparation from action; numbers preserve sequence.', ['Three differently organised pieces','Source information retained accurately','A layout change explained through reader use'], 'organise accurate information for a specific form','explain and refine layout choices for the reader’s purpose',{tool:'writing'}),
EW3:project('A poetry notebook to revisit','Experiment, read back and revise sound, image and wordplay across several occasions.',['Supplied poem; accessible sound/rhythm response; no compulsory beat tapping'],['Visit 1: read the platform poem and identify a true sound rhyme such as gate/late. Write two original lines with a different rhyme pair. If sound access is limited, record which poetic goal an alternative demonstrates.','Visit 2: write four lines using a repeated opening or phrase and one comparison. Read or hear them back and alter a line whose rhythm or meaning does not serve your intention.','Visit 3: create a small pun or use an optional familiar dialect expression. Explain both meanings or the expression’s context for a reader.','Return to one earlier draft. Save a new version and explain what changed for sound, sense or audience. Poems need not all rhyme or share one rhythm.'], 'Wordplay model: “The clock had plenty of hands, but could not carry the bags.” Hands has two meanings. Revision should keep the double meaning understandable rather than merely make the poem longer.', ['Three dated experiments','Original and revised poem versions','Explanation of a sound, image or wordplay effect'], 'make an intentional poetic choice','explain its effect and revise it meaningfully after rereading',{tool:'writing',text:text('poem-platform')}),
EW4:project('One subject, three audiences','Develop genre and audience choices through an explicit writing sequence.',['Book-basket letter and supplied factual set; saved writing versions'],['Study the letter: mark viewpoint, supporting reason, concern, response and requested action. Identify how its form addresses a school council.','Use these fictional facts: a book-trying display uses existing books; it offers four genres; trial lasts a fortnight; comments are anonymous. Plan a factual notice for parents, helpful instructions for a younger child and a persuasive paragraph for the council.','Draft the three pieces separately. For each, explain one vocabulary, organisation or tone choice tied to its audience.','Invite feedback where possible, revise each piece and keep the earlier versions. Compare how the same honest facts can support different purposes without inventing outcomes.'], 'Younger-reader instruction: “Choose a book. Read a little. Return it to the labelled place when you finish.” Council argument: “A short trial could help us learn which recommendations are useful before buying anything.”', ['Three audience/purpose plans','Three draft and revised pieces','Text-based explanations of genre choices'], 'select relevant content and a recognisable form for the reader','revise organisation or style in response to the specific audience and purpose',{tool:'writing',text:text('letter-books')}),
EW5:project('Keep the draft, show the change','Plan, revise and redraft with a retained before-and-after record.',['Workspace draft snapshots; no external document needed'],['Plan a short scene: character, place, small problem, reader’s intended feeling. Save the plan and first draft as separate versions.','Use the model to distinguish revision of meaning from proofreading. Mark one unclear event and one wording choice in your own first draft.','Create a new version rather than erase the only copy. Change sequence or detail for meaning, then proofread sentence boundaries and relevant spellings.','Compare versions. Quote an old and new phrase, explain the effect and record any reader feedback. Further drafts can be added later; number them clearly.'], 'Before: “Eli went there. It was bad. He got it.” After: “Eli hurried back to the shed. Rain was dripping onto the paper map, so he lifted it onto a dry shelf.” The revision clarifies place, problem and response; proofreading alone would not solve the vague references.', ['Saved plan, first draft and redraft','At least one substantive change and one proofreading check','Explanation supported by an actual before/after excerpt'], 'identify a revision that would clarify meaning','make and justify that revision while retaining evidence of the original',{tool:'writing'}),
EW6:project('Facts, feelings and a viewpoint','Build a small collection across imaginative and factual writing.',['Diary and report below; invented survey facts supplied'],['Read how the diary expresses a personal experience and the report distinguishes facts from claims. Identify one example of each.','Write an imaginary diary entry about preparing for a display. Include a feeling and an event that explains it; label the account as fiction.','Write a factual report using this pretend dataset: six choose stories, four information books and two poetry; twelve responses total. State what was counted and avoid claiming everyone agrees.','Write an opinion paragraph about which text to recommend first, acknowledging at least one different preference. Keep all three pieces and revise one after comparison.'], 'Factual: “Six of twelve respondents chose stories.” Opinion: “I would begin with a story because this group’s most common preference was stories, while offering other choices too.” Neither proves stories are best for everyone.', ['Imagined experience, factual report and viewpoint','Facts distinguished from feelings or judgements','One revised piece with an explained improvement'], 'express relevant ideas in both imaginative and factual forms','support a viewpoint and keep evidence-based claims distinct from invention',{tool:'writing',text:text('practice-diary')+'\n\n'+text('report-display')}),
EW7:project('Two moods, one setting','Use selected details and sentence choices to create effects.',['Supplied paired models; writing workspace'],['Compare Model A and Model B below. Identify which details change while the physical setting remains a doorway and room.','Choose a different ordinary place. Plan one welcoming and one uneasy description; use sound, light or movement rather than simply naming the mood.','Draft both, varying sentence choices only where they serve the effect. Explain two deliberate decisions with quotations from your own work.','Ask a reader which mood came across, or compare against your written intention. Revise an ineffective choice and retain the first version.'], 'A: “Warm light spread through the open doorway. Inside, someone laughed and set another cup on the table.” B: “A narrow light slipped under the closed door. Something scraped. Then nothing.” Warmth/open space/social detail differ from uncertainty, restricted view and a short interruption.', ['Two contrasting drafts of the same place','Two choice/effect explanations','Specific feedback or self-comparison and a revised version'], 'select details that support an intended mood','explain their effects and revise a choice in response to a reader’s interpretation',{tool:'writing',text:'Model A and Model B describe invented scenes. A short sentence is not automatically suspenseful; its relationship to surrounding information creates the possible effect.'}),
EW8:project('A portfolio of deliberate choices','Explore personal style through several pieces over time.',['Saved writing workspace; earlier drafts or supplied starter options'],['Create or select three pieces on different visits: a scene, a poem and an opinion piece. Starter themes are an unexpected message, a place waking up and a useful change to a reading space.','For each, label audience, purpose and two deliberate choices. A recurring preference is a possibility to explore, not a permanent label for the writer.','Ask a reader about one effect, or use the intended-effect questions: What will a reader notice? Where might they be confused? What evidence shows my choice worked?','Save revised versions and a portfolio reflection: one choice used differently across forms, one habit to keep and one new experiment. Actual sustained development remains pending until these dated pieces are produced.'], 'A writer might use repeated openings in a poem but a single clear opening claim in a letter. Personal style includes adapting choices, not repeating the same device everywhere.', ['Three dated pieces with purposes','Six choice explanations and at least one revision','Portfolio reflection supported by excerpts'], 'identify intentional choices in more than one composition','evaluate and adapt those choices across purposes using accumulated work',{tool:'writing'}),
EW9:project('Words and graphics that belong together','Create and refine a combined digital information piece.',['The saved picture and caption tools below'],['Use the factual set below to plan a digital information card for a younger reader. Decide what belongs in text and what a diagram can show more clearly.','Create a heading, short caption and a simple original graphic using the picture and caption tools below. Label your shapes; do not rely on colour alone. A written plan for a picture is preparation, not completed graphic composition.','Add a text description of the graphic so its meaning is available without sight. Optional device speech may read your words; no recording of other people is needed.','Review the whole piece with a reader if possible. Revise text/graphic arrangement and explain what each medium contributes. Keep the labelled picture and accompanying writing together in this project.'], 'Card: “Return a borrowed book”. Graphic: book → labelled return shelf. Caption: “Put the book on its labelled shelf so the next reader can find it.” Text description: an arrow leads from a book to a shelf labelled Returns. The arrow shows action; the words explain purpose.', ['Saved writing and a created labelled picture','Text description and explanation of each medium','A revision to the writing or picture, with a reason'], 'combine accurate words and a relevant graphic','explain and refine their relationship for audience understanding',{tool:'writing',text:'FACT SET FOR THIS INVENTED LIBRARY: borrowed books return to a shelf labelled Returns; damaged books should be shown to the adult in charge; personal belongings should stay out of the walkway. Do not add rules about a real library.'}),
EW10:project('What the page needs to explain','Compare spoken context with written clarity.',['Three supplied mini conversations; writing workspace'],['Conversation 1, with a gesture: “Put that beside this.” Objects: a blue folder and a returns box. Write an instruction for a reader who cannot see the gesture.','Conversation 2: “Then do it again.” Earlier action: move a counter two spaces and collect one token. Make the repetition explicit in writing.','Conversation 3: “It was there when I went.” Missing context: a model was on the hall table when the speaker arrived at noon. Write a clear report sentence without adding invented certainty about who put it there.','Explain which information speech gained from shared context and which written version had to supply. Both speech and writing can be precise; the situation matters.'], '“Place the blue folder beside the returns box” names both objects. “The model was on the hall table when I arrived at noon” identifies event, place and time, but does not invent its owner.', ['Three original/rewritten pairs','Explanation of the missing context','A check that no unsupported information was added'], 'replace ambiguous references with relevant information','explain context-dependent differences without treating speech as an inferior form',{tool:'writing'}),
EW11:project('A spelling workshop with transfer','Apply varied spelling strategies in editing and independent writing.',['Supplied word sets and short error text; optional suitable dictionary'],['Model patterns: jumped keeps jump; carried changes consonant+y to i before -ed; played keeps y after a vowel; unhappy adds un- to happy; reread adds re- to read. Explain the meaning as well as the letters.','Edit this invented draft: “We hurryed to the hall and plaid a game. The unhapppy visitor rereed the note.” Correct the four target spellings and record a reason or checking strategy for each.','New application: write meaningful sentences using copied, enjoyed, helpful and rebuild. Identify a useful base/ending or prefix. Do not assume one suffix rule works for every word.','On a later visit, without looking at your corrected draft first, use hurried, played, unhappy and reread in a different short account. Check and record remaining uncertainties; repeated copying alone is not secure retrieval.'], 'Corrections: hurried (consonant+y becomes i before -ed); played (vowel+y stays); unhappy (un + happy, two p letters); reread (re + read). Reread can be present or past, so pronunciation depends on context even though the spelling stays the same.', ['Four corrections with strategy explanations','Four fresh application sentences','Later retrieval attempt and checked corrections'], 'apply a relevant spelling strategy and verify a correction','transfer it to new words or a later independent context while noticing exceptions',{tool:'writing',text:'CHECK WORDS: jumped, carried, played, unhappy, reread, copied, enjoyed, helpful, rebuild. In the error draft, “plaid a game” is wrong in context even though plaid is a real word for a fabric pattern. Meaning as well as letter matching matters.'}),
EW12:project('Grammar that changes meaning','Edit, explain and compose across sentence and punctuation choices.',['Supplied editing set; saved writing workspace'],['Edit A: “the visitors arrived they carried models” into two clearly bounded sentences. Edit B: one pupil owns a model; write “the pupils model” with the intended possessive. Then write the phrase for several pupils jointly owning a model.','Edit C: “The door was narrow. We moved the display.” Join with a suitable cause/result conjunction and explain the relation. Edit D: “The children was ready” for standard written subject–verb agreement; discuss that studying this written convention does not rank a home dialect.','Compose a short account using clear sentence boundaries, a justified possessive and two different sentence links. Include one question or direct-speech sentence if appropriate, checking its punctuation with an adult or reference.','Save a first and edited version. Explain three changes in meaning or clarity, rather than only naming punctuation marks.'], 'A: “The visitors arrived. They carried models.” B: “the pupil’s model”; shared plural: “the pupils’ model”. C: “The door was narrow, so we moved the display.” D: “The children were ready.” More than one clear sentence arrangement is possible.', ['Corrected sentences with explanations','Original composition applying the choices','Before/after draft and three clarity explanations'], 'edit the supplied written conventions accurately','apply them in new composition and explain how choices clarify meaning',{tool:'writing',text:'Meaning comparison: “Let us help, Sam” invites Sam to help. “Let us help Sam” suggests helping Sam. A comma can change who is being addressed. Use a new example to show an equally clear meaning distinction, without assuming every pause requires a comma.'}),
EW13:project('Comfortable handwriting you can use','Observe legibility and useful fluency across several short samples.',['Paper and a comfortable adapted writing tool; qualified adult support for persistent difficulty; optional scribe for reflections'],['Sample 1: write “The small boat reached the harbour.” Ask a familiar reader what they can read without guessing. Notice formation, spacing and size without imposing a single grip. Save an observation in the app; the handwritten sheet remains on paper unless a separate import feature is available.','Sample 2 on another occasion: write two original sentences for a friend. Choose one manageable improvement from the first sample, such as clearer word spaces. Stop or adapt if uncomfortable.','Sample 3: take short notes from the supplied familiar message, hearing or reading it again as needed. Check later whether the notes can be read and used. Avoid making memory or speed the hidden goal.','Compare dated observations and comfort, not just speed. An adult should record actual handwriting evidence; typed responses demonstrate composition/access, not handwriting itself.'], 'Message for notes: “For the model, bring card, string and a pencil.” Useful notes: “Model: card, string, pencil.” If word gaps were unclear, a successful change is readable spacing without extra discomfort, not a race to finish faster.', ['Three dated paper samples with app observation notes','One chosen improvement and evidence of its effect','Comfort/access record and actual adult observation, or pending status'], 'produce a short message that a reader can use','make and evaluate a focused legibility or fluency improvement across occasions',{tool:'table',starterRows:[['Date / sample','What could be read','Chosen change / result','Comfort and adult observation'],['1','','',''],['2','','',''],['3','','','']]})
};

export const englishProjectStatus='All 41 English matrix actions now have an authored project resource. This is implementation coverage, not proof of curriculum sufficiency, completed pupil work, sustained practice or qualified teacher approval. Human review and actual observations remain pending.';
