import type { Task } from './content.ts';

export type EnglishLearningStep = {focus:string;example:{prompt:string;reasoning:string;answer:string};rubric:{support:string;developing:string;secure:string}};
export type EnglishLearningTrail = {skill:string;prerequisites:string[];steps:[EnglishLearningStep,EnglishLearningStep,EnglishLearningStep]};
export const englishAuthoringStatus = 'AI-authored teaching supplement: qualified NI KS2 teacher review and pupil validation pending. Levels are practice steps, not calibrated attainment levels.';
export const englishAccessGuidance = 'Judge the learning goal, not accent, speech fluency, handwriting, speed or use of accessibility tools. Accept pointing, AAC, typing, dictation or a scribe where these preserve the goal. If reading aloud, spelling or handwriting is the goal, record which part the child demonstrated and which part was supported. A missing partner, resource or suitable access method means not yet observed, not needs support. These rubrics describe this task only; seek fresh evidence before changing a recommendation.';
const step=(focus:string,prompt:string,reasoning:string,answer:string,first:string,next:string):EnglishLearningStep=>({focus,example:{prompt,reasoning,answer},rubric:{support:`After an accessible explanation and a model, needs a learning prompt to ${first}. Offer a smaller shared example, then try again.`,developing:`Can ${first}, but needs a learning prompt to ${next}. Record the prompt and practise that part.`,secure:`Can ${first} and ${next} on a fresh example, with usual accessibility supports and without a prompt that supplies the idea. This is evidence for this task, not whole-topic mastery.`}});
const trail=(skill:string,prerequisites:string[],steps:EnglishLearningTrail['steps']):EnglishLearningTrail=>({skill,prerequisites,steps});

export const englishLearning:Record<string,EnglishLearningTrail>={
 detective:trail('Find evidence and distinguish information from inference',['Locate a detail in a short text','Explain a choice using a phrase or pointing'],[
 step('Retrieve an explicit detail','“Nia placed a green pebble in a tin. Her yellow scarf lay on the chair.” What went in the tin?','I match the question to placed…in a tin. Yellow describes the scarf, not the object in the tin.','A green pebble.','locate the detail asked for','identify the words that support the answer rather than another nearby detail'),
 step('Infer from a current clue','“The shed looked empty. Then a voice inside said, ‘Pass the brush.’” What suggests somebody is inside now?','Empty is an appearance. A voice asking for an object suggests someone is there, although I cannot see them.','The voice speaking inside is evidence of a person there now.','select a clue relevant to the inference','explain the clue and distinguish a likely inference from certain proof'),
 step('Reconsider after new information','First: “Someone was drumming on the roof.” Predict a cause. Then: “A woodpecker tapped the gutter.” What would you revise?','I might first imagine a person. The later sentence names a bird, so I replace my first idea with a better-supported one.','My first idea was a person. Now I think the woodpecker made the sound because the second sentence says it tapped the gutter.','state an initial interpretation and notice new evidence','explain whether that evidence changes or supports the initial interpretation')]),
 words:trail('Build sentences and notice spelling patterns',['Recognise a sentence as a complete message','Find a capital letter and end punctuation'],[
 step('Order a statement','Arrange: “slept.” “cat” “The”','The starts the sentence; cat names who; slept tells what happened and ends the statement.','The cat slept.','arrange a complete statement','explain the role of the capital and full stop in that statement'),
 step('Build a question','Arrange: “kite?” “my” “Where” “is”','Where asks for a place. Is follows it; my kite identifies what I am asking about.','Where is my kite?','arrange a question that makes sense','explain what information it requests and why a question mark fits'),
 step('Inspect a plural spelling','Complete: “The two ___ opened their notebooks.” writer / writers / writters','Writer is the base word. Adding s makes more than one; there is no extra t.','writers','identify the correctly spelled plural','explain the base word and ending and apply the strategy to another word')]),
 story:trail('Plan, compose and revise an imaginative text',['Share an idea in words, symbols or pictures','Identify a character and an event'],[
 step('Model, share, then draft an opening','Model an opening about a lost button. Together choose a different character and place; then draft your own opening.','My plan is Jo + attic + a button that glows. I include character and place before the surprise; then replace saw with spotted for precision.','In the quiet attic, Jo spotted a silver button glowing beneath a box. Your shared and independent openings can be different.','introduce a character and setting','reread and explain a word change that makes the opening clearer'),
 step('Plan a problem and response','Model a three-part story plan about a missing picnic. Together invent another solution; then draft a different adventure.','I connect the solution to the problem rather than adding an unrelated event. My audience needs to follow why the character acts.','Plan: a crow takes the map; Asha follows its calls; she finds the map caught in a hedge and reaches the picnic.','order a character’s problem and response','write a connected resolution and revise a confusing link for the intended reader'),
 step('Revise for suspense','Improve: “Ben went into the hall. It was scary.” Share one sensory choice, then try another scene.','Naming scary tells the feeling. A sound and a pause let the reader experience uncertainty. A short final sentence changes the pace.','A floorboard creaked behind Ben. He held his breath and listened to the darkness. Nothing.','choose details that contribute to the intended mood','explain the effect of a sentence or detail and revise after reader feedback')]),
 talk:trail('Listen, communicate directions and consider another viewpoint',['A willing partner or alternative supported interaction','Take turns using a comfortable communication method'],[
 step('Retell the main sequence','Partner text: “A rabbit found a mitten, carried it to the gate and left it for its owner.” Retell; repeats are welcome.','I keep the important events in order, using my own words rather than memorising every word.','The rabbit found a mitten and took it to the gate for the owner. Who might collect it?','retell the main events in order','ask a relevant question and respond to the partner’s answer'),
 step('Make an instruction precise','Ask a partner to place a circle above a square. They ask, “Touching or apart?”','I notice what my instruction left unclear and add a distance or relationship. Clarifying is useful, not failure.','Put the circle above the square with a small gap between them.','give an ordered instruction with position words','respond to clarification and improve an instruction after comparing results'),
 step('Respond fairly to another view','One person wants a pond; another wants room for games. Model a fair response.','I first state the other person’s reason accurately, then add my reason and a possible agreement.','You want games space so everyone can move. I want wildlife to have water. Could a small safe wildlife area leave most of the space open?','give a relevant reason and summarise another view fairly','respond to that reason and suggest a justified compromise')]),
 'reading-library':trail('Explore different texts using evidence',['Read or access a short passage','Distinguish a question from an answer'],[
 step('Read a short story for cause','“Sam heard a bell. He left his sketch and opened the shop door.” Why did he stop sketching?','The bell comes immediately before his action and signals somebody at the door.','He heard the bell and went to the door.','locate the event that answers the question','explain the connection using a relevant detail rather than inventing a cause'),
 step('Explore personification','“The sleepy kettle grumbled on the stove.” Which words make the kettle seem alive?','Sleepy and grumbled usually describe living beings. They make its low sound seem like a tired complaint.','Sleepy and grumbled give the kettle living qualities.','identify the relevant language choice','explain an effect on the picture or feeling it creates'),
 step('Check a factual claim against text','“A rain gauge collects water in a container. Its markings help show how much rain has fallen.” Does it measure wind?','I choose what the passage actually states; the instrument collects rain, and no wind measurement is described.','The text supports measuring rainfall, not wind.','select a claim the information supports','identify the supporting detail and reject an unsupported claim')]),
 'reading-habits':trail('Choose, sustain and discuss reading',['An accessible text and optional partner','Comfortable reading or listening arrangements'],[
 step('Model and share reading','Partner model: “At the bend, / the path disappeared.” Read or listen together, then discuss the pause.','The pause groups words so the meaning is easier to follow. We can reread and check what disappeared.','The path disappeared at the bend. I paused after bend to make the place clear.','take part in shared reading and notice a text detail','explain that detail or ask a relevant question after rereading'),
 step('Choose a next reading step','After a page about a rescue boat, explain what makes you want to continue.','A reason linked to the text says more than “it is good”. There is no required number of minutes.','I want to find out how they reach the boat because the harbour rope has snapped.','describe something read during a comfortable independent stretch','give a text-linked preference and choose a manageable next step'),
 step('Compare reading preferences','Compare a garden poem and instructions for planting peas.','I can enjoy both for different reasons: one helps me imagine; one helps me act.','The poem helps me picture the garden sounds. I would choose the instructions when I want to grow peas.','compare specific features of two texts','justify a preference and respond to another reader’s recommendation')]),
 'source-detective':trail('Choose and evaluate relevant information',['Identify the question being investigated','Distinguish an observation from an opinion'],[
 step('Choose a relevant source','To check whether a pool opens tomorrow, choose between its current notice and a two-year-old holiday story.','The current notice directly concerns opening. I still check date and unusual closures.','Use the pool’s current opening notice and check it applies to tomorrow.','match a source to the question','explain why its relevance and date matter'),
 step('Separate a record from a judgement','A note says “We saw five worms on Tuesday.” A slogan says “The greatest soil ever!” Which records an observation?','The note records a count and day; it does not yet tell me how the observers searched. Greatest needs a criterion.','The five-worm note records an observation. I would ask how they counted before judging reliability.','distinguish a recorded observation from an opinion','state a limitation or further check rather than treating a number as automatic proof'),
 step('Compare sources with a shared question','Pretend sources: park notice dated June says the gate shuts at six; an old leaflet says five. What should we report?','Both address the gate, but dates conflict. A newer official notice is a better starting point; uncertainty should be checked rather than hidden.','The June park notice says six. An older leaflet differs, so an adult should confirm the current time with the park.','identify agreement or disagreement between two sources','give a relevant answer with attribution and a sensible unresolved check')]),
 media:trail('Notice how purpose changes presentation',['Separate a fact from a judgement','Identify who a message addresses'],[
 step('Recognise a neutral report','Compare “Four boats arrived at noon” with “Our fabulous boats amazed everyone”.','The first offers checkable detail without assuming everybody’s feelings.','Four boats arrived at noon is the more neutral report.','identify reported information without evaluative language','explain how a word in another version encourages a reaction'),
 step('Explain a headline’s effect','What does “Small seeds, enormous hopes” suggest?','The size contrast attracts attention and links a small action with ambitious aims; it is not a measured result.','It suggests that planting a small seed may lead to something people care about greatly.','identify a language feature that attracts attention','explain its possible effect without treating it as evidence of an outcome'),
 step('Compare a report and an invitation','Report: “Eight families visited the pond.” Poster: “Come and explore our pond!” Compare purposes.','One records an event; the other encourages action. Neither says whether every visitor enjoyed it.','The report gives attendance; the poster invites new visitors. A fair headline could be “Eight families visit pond”.','compare purpose and audience using features of each account','identify missing evidence and create a fair alternative message')]),
 'reading-response':trail('Show understanding in different forms',['Access a short text','Choose an accessible visual, verbal or symbolic response'],[
 step('Sequence a response','“A ball rolled away. Dev caught it. He returned it.” Plan three pictures or symbols.','I choose the main change in each sentence and preserve its order.','1 Ball rolling; 2 Dev catching; 3 ball returned.','represent the main events in order','explain how each part of the representation connects to the text'),
 step('Represent an inference','“Lena hid the broken cup when footsteps approached.” Plan a pose, symbol or spoken picture.','Hiding and approaching footsteps suggest worry about discovery; I should not say the text proves exactly what Lena feels.','A hunched pose or a worried-face symbol could show Lena fearing discovery, supported by hiding the cup.','represent a plausible character thought or feeling','point to supporting text and distinguish inference from stated information'),
 step('Summarise in two modes','Text: “Bees visit flowers for food. As they move, pollen can travel between flowers.” Pair a summary with a sketch plan.','I keep the main relationship, then use arrows to show movement that the sentence explains.','Summary: bees can carry pollen while visiting flowers for food. Sketch: two flowers, a bee and a movement arrow.','select the main ideas accurately','explain what each chosen format contributes to understanding')]),
 'word-strategies':trail('Cross-check word reading and meaning',['Access print or an appropriate adapted text','Identify familiar word parts'],[
 step('Use word parts and context','“Her boots were dusty after the dry walk.” Work out dusty.','Dust is a familiar part. The dry walk supports a coating of fine dry dirt; I check the written letters as well as the context.','Dusty means covered with dust here.','identify a useful word part or sound pattern','cross-check the suggested meaning against both the written word and context'),
 step('Use a prefix carefully','“The box was unopened.” Explain un-.','I recognise opened and test not opened in the sentence. Prefix meaning is a clue, not a reason to ignore the rest of the word.','Unopened means not opened.','identify the base and prefix','check the combined meaning in context and apply it to another suitable word'),
 step('Model a checking routine','An adult supplies “The creature was nocturnal.” How can we check nocturnal?','I try the syllables with help, reread, and check a dictionary’s meaning and pronunciation rather than guess night from a picture.','A dictionary confirms nocturnal means active at night. I reread using that meaning and check the pronunciation.','use more than one relevant word-reading or meaning strategy','explain how a reliable check confirmed or corrected the first attempt')]),
 'reading-purpose':trail('Match and perform a reading strategy',['Access a structured short text','Know the information being sought'],[
 step('Scan for a specific detail','Mini timetable: Route 4 — 09:10; Route 7 — 09:25; Route 9 — 09:40. Find Route 7.','I search for the route label, then read across its row rather than choose the first time.','Route 7 leaves at 09:25.','locate the requested item by its label','verify the associated information in the correct row or section'),
 step('Skim for a main topic','Title: “A home for hedgehogs”. Headings: Shelter; Food; Safe pathways. What is the likely topic?','I use the title and headings to form a broad overview; I do not claim details I have not read.','The text is likely about making places suitable for hedgehogs.','use title and headings for an overview','distinguish that overview from a specific detail requiring closer reading'),
 step('Switch strategies deliberately','Text titled “Our seed box”: “The box holds beans and peas. Bean packets are on the top shelf. Pea packets are below.” Find the topic, then locate peas.','First I skim the title for the topic. Then I scan for peas and read the sentence closely to confirm their position.','Topic: the seed box. Peas: below the top shelf.','choose a strategy that fits each question','explain what needed close checking after skimming or scanning')]),
 'listen-texts':trail('Respond to heard text and messages',['A partner or accessible audio/text equivalent','Comfortable way to request another hearing'],[
 step('Retell meaning rather than exact words','Partner reads: “A wheel squeaked. The cart stopped. Someone lifted a stone from the path.”','I listen for the changes and retell them in order. I can request a repeat.','The cart stopped after a squeak, and someone removed a stone.','retell the main information heard','separate a stated event from an inferred cause'),
 step('Listen to an image and voice choice','Partner reads: “Soft shoes shuffle / past the sleeping door.” Try a quiet, slow reading.','The sounds and pace can suggest care not to wake someone. A louder reading could change the effect.','I imagined somebody moving carefully because of soft shoes and the quiet reading.','describe an image linked to the words heard','explain how a vocal choice contributes to that interpretation'),
 step('Separate information and action','Announcement: “The art room opens at ten. Please leave wet coats on the hooks.”','The time tells me when; the request tells me what to do.','Information: opens at ten. Requested action: put wet coats on hooks.','summarise key information and requested action','identify the intended listener and clarify a missing detail if needed')]),
 'retell-drama':trail('Sequence, take perspectives and improvise',['Choose real or imagined content without private details','A partner or an alternative way to represent roles'],[
 step('Structure a journey','Model an imaginary walk to a hilltop.','I select a beginning, an interesting change and an ending, not every step.','First we left the bridge. A goat blocked the path. Finally it moved and we reached the hill.','tell a coherent beginning, event and ending','add relevant detail and answer a listener’s question'),
 step('Change viewpoint','A cyclist loses a bell; a walker finds it. Retell from the walker’s view.','The walker knows where it was found but may not know when the cyclist lost it.','I found a silver bell beside the bench. I wondered whose it was and called to the cyclist.','retell events from a chosen character’s viewpoint','keep that character’s knowledge consistent and respond to another role'),
 step('Combine fact and imagination','Improvise a seed speaking to a watering can.','A seed can need water, but speaking is imaginary. I can use fantasy to communicate a real idea without confusing them.','Seed: “Water can help me begin to grow.” The talking voice is imagined; the water need is factual.','improvise a relevant response within a role','explain which content is factual and which is invented')]),
 discussion:trail('Use reasons, listening and fair decisions',['Agree a comfortable turn-taking method','Different opinions are allowed'],[
 step('Build on another speaker','Partner: “Choose a seaside setting because of the storm.” Model a reply.','Repeating the reason shows I heard it before adding my own.','You chose the sea for the storm. I prefer a forest because a hidden path could make a mystery.','take turns and restate another person’s point accurately','give a relevant reason for a different or shared choice'),
 step('Disagree with an idea respectfully','Should books ever leave the reading corner? Give a reason and respond.','I address the proposal, not the person. A concrete example makes my reason clearer.','Books could leave it for partner reading at a table, but we need a return place so they do not get lost.','support a view with a reason or example','respond to a different reason respectfully rather than simply repeat a view'),
 step('Summarise a group decision','A group has £12: one map book costs £8; a poem booklet costs £4. Model a summary after discussing choices.','I name the decision and its reasons, including disagreement if it remains.','We chose both because the total is £12 and we wanted different kinds of reading. One person preferred saving the money.','invite and consider different proposals under the agreed rules','give a fair decision summary including reasons and unresolved disagreement')]),
 instructions:trail('Make instructions followable and resolve ambiguity',['Share a viewing direction or reference point','Ask when an instruction is unclear'],[
 step('Name the reference object','Improve: “Put the button above it.” A cup and a book are both on the table.','It could mean either object. Naming the book removes the ambiguity.','Put the button above the book, from where we are both looking.','name objects and positions clearly','check the listener’s understanding and repair an unclear reference'),
 step('Sequence a making task','Explain a paper name label using a rectangle of paper and a pencil.','Materials come before action; ordered verbs show what to do next.','Take paper and a pencil. Write your name. Add a border. Place the label beside your model.','state materials and a followable sequence','use listener feedback to improve a confusing step'),
 step('Give a route from a fixed orientation','On a grid A–C left to right and 1–3 bottom to top, start A1 facing row 3. Reach B3.','Forward two reaches A3. A right turn faces columns increasing; one forward reaches B3.','Forward two squares, turn right, then forward one square.','give a route with a clear start and facing direction','check a partner’s route and explain or correct an ambiguity')]),
 presentations:trail('Organise a message for an audience',['Choose a familiar topic','Access to a listener or supported audience alternative'],[
 step('Plan a short object talk','Introduce a pretend shell collection to a partner.','Name the object, choose relevant details and finish with a clear point.','This is a ridged shell. Its curved lines feel rough. I chose it because it reminds me of waves.','communicate a clear topic and relevant details','organise them so the listener can follow and understand the ending'),
 step('Use a visual purposefully','Explain a survey: bikes 3, scooters 5. Choose a visual.','Two labelled bars make comparison visible; I explain what the difference means rather than just read labels.','My chart shows two more scooters than bikes: five compared with three.','explain accurate information in an organised way','use a visual to support meaning and respond to a relevant question'),
 step('Adapt a digital presentation','For younger listeners, explain a pretend rain collector with two slides.','One idea per slide reduces clutter. I explain new words using a familiar action.','Slide 1: a container catching rain. Slide 2: markings showing the amount. Spoken explanation: the marks help us compare rainy days.','organise a short presentation for the stated audience','justify media choices and adjust wording or explanation after a question')]),
 questions:trail('Ask relevant, responsive questions',['A willing partner or role-play response','Listen or access the answer before following up'],[
 step('Follow up an answer','Answer: “I like the explorer because she helps a lost animal.” Ask a follow-up.','I pick up helping from the answer rather than change to an unrelated topic.','How did she work out where the animal belonged?','ask a question relevant to the topic','connect a follow-up to something in the actual answer'),
 step('Adapt a request to context','Ask a museum guide, then a friend, about a model boat.','Both requests can be respectful. The guide may need more introduction because we do not share the same context.','Guide: “Could you explain how this model was made?” Friend: “How do you think they made that boat?”','make a clear request in each context','explain a wording choice without ranking accents or dialects'),
 step('Avoid a leading question','Improve: “You were frightened when the bridge shook, weren’t you?”','That assumes a feeling. An open question lets the character offer an unexpected response.','How did you feel when the bridge shook?','ask questions about events, views and feelings without supplying the answer','summarise the answers fairly and identify a leading question')]),
 voice:trail('Use voice and language choices for meaning',['Comfortable accessible way to express or annotate meaning','Respect different accents and communication methods'],[
 step('Vary emphasis intentionally','Say or annotate “You came back!” as pleased, then surprised.','A warmer steady voice may convey pleasure; lifted pitch or stress on back can convey surprise. There is more than one effective choice.','Pleased: warm emphasis on you. Surprised: stronger emphasis on back, with a questioning lift.','identify different intended feelings','demonstrate or explain a voice choice that communicates each feeling'),
 step('Prepare expressive reading','Mark “Beyond the gate, the little path twisted into darkness.” for a listener.','I group the place phrase, pause briefly at the comma and emphasise darkness to support the meaning.','Beyond the gate, / the little path twisted into DARKNESS.','prepare pauses or emphasis that fit the meaning','explain a choice and refine the reading or annotation after feedback'),
 step('Discuss register without judging speakers','Compare “Would you mind moving along?” and “Shift over a wee bit.”','Context and relationships affect suitability; dialect is a language variety, not evidence of lesser ability.','The first may suit an unfamiliar visitor. The second may suit friends who understand it. Tone and context still matter.','identify a contextual difference in wording','explain suitability while respecting dialect and recognising more than one possible context')]),
 'factual-writing':trail('Plan clear information and supported viewpoints',['Distinguish supplied facts from invented details','Name the intended reader'],[
 step('Model a short helpful explanation','Show a younger reader how to return a board game. Together change one instruction; then write your own.','I choose an order and specific nouns so the reader does not need to guess what it means.','Put the pieces in the bag. Close the game box. Return the box to its labelled shelf.','write useful advice in a clear order','revise a reference or word to help the specified reader'),
 step('Write only what the data supports','Pretend survey: ants 7, beetles 3. Model a report sentence and conclusion.','I report sightings accurately and compare them; I cannot infer all places have more ants.','We recorded seven ant sightings and three beetle sightings. There were four more ant sightings in this survey.','report supplied information accurately','distinguish a supported conclusion from an unsupported generalisation'),
 step('Develop a reasoned proposal','Write a short proposal for a shaded reading bench.','A specific benefit and a response to a concern are stronger than exaggerated promises.','A shaded bench could make outdoor reading more comfortable. It would need a safe place away from the path, so we should check the space first.','organise a viewpoint with specific reasons','respond to a plausible concern and revise tone for the intended audience')]),
 layout:trail('Arrange information for a reader’s purpose',['Identify essential facts','Paper, accessible layout tool or structured text'],[
 step('Make an invitation easy to use','Arrange pretend details: craft swap; hall; Saturday; 11 am; bring spare card.','A heading names the event; labelled time and place let a reader find them quickly.','PRETEND CRAFT SWAP\nWhere: hall\nWhen: Saturday, 11 am\nBring: spare card','include the information a reader needs','arrange and label it so the intended reader can find it easily'),
 step('Transform prose into instructions','Prose: “Get paper and a crayon. Draw a large circle. Add a pattern inside it.”','I separate materials from actions and keep the original order without losing a step.','Materials: paper, crayon.\n1. Draw a large circle.\n2. Add a pattern inside it.','preserve the source information and sequence','use lists or numbered steps and explain why the layout helps'),
 step('Match two forms to different purposes','Pretend facts: a kite display planned for June; afterwards six kites flew. Compare a poster and report.','The invitation looks forward and highlights attendance details. The report looks back and organises what happened.','Poster heading: “Come to our pretend kite display!” Report opening: “Six kites flew at the imaginary June display.”','use appropriate facts and time framing for each form','explain how layout and emphasis serve each audience and purpose')]),
 poetry:trail('Experiment with sound, imagery and wordplay',['Hear or access word sounds appropriately','Respond creatively without one required style'],[
 step('Explore a sound rhyme','Make two lines ending in light and night.','I listen to the matching end sounds; matching letters alone would not prove a rhyme.','A tiny window spills its light;\nA silver path wakes in the night.','identify or create a sound rhyme','use it meaningfully in two lines and explain the sound connection'),
 step('Shape rhythm and imagery','Try a repeated opening for a river poem.','Repetition gives a pattern; a comparison adds an image. I read back to hear where a line is awkward.','River, carry a leaf like a boat.\nRiver, carry a twig afloat.\nRiver, whisper past the stone.\nRiver, wander on your own.','use an intentional repeated rhythm or phrase and an image','explain an effect and revise a line for sound or meaning'),
 step('Explain a playful choice','Create wordplay using a calendar’s dates.','Dates can mean calendar days or fruit. A joke works when the reader can recognise both meanings.','The calendar was hungry: it had a taste for dates.','use a deliberate wordplay or dialect choice','explain its meaning and adapt it so the intended audience can understand')]),
 'writers-style':trail('Make deliberate stylistic choices and revise',['Understand that different words can change effect','Accept readers may interpret differently'],[
 step('Choose a precise verb','Change “The squirrel went up the tree.”','Scampered suggests quick light movement; climbed is more neutral. I choose for the picture I want.','The squirrel scampered up the tree.','choose a word that changes the intended picture','explain the change rather than simply choose a longer word'),
 step('Create contrasting moods','Describe one doorway as welcoming, then uneasy.','I keep the doorway but alter selected light and sound, not just attach the labels happy and scary.','Welcoming: Warm light spilled across the doorstep. Uneasy: A thin strip of light trembled beneath the silent door.','select details that support each mood','compare their effects while keeping the setting recognisable'),
 step('Review a personal choice','A writer wants a calm scene: “Water rested in the bowl. A leaf turned slowly.” A reader notices tension. What next?','Intent is not enough; I ask which word caused the reader’s reaction and decide whether to revise.','I chose rested and slowly for calm. I would ask what felt tense, then test a clearer detail such as still morning light.','identify deliberate choices and intended effects','use reader feedback to make and explain a revision without copying a prescribed style')]),
 'digital-composition':trail('Combine media purposefully',['A suitable accessible tool for completed digital output','Use own or permitted images and protect personal information'],[
 step('Connect a caption to a picture','A sketch shows a bowl beneath a dripping tap. Add information with a caption.','The picture shows objects; a caption can explain the reason for the bowl.','The bowl catches drips while an adult arranges a repair.','write text that relates accurately to an image','explain information added by the words rather than merely name visible objects'),
 step('Plan an information card','Create a pretend seed card with a heading, three supplied facts and a drawing: beans are seeds; seeds vary in size; some travel in fruits.','I group related information, keep text readable and use my own labelled drawing.','Heading: Seeds. Three fact bullets plus a labelled drawing of a bean; revise spacing so each fact is easy to read.','combine accurate text and an appropriate image in a usable arrangement','explain and improve a layout choice after viewing the whole card'),
 step('Give each medium a purpose','Plan a story about a storm with text, drawing and optional sound.','Text gives the sequence; a drawing shows the scene. Sound should add something, not compete with the words.','Text explains the lost umbrella; a drawing shows its journey; optional soft rain audio sets the scene, with a written sound description available.','organise a coherent story across chosen media','justify what each medium adds and revise after audience feedback')]),
 'spoken-written':trail('Make meaning clear when context changes',['Recognise what a listener can see or ask','Identify who will read a message'],[
 step('Replace a vague reference','Rewrite “Put that there” for someone who cannot see a gesture.','I name the object and destination so the reader does not need shared surroundings.','Put the red folder in the tray beside the window.','replace vague references with needed information','explain why a reader without gestures needs that detail'),
 step('Turn an explanation into written guidance','A speaker says “Then do the same again” while showing a game move.','The writer must identify what to repeat and when; spoken interaction could have supplied that information.','After moving one counter forward, move the second counter forward one space too.','preserve the spoken idea in writing','add context or organisation that a reader cannot obtain by asking'),
 step('Write a clear proposal','Turn “Maybe we could stick something there to sit on” into a pretend proposal.','I name the place and object and give a reason, while keeping the suggestion rather than making it an order.','I suggest a bench beside the pretend reading tree so two readers can share a book.','state the proposal clearly without relying on shared gestures','add a relevant reason and choose wording suitable for the audience')]),
 spelling:trail('Apply and check spelling strategies',['Notice sounds and meaningful parts in words','Use an accessible spelling response method'],[
 step('Add an ending to an unchanged base','Add -ing to help.','Help ends with two consonants. I keep the base spelling and add ing.','helping','identify the base and ending correctly','apply the same pattern to a new suitable word and check it'),
 step('Change consonant plus y before -ed','Make the past tense of worry.','The consonant r is before y, so I replace y with i and add ed. This example does not imply that all suffixes behave the same way.','worried','apply the consonant-plus-y change for this ending','explain the change and distinguish a suitable non-example such as played'),
 step('Choose a strategy for an actual error','A draft says “unhapppy”. Model checking it.','I split un + happy. Happy has two p letters, not three. I confirm the spelling and use it in another sentence later.','unhappy: un + happy. “The unhappy character missed the train.”','identify and check an error using a relevant strategy','explain the strategy and retrieve the corrected spelling on a later fresh use')]),
 grammar:trail('Use punctuation and sentence choices for clarity',['Recognise a complete idea','Read or access a short sentence'],[
 step('Mark a statement’s boundary','Edit “our team arrived” as one statement.','The capital marks the beginning and the full stop shows where the statement ends.','Our team arrived.','mark the start and end of a statement','explain the boundary and apply it in another complete sentence'),
 step('Show one owner','One farmer owns a hat. Write the phrase.','Farmer names one owner. Adding apostrophe then s links that owner to the hat.','the farmer’s hat','write a singular possessive correctly for the given owner','explain the ownership and distinguish it from a plural owners phrase'),
 step('Connect a result clearly','Join: “The gate was locked. We used the side entrance.”','So can show a result. I keep both clauses complete and use a comma before so in this example; punctuation depends on sentence structure.','The gate was locked, so we used the side entrance.','join related clauses with a suitable relationship word','explain the relationship and punctuate the resulting sentence clearly')]),
 handwriting:trail('Develop comfortable and readable written communication',['Suitable paper and adapted writing tool if needed','Permission to pause or change method when uncomfortable'],[
 step('Check whether a message can be read','Write a short message such as “Meet by the model.” Ask a partner to read it.','I check whether letters and word spaces communicate the message. A comfortable effective grip is more important than matching a single grip style.','If model is hard to read, I identify which letter or gap needs attention and rewrite that small part.','produce a readable short message with suitable tools','identify and improve a specific letter or spacing feature without discomfort'),
 step('Revise a manageable sample','Compare two handwritten lines for spacing and letter size.','I choose one useful improvement rather than rewrite a whole page or race a clock.','My second line uses clearer gaps between words while keeping letter size comfortable and consistent.','identify a feature affecting legibility in a short paragraph','make a focused improvement and check that it helps another reader'),
 step('Keep useful readable notes','Partner says: “The model needs card, string and tape.” Write key notes using familiar words.','I record useful keywords instead of every word. Listening can be repeated so memory demands do not disguise handwriting needs.','Model: card, string, tape. I can read and use the notes later; if not, I choose one change for readability.','produce notes that can be read and used','explain a manageable way to improve fluency while preserving comfort and legibility')])
};

const choice=(prompt:string,options:string[],answer:string,hint:string,explanation:string,passage?:string):Task=>({prompt,options,answer,hint,explanation,...(passage?{passage}:{})});
export const englishPractice:Record<string,Task[]>={};
// Each bank supplies fresh examples of the SAME local subskill. These are practice
// variants, not psychometrically equated items or evidence that all English is covered.
englishPractice['detective:0']=[
 choice('What was beside the backpack?',['A silver whistle','A yellow glove','A red cup'],'A yellow glove','Find the words beside the backpack.','The glove was beside the backpack; the whistle was inside it.','A silver whistle lay inside the backpack. Beside the backpack was a yellow glove. A red cup stood on the bench.'),
 choice('Where did Eoin leave the note?',['Under a plate','Inside a shoe','On a windowsill'],'On a windowsill','Look for the sentence about leaving the note.','The text says the note was left on the windowsill.','Eoin looked under a plate for his pencil. He wrote a note and left it on the windowsill. Then he put on his shoes.'),
 choice('Which animal reached the pond first?',['The fox','The badger','The hare'],'The hare','Find first, then check the animal named.','The hare arrived first; the badger followed.','The hare reached the pond first. A badger followed, carrying a leaf. Much later, a fox appeared.'),
 choice('What colour was the kite?',['Purple','Orange','White'],'Orange','Match the colour to the kite rather than the clothing.','Orange describes the kite; purple describes the coat.','Farah wore a purple coat and white boots. Her orange kite fluttered above the field.')];
englishPractice['detective:1']=[
 choice('Which clue most strongly suggests somebody is working in the workshop now?',['Dust on an old shelf','A hammer tapping inside','A rusty sign'],'A hammer tapping inside','Choose a clue to a current action.','A hammer tapping suggests current work, unlike old dust or rust. It is an inference rather than certainty.','The workshop sign was rusty and an old shelf was dusty. Through the open window, Arun heard a hammer tapping.'),
 choice('What most strongly suggests that Beth feels nervous about performing?',['She wears blue shoes','She waits beside a wall','Her hands tremble as she checks her lines'],'Her hands tremble as she checks her lines','Look for behaviour connected to the performance.','Trembling while checking lines supports nervousness; the other details do not indicate a feeling.','Beth waited beside the stage wall in blue shoes. Her hands trembled as she checked her lines for the third time.'),
 choice('Which clue most strongly suggests the café is preparing to open soon?',['A faded photograph','Chairs being set beside clean tables','A crack in the old pavement'],'Chairs being set beside clean tables','Look for preparation happening now.','Setting chairs beside clean tables suggests preparation for customers; it does not prove an exact opening time.','A faded photograph hung by the café window. Inside, a worker set chairs beside clean tables. A crack crossed the pavement outside.'),
 choice('Why is it reasonable to think Ravi is trying not to wake someone?',['He walks on tiptoe and closes the door gently','He carries a green bag','The hallway is long'],'He walks on tiptoe and closes the door gently','Look for actions that reduce noise.','Tiptoeing and gentle closing both reduce noise and support the inference. Other explanations remain possible.','Ravi carried a green bag along the long hallway. He walked on tiptoe and eased the bedroom door shut without a sound.')];
englishPractice['detective:2']=[
 choice('Which new detail changes Mo’s idea about the scratching?',['A lizard scratches the tank wall','A curtain is yellow','The room has a shelf'],'A lizard scratches the tank wall','Find what identifies the source of the sound.','The lizard supplies new evidence; the noise need not come from the imagined mouse.','Mo thought a mouse was scratching behind the shelf. Then she saw the pet lizard scratching the wall of its tank. The yellow curtain moved in the breeze.'),
 choice('Why does Dan change his idea about the wet floor?',['He sees an open umbrella dripping','The carpet is blue','The window is closed'],'He sees an open umbrella dripping','Which detail supplies a different source of the water?','The dripping umbrella explains the water more directly than Dan’s first idea about a leaking roof.','Dan thought the roof had leaked onto the floor. The window was closed. Then he noticed an open umbrella dripping onto the blue carpet.'),
 choice('What new evidence changes Lia’s understanding of the word bank?',['A muddy slope beside the stream','A sign showing money','A clock on the wall'],'A muddy slope beside the stream','Match the meaning of bank to the later setting.','The stream and muddy slope show a river bank rather than a place for money.','“Meet me at the bank,” the message said. Lia pictured a building where people kept money. The next message showed a muddy slope beside the stream.'),
 choice('Why does Owen revise his belief that the model is broken?',['He learns its wheel is designed to come off','The model is red','The box is large'],'He learns its wheel is designed to come off','Look for information explaining the loose part.','The design explanation changes the loose wheel from evidence of damage to an intended feature.','Owen saw a wheel beside the red model and thought it had snapped off. The instructions in the large box said: “Remove this wheel to see how the gears turn.”')];

englishPractice['words:2']=[
 choice('Choose the correct spelling: “The ___ carried bags.”',['travellers','travelerss','travellars'],'travellers','In this UK spelling, keep traveller and add s.','Traveller + s = travellers.'),
 choice('Choose the correct spelling: “The ___ explained the route.”',['guiddes','guides','gides'],'guides','Keep the base word guide and add s.','Guide + s = guides.'),
 choice('Choose the correct spelling: “Two ___ painted the sign.”',['artests','arttists','artists'],'artists','Keep artist and add s.','Artist + s = artists.'),
 choice('Choose the correct spelling: “The ___ prepared the meals.”',['cookes','cooks','cokks'],'cooks','The base word cook keeps its double o.','Cook + s = cooks.')];

englishPractice['grammar:0']=[['The ferry arrived.','the ferry arrived.','The ferry arrived,'],['My pencil broke.','my pencil broke','My pencil broke,'],['A leaf fell.','A leaf fell,','a leaf fell.'],['We packed lunch.','we packed lunch.','We packed lunch,']].map(([answer,b,c])=>choice('Which statement has a capital letter and a full stop?',[b,answer,c],answer,'Check both the beginning and the end.',`${answer} begins with a capital letter and ends the statement with a full stop.`));
englishPractice['grammar:1']=[['boy','bag'],['pilot','cap'],['teacher','desk'],['dog','bowl']].map(([owner,item])=>choice(`There is one ${owner}. Which phrase shows the ${item} belonging to that ${owner}?`,[`the ${owner}s’ ${item}`,`the ${owner}’s ${item}`,`the ${owner}s ${item}`],`the ${owner}’s ${item}`,'For this singular owner, add apostrophe then s.',`${owner} names one owner. ${owner}’s shows that owner’s ${item}; ${owner}s’ would refer to multiple owners.`));
englishPractice['grammar:2']=[['The bus was late','we walked to school'],['The box was heavy','we carried it together'],['The path was flooded','we chose another route'],['The sun was bright','we put on our hats']].map(([a,b])=>choice('Which sentence clearly joins a cause and its result?',[`${a}, so, ${b}.`,`${a} ${b}.`,`${a}, so ${b}.`],`${a}, so ${b}.`,'The result needs a clear link to the first clause.',`So links the result to the first clause. The comma before so separates the clauses here; an extra comma immediately after so interrupts the connection.`));
englishPractice['spelling:0']=[['paint','painting','paintting','painteng'],['look','looking','lookking','lookeng'],['float','floating','floatting','floateng'],['rest','resting','restting','resteng']].map(([base,answer,b,c])=>choice(`Add -ing to ${base}. Which spelling is correct?`,[b,c,answer],answer,'For this word, keep the base spelling and add ing.',`${base} + ing = ${answer}; no extra consonant is needed in this word.`));
englishPractice['spelling:1']=[['hurry','hurried','hurryed','huried'],['copy','copied','copyed','coppied'],['study','studied','studyed','studdied'],['try','tried','tryed','tryd']].map(([base,answer,b,c])=>choice(`Choose the correct past tense of ${base}.`,[b,answer,c],answer,'A consonant comes before the final y. For -ed, change that y to i.',`${base} becomes ${answer}: change final y to i before adding ed.`));

englishPractice['reading-library:0']=[
 choice('Why does the character stop?',['A branch blocks the path','She needs a drink','She loses her map'],'A branch blocks the path','Look for the obstacle just before she stops.','The fallen branch blocks her way.','Mara followed the path to the gate. A fallen branch blocked the path. She stopped and looked for a safe way around it.'),
 choice('Why does the character open the box?',['To hide a shoe','To find out what is rattling','To take a nap'],'To find out what is rattling','Read the event before the opening.','The rattle makes him curious about the box’s contents.','A small box rattled when Alf moved it. Curious about the noise, he lifted the lid. Inside were three wooden beads.'),
 choice('Why does the character turn back?',['She forgot her notebook','The sun sets','A friend calls her name'],'A friend calls her name','Locate what happens just before the turn.','Her friend calls, and she turns to respond.','Ella walked towards the bridge with her notebook. Behind her, a friend called, “Ella!” She turned back and waved.'),
 choice('Why does the character move the pot?',['To give the plant light','To empty it','To paint the wall'],'To give the plant light','Look for the reason stated near the action.','He moves it out of the shade so sunlight can reach it.','The seedling leaned towards the window. Cian moved its pot out of the shade so the sunlight could reach its leaves.')];
englishPractice['reading-library:1']=[
 choice('Which phrase gives a non-human thing a human action?',['the stone wall','the window winked','the narrow street'],'the window winked','Look for an action a person can do.','Winking is a human action used here for a window reflecting light.','Morning shone on the stone wall. The window winked above the narrow street.'),
 choice('Which phrase uses personification?',['the moon listened','a white cloud','the dark field'],'the moon listened','Find a human-like action given to the moon.','Listening makes the moon seem like a person paying attention.','Above a white cloud, the moon listened to the stillness of the dark field.'),
 choice('Which phrase gives a human quality to the rain?',['on the roof','small drops','the rain argued'],'the rain argued','Which verb usually describes people disagreeing?','Argued gives the rain a human action to suggest noisy, insistent falling.','Small drops gathered on the roof; then the rain argued with the sleeping house.'),
 choice('Which phrase uses personification?',['the old stairs complained','a blue carpet','beside the door'],'the old stairs complained','Look for an action associated with a person’s voice.','Complained gives the stairs a human action, suggesting creaking.','Beside the door lay a blue carpet. Under my feet, the old stairs complained.')];
englishPractice['reading-library:2']=[
 choice('Which statement does the text support?',['All seeds float','Some seeds travel on the wind','Seeds only move in water'],'Some seeds travel on the wind','Choose what the text states, keeping words such as some.','The text says some seeds can be carried by wind; it does not generalise to all seeds.','Some seeds have light structures that help the wind carry them. Other seeds travel in different ways.'),
 choice('Which claim is supported?',['Every bird visits every day','The same bird was counted each time','Six visits were recorded'],'Six visits were recorded','Distinguish recorded visits from known individual birds.','The observation recorded six visits but could not establish six different birds.','During one watch, a bird feeder received six visits. The observer could not tell whether some visits were by the same bird.'),
 choice('Which claim is supported?',['A shadow changes as the light’s position changes','Shadows always stay still','Every shadow is the same size'],'A shadow changes as the light’s position changes','Find the change described in the investigation.','Changing the lamp’s position changed the shadow in this investigation.','The class placed a toy near a lamp. When they moved the lamp, the toy’s shadow changed position.'),
 choice('Which claim follows from this information?',['The library never closes','Books may be renewed if no one is waiting','Every loan lasts a year'],'Books may be renewed if no one is waiting','Keep the condition attached to the claim.','Renewal is possible under the stated condition; the text does not promise it in all cases.','This imaginary library lends books for two weeks. A book may be renewed if no other reader is waiting for it.')];

englishPractice['word-strategies:0']=[['“The floor was sandy after our beach walk.”','sandy','Covered with sand','Made of snow','Very noisy','sand'],['“The field was snowy after the winter storm.”','snowy','Covered with snow','Made of paper','Very hot','snow'],['“The track was stony, with small rocks underfoot.”','stony','Covered with stones','Full of flowers','Entirely smooth','stone'],['“The room was smoky after the toast burned.”','smoky','Containing smoke','Covered in water','Brightly painted','smoke']].map(([passage,word,answer,b,c,base])=>choice(`What does ${word} mean here?`,[b,answer,c],answer,`Use the word part ${base} and check the sentence.`,`${base} helps with the meaning, and the context supports ${answer.toLowerCase()}.`,passage));
englishPractice['word-strategies:1']=[['unfair','fair','not fair'],['unkind','kind','not kind'],['unclear','clear','not clear'],['unusual','usual','not usual']].map(([word,base,meaning])=>choice(`What does the prefix un- do in ${word}?`,[`It means very ${base}`,`It makes the meaning ${meaning}`,`It means ${base} yesterday`],`It makes the meaning ${meaning}`,`Identify the base word ${base}.`,`Here un- means not: ${word} means ${meaning}. Check the whole word and context when using prefixes.`));
englishPractice['spoken-written:0']=[
 choice('Which written instruction is clearest without pointing?',['Put those there.','Place the pencils in the blue pot.','Move that stuff.'],'Place the pencils in the blue pot.','Name the objects and their destination.','Pencils and blue pot identify what to move and where.'),
 choice('Which written instruction is clearest to someone who cannot see your gesture?',['Stick it over there.','Do that now.','Attach the label to the front of the box.'],'Attach the label to the front of the box.','Look for an explicit object and location.','The label, box and front specify the action without gestures.'),
 choice('Which written instruction supplies the missing context?',['Put the clean plates on the kitchen table.','Put them where I said.','Put the things away there.'],'Put the clean plates on the kitchen table.','A new reader needs to know what and where.','Clean plates and kitchen table make the instruction clear.'),
 choice('Which instruction can a reader follow without seeing you point?',['Take this over to him.','Give the green folder to the librarian.','Pass that thing along.'],'Give the green folder to the librarian.','Choose named items and people.','The folder and recipient are identified explicitly.')];
// Sentence-building trails retain their physical word-tile interaction and unique tokens.
englishPractice['words:0']=['The rabbit hopped.','The lantern glowed.','The engine hummed.','The dancer bowed.'].map(answer=>({prompt:'Tap the words to build a statement beginning with “The”.',words:[answer.split(' ')[2],answer.split(' ')[0],answer.split(' ')[1]],answer,hint:'Start with The, name who or what, then tell what happened.',explanation:`${answer} gives a complete message and ends with a full stop.`}));
englishPractice['words:1']=['Where is the basket?','Where is the ticket?','Where is the lantern?','Where is the shell?'].map(answer=>({prompt:'Build the question beginning with “Where”. Keep the question mark.',words:[answer.split(' ')[3],answer.split(' ')[2],answer.split(' ')[0],answer.split(' ')[1]],answer,hint:'Begin Where is, then name the object you are asking about.',explanation:`${answer} asks for a location. Its capital letter and final question mark make that clear.`}));
