import {trail as t,choice as c,practical as p} from './authoring.ts';
const review=['I completed the activity','I explained or shared my choices','I reflected and improved something'];
export const english=[
 t('reading-library','The reading nook','English','Reading','Explore fiction, poetry and information texts using different reading purposes.',[
 c('In this story, why does Finn stop?',['He hears a tapping sound','He loses his boots','He wants to sleep'],'He hears a tapping sound','Find the event just before Finn pauses.','The tapping catches Finn’s attention; the text states that he stops to listen.','Finn splashed along the lane in his boots. A tapping sound came from the wall. He stopped to listen. Behind a loose stone, a beetle was nudging a dry leaf.'),
 c('Which phrase gives the wind a human action?',['the wind tiptoes','silver rain','the narrow lane'],'the wind tiptoes','Look for an action a person might do.','Tiptoeing is a human action. Giving it to the wind is personification.','Silver rain on the window pane,\nThe wind tiptoes down the narrow lane.\nA small leaf turns, a branch bows low,\nThe garden hums a song we know.'),
 c('Which claim is supported by the information text?',['Air helps the tiny living things break scraps down','All scraps belong in compost','Compost forms instantly'],'Air helps the tiny living things break scraps down','Choose only what the text provides evidence for.','The passage explicitly says air helps decomposers. It does not say every kind of scrap is suitable.','Composting turns some plant scraps into material that improves soil. Tiny living things break the scraps down. Air and suitable moisture help them work. A mix of dry leaves and plant scraps can be useful. Ask an adult what can safely go into your compost bin.')]),
 t('reading-habits','Find your next favourite','English','Reading','Build sustained reading, preferences and shared or independent reading experiences.',[
 p('Choose a suitable book or one of the app’s stories with an adult. Read a short part together, taking turns. Tell each other one thing you noticed.','Ask for help with unfamiliar words. Shared reading is a chance to hear another reader.', ['We chose a text together','We took turns or read together','I shared a detail I noticed'],'Adult review: model phrasing and support word reading without rushing. Record participation, not a reading-age judgement.'),
 p('Choose a text that interests you. Read quietly for a comfortable stretch without a timer. Write or tell someone what held your attention and which part you want to read next.','You may stop at a natural break and continue later.', ['I read independently for a comfortable stretch','I explained a preference','I chose a next reading step'],'Adult review: discuss enjoyment and understanding. Adapt text length to the reader; do not turn sustained reading into a speed contest.'),
 p('Compare two texts you have read: perhaps a story and a fact book. Explain your preferences with examples. With a partner, recommend one and respond to their recommendation.','Consider language, subject, layout and purpose.', ['I compared two texts with examples','I explained my preferences','I listened to another recommendation'],'Adult review: accept different preferences. Look for specific reasons and growing independence in choosing reading.')],'practical'),
 t('source-detective','Can I trust this?','English','Reading','Locate, select and evaluate information for a purpose across sources.',[
 c('You need to know when a museum opens. Which source is most directly useful?',['The museum’s current opening-times page','An old fictional story about a museum','A drawing of a museum'],'The museum’s current opening-times page','Match the source to the question and check its date.','The museum’s own current opening-times information is the best starting point; special closures still need checking.'),
 c('A poster says “Our garden is the best!” A record sheet says “We counted 12 plant species on Monday.” Which is evidence from an observation?',['The record-sheet statement','The word best','Both are measured facts'],'The record-sheet statement','Look for a recorded observation that could be checked.','The sheet records a count and a day. We would still need to ask how the count was made before judging its reliability. “Best” is a judgement without a stated criterion.'),
 p('With an adult, choose a safe factual question. Compare two suitable sources. Record who produced them, when, what they agree on and a fact that needs checking. Share a short answer with its sources.','Choose sources with a clear author or organisation. Do not follow unknown links alone.', ['I selected information relevant to my question','I compared authority and freshness','I communicated an answer and its sources'],'Adult review: help choose child-safe sources. Look for relevance and corroboration; a polished layout alone does not establish reliability.')]),
 t('media','One event, different voices','English','Reading','Compare how texts and media present information and engage attention.',[
 c('Which sentence is a neutral report?',['The school planted ten trees.','Our absolutely amazing trees will change everything!','You must love our trees!'],'The school planted ten trees.','Look for a statement without pressure or exaggerated praise.','The first sentence reports a count without telling the reader how to feel.'),
 c('A headline reads “Tiny team, gigantic change!” What is its main effect?',['It makes the event sound striking','It gives the exact team size','It proves all changes are good'],'It makes the event sound striking','Notice the contrast between tiny and gigantic.','The contrast attracts attention and suggests a large impact; it does not provide exact measurements.'),
 p('Compare these accounts: Report: “Six pupils collected four bags of litter on Friday.” Poster: “Join our brilliant clean-up crew and rescue the park!” Discuss fact, persuasion, intended audience and missing information. Then create a fair headline.','Ask what each writer wants the reader to know or do.',review,'Adult review: the report provides numbers and a time; the poster invites action with emotive words. Neither account alone tells us the long-term result.')]),
 t('reading-response','Show what you understood','English','Reading','Represent and discuss understanding through visual, spoken, dramatic and digital responses.',[
 p('Read: “Mia found a seed. She planted it in a pot and watered it. A shoot appeared.” Draw three pictures showing the sequence, then explain them to a partner.','Choose one main event per picture.',review,'Adult review: pictures and explanation should follow finding, planting/caring, then growth. Artistic quality is not being assessed.'),
 p('Read an app story with a partner. Make a freeze-frame pose for an important moment. Explain what each character may be thinking and point to clues in the story.','A freeze-frame is a still pose that shows a moment.',review,'Adult review: distinguish explicit details from plausible inferences. Accept more than one interpretation when supported by evidence.'),
 p('Choose a passage in the reading nook. Create a digital text summary and a sketch or oral explanation of its main ideas. Explain why each format helps an audience understand.','You can type your summary in the notes below and make the sketch on paper.',review,'Adult review: look for accurate main ideas, selective detail and thoughtful use of format. This app does not record audio or upload pictures.')],'practical'),
 t('word-strategies','Unlock an unfamiliar word','English','Reading','Combine decoding, word parts and context, then cross-check meaning.',[
 c('“The path was muddy after the rain.” What does muddy mean here?',['Covered in wet earth','Made of glass','Very sunny'],'Covered in wet earth','Use the familiar word mud and the clue after the rain.','The word part mud and the rainy context both support wet earth.'),
 c('In “The bridge was unsafe, so we stayed back”, what does the prefix un- do?',['Makes safe mean not safe','Means very safe','Means safe yesterday'],'Makes safe mean not safe','Look at the base word safe.','Un- often means not. The action stayed back supports the meaning unsafe.'),
 p('Choose an unfamiliar word from a suitable text with an adult. Try its sounds and parts, reread the sentence, then check a dictionary. Explain how you checked both pronunciation and meaning.','Context can suggest meaning, but check that it matches the written word.',review,'Adult review: help with the dictionary and sounds where needed. Do not reward guessing a different word that merely fits the sentence.')]),
 t('reading-purpose','Choose your reading tool','English','Reading','Skim, scan and read closely for different purposes.',[
 c('You need one bus time from a timetable. What is most useful?',['Scan for the route and time','Read every word aloud twice','Guess from the page colour'],'Scan for the route and time','You are searching for one specific piece of information.','Scanning helps locate a specific item; then read the relevant row and column carefully.'),
 c('You want the general topic of an article before deciding to read it. What helps?',['Skim its title and main sections','Count its commas','Read only its last letter'],'Skim its title and main sections','Look for a quick overview.','Skimming gives a broad sense of purpose and content, not every detail.'),
 p('Use one suitable information text. First skim for its main idea, then scan for one fact, then read a paragraph closely and explain a detail. Compare what each strategy helped you learn.','State your purpose before each reading.',review,'Adult review: the child should match strategy to purpose and confirm specific facts by close reading. Fast reading is not always the best choice.')]),
 t('listen-texts','Listen for the meaning','English','Talking and Listening','Listen and respond to stories, poems, drama and media messages.',[
 p('Ask a partner to read: “The lantern swung. A boat tapped the pier. A voice called, ‘Wait for me!’” Listen without looking, then retell what you heard. Ask to hear it again if needed.','Listen for objects, sounds and the spoken words.',review,'Adult review: accept a sensible retelling, not exact memorisation. Discuss who the voice might belong to and label that as an inference.'),
 p('Ask a partner to read the poem in the reading nook aloud twice. Describe an image it creates and how the voice changed its meaning. Then swap roles.','Listen for rhythm, pauses and emphasis.',review,'Adult review: look for a response linked to the poem and thoughtful listening. Different images and reading styles are welcome.'),
 p('With an adult, listen to a suitable short announcement or act out this one: “The library closes at four today. Please return borrowed games before you leave.” Summarise the information, audience and requested action.','Separate what listeners need to know from what they need to do.',review,'Adult review: closing at four is information; returning games is a requested action. For other chosen media, review against its actual content.')],'practical'),
 t('retell-drama','Step into the story','English','Talking and Listening','Retell, interpret and improvise stories and real or imagined experiences.',[
 p('Tell a partner about an ordinary journey, real or imagined. Include a beginning, something you noticed and an ending. Let them ask a question.','Use first, next and finally if they help.',review,'Adult review: look for a coherent sequence and relevant details. Do not ask the child to disclose personal locations.'),
 p('With a partner, act out a scene in which a lighthouse keeper has lost a map. Improvise dialogue, then retell the scene from the keeper’s point of view.','Think about what each character knows and wants.',review,'Adult review: discuss how the same events feel different from another viewpoint. Support turn-taking and imaginative choices.'),
 p('Choose a curriculum idea, such as a garden needing water. Improvise a discussion between a gardener, a plant and a raincloud. Describe the setting and explain which parts are factual and which are imagined.','A character can explain a fact through an imagined voice.',review,'Adult review: distinguish biological facts from personification and fantasy. Encourage reasons, descriptive language and responsive improvisation.')],'practical'),
 t('discussion','Every voice matters','English','Talking and Listening','Use discussion conventions, reasons and evidence to share and evaluate ideas.',[
 p('With a partner, choose a story setting: forest or coast. Take turns giving a reason. Repeat one thing your partner said before you reply.','Listening includes letting the other person finish.',review,'Adult review: support turn-taking and accurate listening. Either setting can be justified.'),
 p('Discuss whether a class reading corner should be quiet all the time. Give a reason and an example. Respond respectfully to a different view.','Try “I agree because…” or “I see it differently because…”.',review,'Adult review: distinguish disagreement with an idea from criticism of a person. Look for reasons and responses.'),
 p('With two or more willing people, plan how to use a pretend £30 library budget. Agree ground rules, consider different proposals and summarise the final decision and any disagreement.','Invite quieter people to contribute and check that you have understood.',review,'Adult review: assess the discussion process, use of reasons and fair summary. A unanimous decision is not required.')],'practical'),
 t('instructions','Say it clearly','English','Talking and Listening','Give, follow and improve guidance and directions.',[
 p('Tell a partner how to arrange a pencil to the right of a book and a rubber above the book. Do not point. Ask them to explain what they heard, then compare the arrangement.','Use precise position words.',review,'Adult review: check that the pencil is to the right of the book and the rubber is above the book from the shared viewing position. Invite clarification rather than guessing.'),
 p('Explain how to make a simple paper bookmark in four steps. Let a partner follow the instructions, then swap roles and improve any confusing step.','Say what is needed before the steps.',review,'Adult review: check sequence, clarity, safe materials and response to questions.'),
 p('On paper, draw a 4 by 4 grid of squares. Label columns A to D from left to right and rows 1 to 4 from bottom to top. Both partners look from the bottom edge. Put the library at A1, the pond at A3, the bakery at C3 and the park at C2. Start at the library facing towards row 4. Explain this route without pointing: move to the pond, turn right and move to the bakery, turn right and move to the park, then turn left to face column D. Ask your partner to repeat the route and clarify any unclear instruction. You can use a counter, finger or spoken square labels.','Include a starting point and initial facing direction.',review,'Adult review: the route is forward two squares to A3, right then forward two to C3, right then forward one to C2, and left to finish facing D2. There are three turns. Judge clear sequence and clarification, not drawing or motor control.')],'practical'),
 t('presentations','Your idea, your audience','English','Talking and Listening','Prepare oral presentations and adapt voice and media for a familiar audience.',[
 p('Choose a familiar object. Plan three things to say about it and give a short talk to a partner. Speak clearly enough for them to hear comfortably.','Start by naming the object and finish with your favourite detail.',review,'Adult review: support an audible, comfortable voice and a simple structure. No timer or recording is required.'),
 p('Explain a maths or reading discovery to a small familiar group. Use a drawing or chart. Invite a question and check that your visual helps the explanation.','Use an opening, two main points and a closing sentence.',review,'Adult review: assess structure, audience awareness, voice and how the visual supports meaning.'),
 p('Prepare a brief presentation about a fictional school garden using two slides or a digital picture plus spoken explanation. Adjust your wording for a younger audience and respond to questions.','Keep visual text short and explain it in your own words.',review,'Adult review: use a suitable separate presentation tool with adult support. Check accuracy, clear voice, purposeful media and thoughtful answers.')],'practical'),
 t('questions','The curious interviewer','English','Talking and Listening','Ask suitable questions and talk in formal and informal situations.',[
 p('Ask a partner about a favourite fictional character. Use one who/what question and one why/how question. Listen and ask a relevant follow-up.','A follow-up connects to the answer you just heard.',review,'Adult review: check relevance and listening. Personal information is not needed.'),
 p('Role-play asking a librarian for help finding a book. Then ask a friend about the same book. Discuss how your wording and tone changed.','Both conversations can be polite, with different levels of formality.',review,'Adult review: look for clear requests and sensitivity to audience; avoid judging a child’s natural accent.'),
 p('Plan an imaginary interview with a character who has just solved a problem. Ask about events, opinions and feelings without suggesting the answer. Summarise their responses fairly.','An open question leaves room for an unexpected answer.',review,'Adult review: distinguish open questions from leading ones and look for accurate summarising.')],'practical'),
 t('voice','Words in different voices','English','Talking and Listening','Explore expressive reading, register, dialect and colloquial language.',[
 p('Read aloud: “You found it!” First sound surprised, then relieved. Explain how your voice changed the feeling.','Try changing emphasis and pace without shouting.',review,'Adult review: both interpretations may work. Ask which vocal choices supported the intended feeling.'),
 p('Read a short passage you have prepared, including something you wrote. Mark places to pause and words to emphasise, then share it aloud with a familiar listener.','Let punctuation and meaning guide your pauses.',review,'Adult review: focus on conveying meaning, not speed or accent. Invite a rereading after feedback.'),
 p('With an adult, compare “Could you please help me?” and “Give us a hand, will you?” Discuss audience, context, formality and everyday expressions. Share a dialect expression you know if you wish.','Different varieties of language can be appropriate in different settings.',review,'Adult review: respect dialects and accents. Explain that register is a choice for context, not a ranking of people’s speech.')],'practical'),
 t('factual-writing','Write to make a difference','English','Writing','Plan and compose factual writing, opinions and persuasive texts for different audiences.',[
 p('Write three clear sentences for a younger child explaining how to care for a book. Plan the order first, then reread for clarity.','Use helpful instructions such as Keep, Turn and Put.',review,'Adult review: check useful advice, audience and sentence clarity. Do not require one exact wording.'),
 p('Write a short factual report about a pretend wildlife survey: robins 6, wrens 2, blackbirds 4. Include a title, accurate findings and a conclusion that does not go beyond the evidence.','Sightings are not necessarily different birds.',review,'Adult review: verify counts, distinguish observation from inference, and discuss the report structure.'),
 p('Write a letter arguing for a school garden. Plan a viewpoint, two reasons and a response to a possible concern. Revise the tone for a head teacher.','Persuasion is stronger when reasons are specific and claims are honest.',review,'Adult review: check purpose, audience, paragraph organisation and reasonable support. The letter stays in the app and is not sent.')],'practical'),
 t('layout','Make the page work','English','Writing','Choose text forms and layouts appropriate to a purpose and audience.',[
 p('Plan a poster for an imaginary book swap. Include a clear heading, place, date and what to bring. Label all details as pretend.','Important information should be easy to find.',review,'Adult review: check essential details and readable organisation. Artistic polish is not the learning goal.'),
 p('Turn this paragraph into a materials list and numbered instructions: “Take a strip of card and a pencil. Write a title near the top of the card. Draw a small picture beneath the title. Place the finished card between two pages to mark your place.” Keep the same information, put the steps in order and compare how easy each layout is to follow. Write in the notes or on paper.','A reader should be able to follow the order at a glance.',review,'Adult review: materials are a strip of card and a pencil. Steps are write the title, draw below it, then place the card between pages. Accept taking the card as an initial step. Check sequence and layout; invite a partner to follow the instructions.'),
 p('Use these pretend event facts: a seed swap in the school garden on 10 May at 2 pm; visitors bring spare seeds. First make an invitation poster as if the event is still to come. Then imagine it has finished and write a news report saying that twelve visitors swapped seeds. Explain how headings, paragraphs and emphasis change for each purpose. Label both pieces as imaginary; use notes or paper.','A report explains what happened; a poster may invite people to something.',review,'Adult review: check genre conventions and clarity. Discuss how layout shapes attention without replacing accurate content.')],'practical'),
 t('poetry','The poetry playground','English','Writing','Experiment with rhyme, rhythm, verse, wordplay and dialect.',[
 p('Write two playful lines about rain. Try one pair of rhyming words, then read the lines aloud.','Rhyme depends on sound, not just matching letters.',review,'Adult review: check a genuine sound rhyme while valuing imaginative choices. Offer a non-rhyming alternative if useful.'),
 p('Write a four-line poem about a familiar place. Choose a repeating rhythm or phrase, and try one surprising comparison. Read it aloud and revise a line.','Tap a comfortable beat while you read.',review,'Adult review: discuss how rhythm and imagery affect the listener. Poems do not need to rhyme.'),
 p('Write a short poem using wordplay or a familiar dialect expression. Explain the effect and the audience who will understand it. Revise for sound and meaning.','A pun plays on more than one meaning; dialect can give a poem a distinctive voice.',review,'Adult review: value language variety. Ask the writer to explain intentional choices and help make unfamiliar expressions understandable.')],'practical'),
 t('writers-style','Make the reader feel it','English','Writing','Develop stylistic choices, personal voice, mood and effect through revision.',[
 p('Rewrite “The dog went down the path” with a more precise movement word. Explain how it changes the picture.','Try a verb that tells how the dog moves.',review,'Adult review: verbs such as padded, bounded or limped create different meanings. Accept a justified choice.'),
 p('Describe the same room first as welcoming and then as unsettling. Change details and word choices while keeping the room recognisable.','Think about light, sound and what a character notices.',review,'Adult review: discuss how selected details create mood rather than simply adding adjectives.'),
 p('Write a short scene in your own style. Identify two deliberate choices, such as sentence length or imagery. Ask a reader about the effect and revise where their response differs from your intention.','A personal voice develops through choices and revision.',review,'Adult review: evaluate the intended effect with the writer. Avoid imposing a single preferred style.')],'practical'),
 t('digital-composition','Words, pictures, meaning','English','Writing','Organise and present ideas using digital text with graphics or sound.',[
 p('Type a short caption for a drawing you make on paper. Explain what the words add that the picture alone does not show.','A caption can identify, explain or add a new detail.',review,'Adult review: check the relationship between picture and words. The drawing remains on paper in this release.'),
 p('With an adult and a suitable drawing tool, make a digital information card combining a heading, three facts and a picture you create. Plan first and revise the layout.','Use your own image or a properly licensed one.',review,'Adult review: check factual accuracy, readable arrangement and image permissions. Use a separate tool; the app does not upload media.'),
 p('Plan a short digital story combining text, your own drawing and an optional spoken reading. Explain what each medium contributes. Create it with adult support in a suitable tool and review it with an audience.','Do not record or share other people without permission.',review,'Adult review: assess organisation and purposeful combination of media. Audio creation is optional and external; this app makes no recordings.')],'practical'),
 t('spoken-written','From conversation to page','English','Writing','Recognise differences between spoken and written language.',[
 c('Which message is clearer in written instructions?',['Place the book on the shelf beside the door.','Put it over there.','You know, that thing goes there.'],'Place the book on the shelf beside the door.','A reader cannot see your pointing gesture.','Specific nouns and position words make the written instruction clear without gestures.'),
 p('Say a short explanation of a game to a partner. Then write it for someone who cannot ask questions. Discuss what you needed to add or change.','Written explanations often need more explicit references and organisation.',review,'Adult review: compare clarity in the two contexts without treating speech as inferior.'),
 p('Turn “Well, I reckon we should, you know, put some seats there” into a clear written proposal for a class garden. Keep the idea and add the information a reader needs.','Clarify where, what kind of seats and why.',review,'Adult review: look for a clear proposal, reasons and audience awareness. More than one wording is acceptable.')]),
 t('spelling','Word-building workshop','English','Writing','Use sound, word parts, word families and checking strategies to spell.',[
 c('Add -ing to jump. Which spelling is correct?',['jumping','jumpping','jumpeng'],'jumping','The base word jump stays the same.','Jump + ing = jumping.'),
 c('Which is the correct past tense of carry?',['carried','carryed','caried'],'carried','For consonant + y, change y to i before adding -ed.','Carry becomes carried. Compare hurry → hurried.'),
 p('Choose three spelling words from your own writing. For each, identify a useful strategy: sounds, syllables, word family or a word part. Check a dictionary, use it in a sentence and revisit it later.','Different words may need different strategies.',review,'Adult review: confirm spellings and discuss why each strategy helps. Correct a misconception before repeated practice.')]),
 t('grammar','Punctuation with a purpose','English','Writing','Use grammar and punctuation to make meaning clear.',[
 c('Which sentence uses a capital letter and full stop correctly?',['The boat is blue.','the boat is blue','The boat is blue,'],'The boat is blue.','A statement starts with a capital and can end with a full stop.','“The boat is blue.” is a complete statement with a capital letter and a full stop.'),
 c('There is one girl. Which phrase means the coat belonging to her?',["the girl’s coat","the girls’ coat","the girls coat"],"the girl’s coat",'For one owner, add apostrophe + s.',"The girl’s coat uses a singular possessive apostrophe. Girls’ would mean more than one girl."),
 c('Which sentence joins the cause and result with so, using one comma immediately before so and no comma after it?',['The rain stopped, so we went outside.','The rain stopped we went outside.','The rain stopped, so, we went outside.'],'The rain stopped, so we went outside.','Check the stated pattern: first clause, so second clause.','So links the result to its cause. This question asks for a comma before so and none after it; the first option follows that pattern.')]),
 t('handwriting','A message worth reading','English','Writing','Develop comfortable, fluent and legible handwriting.',[
 p('On paper, write a short friendly message. Choose a comfortable pencil grip and position. Ask someone to read it back.','Aim for readable letters and spaces, not speed.',review,'Adult review: offer support for posture, grip, letter formation and spacing. Adapt tools for motor needs; do not enforce one grip if another is comfortable and effective.'),
 p('Write a short paragraph on paper. Check consistent spacing and letter size. Rewrite one line to improve readability without rushing.','Let the writing sit comfortably on the line.',review,'Adult review: focus on a manageable improvement. Joined writing is useful only when it supports comfort and legibility.'),
 p('Write a short set of notes on paper while listening to an adult explain a familiar topic. Review whether you can read and use them, then identify one way to improve fluency.','Capture key ideas instead of every word.',review,'Adult review: balance fluency with legibility and understanding. Adapt the activity for handwriting difficulties; typing can support access but does not itself demonstrate handwriting.')],'practical')
];
