import type {Task} from './content.ts';

/** AI-assisted authoring, awaiting qualified NI KS2 teacher sign-off.
 * The three steps sometimes introduce different subskills. They are a teaching
 * sequence, not evidence that success on one item measures a child's ability.
 * Worked examples are instruction and must never count as independent practice.
 */
export type MathsStep = {focus:string;example:{prompt:string;reasoning:string;answer:string};rubric:{support:string;developing:string;secure:string}};
export type MathsLearning = {skill:string;prerequisites:string[];steps:[MathsStep,MathsStep,MathsStep]};
const tidy=(text:string)=>text.replace(/([a-zA-Z])([0-9])/g,'$1 $2').replace(/([0-9])([a-zA-Z])/g,'$1 $2').replace(/([,;])(?=[a-zA-Z0-9])/g,'$1 ');
const s=(focus:string,prompt:string,reasoning:string,answer:string,support:string,developing:string,secure:string):MathsStep=>({focus:tidy(focus),example:{prompt:tidy(prompt),reasoning:tidy(reasoning),answer:tidy(answer)},rubric:{support:tidy(support),developing:tidy(developing),secure:tidy(secure)}});
const lesson=(skill:string,prerequisites:string[],steps:MathsLearning['steps']):MathsLearning=>({skill,prerequisites,steps});
export const mathsLearning:Record<string,MathsLearning>={
 shop:lesson('Calculate a basket cost, then change.',['Count equal groups','100 pence make £1'],[
 s('Combine prices before finding change','Buy three 20p stickers with £2. What change?','Three groups of 20p make 60p. Keep one unit: £2 is 200p. The difference is 200−60=140p.','£1.40','Needs objects to count three equal groups.','Finds 60p but needs help converting pounds or subtracting.','Explains the total and change, checks 60p+140p=200p.'),
 s('Use multiplication with decimal prices','Two notebooks cost £1.65 each. Pay £5.','165p+165p=330p. 500p−330p=170p. Working in pence keeps columns aligned.','£1.70','Adds quantities to prices rather than multiplying.','Finds £3.30; needs support with the subtraction across zero.','Checks £3.30+£1.70=£5 and records two decimal places for money.'),
 s('Organise two products and a budget','Buy three 85p cards and two 60p stamps with £5.','Cards:255p. Stamps:120p. Total375p. Change500−375=125p. A table keeps products separate.','£1.25','Cannot keep both quantities and prices connected.','Calculates products with one correction or a prompt to combine them.','Independently organises the products and verifies cost plus change equals £5.')]),
 garden:lesson('Distinguish area from perimeter and use area in a fraction problem.',['Rows and columns','Length units and square units'],[
 s('Count equal square units','A bed is 5m by 2m. Find its area.','Two rows of five one-square-metre squares give5+5=10. Area describes the covered surface.','10m²','Counts only the outside squares or uses length units.','Counts the squares correctly but needs help connecting to multiplication.','Explains 5×2=10 and uses square metres.'),
 s('Measure the whole boundary','A bed is 5m by 3m. Find its perimeter.','Walk all four sides:5+3+5+3. Opposite sides match, so2×(5+3)=16.','16m','Multiplies sides and calls the result perimeter.','Adds some sides but needs a reminder to close the boundary.','Accounts for all four sides and distinguishes metres from square metres.'),
 s('Find the remaining fraction of an area','A 4m by 5m bed has one quarter planted with herbs. How much is left?','Area20m². One quarter is20÷4=5m². The remainder is20−5=15m².','15m²','Takes a quarter of one side instead of the whole area.','Finds the quarter with support, then subtracts correctly.','Connects the remaining three quarters to3×5=15m² and checks the total.')]),
 fractions:lesson('Represent equal shares of a collection.',['Count equal objects','Share into equal groups'],[
 s('Half is one of two equal groups','Share ten buttons equally between two bowls. How many in each?','Move one button to each bowl in turn. Five in each uses all ten. One half of ten is five.','5','Makes unequal groups or counts only one group without checking.','Shares equally with objects but needs help naming one half.','Explains two equal groups and checks5+5=10.'),
 s('A quarter is one of four equal groups','Sixteen counters are shared equally into four groups. Find one quarter.','16÷4=4. Four groups of four reassemble the whole collection.','4','Uses half rather than four equal groups.','Gets four with counters, needs support relating group to fraction.','Explains the denominator as four equal groups and verifies4×4=16.'),
 s('Connect percentage to an equal share','Find25% of twenty-four beads.','Percent means out of100. 25/100=1/4, so24÷4=6. The percentage describes a proportion, not25 objects.','6','Interprets25% as25 objects regardless of the collection.','Recognises one quarter but needs help with the quantity.','Connects25%,0.25 and1/4, then finds six and checks four sixes.')]),
 data:lesson('Read counts, combine them and find a mean.',['Addition and subtraction','Equal sharing'],[
 s('Compare two counts','A survey lists finches9 and sparrows4. How many more finches?','Match one finch sighting to each sparrow sighting. Five remain:9−4=5.','5','Adds both counts when asked how many more.','Uses subtraction after a prompt to compare.','Explains the difference and checks4+5=9.'),
 s('Combine separate observations','Equal-length watches recorded3,6 and8 sightings. Find the total.','The counts are separate observations. Add each once:3+6+8=17. This is a total, not an average.','17','Omits or repeats one count.','Finds the sum with support but calls it a mean.','Sums all observations once and distinguishes total from mean.'),
 s('Share a total equally to find a mean','Four watches recorded2,8,6 and4. Find the mean.','The total is20. Share it among the four watches:20÷4=5. The mean need not be an observed count.','5 sightings per watch','Divides by a count rather than the number of watches.','Finds20 and divides with a reminder about four observations.','Explains mean as an equal-share summary and checks4×5=20.')]),
 'place-value':lesson('Use each digit’s position to read, partition and compare numbers.',['Count in tens and hundreds','Know tenths and hundredths'],[
 s('Identify a digit’s value','What is the value of6 in2,681?','The columns are thousands,hundreds,tens,ones. Six is in hundreds, so6×100=600.','600','Names the digit6 but not its value.','Uses a labelled column chart to find600.','Identifies the value and partitions2,681 as2000+600+80+1.'),
 s('Compare decimals with equal place-value columns','Order2.09,2.9 and2.19.','Write2.9 as2.90. Whole parts are equal; compare tenths next, then hundredths.','2.09,2.19,2.9','Treats more decimal digits as automatically larger.','Compares with a place-value chart and a prompt to insert zero.','Orders all three and explains why2.90 equals2.9.'),
 s('Reassemble a number with empty places','Combine30,000+500+4+0.07.','Use ten-thousands through hundredths. Put zero in missing thousands,tens and tenths positions.','30504.07','Loses place holders when joining parts.','Builds the number using labelled columns.','Writes and reads30,504.07 and explains each zero.')]),
 'decimal-scaling':lesson('Change place value by factors of ten and one hundred.',['Decimal place value','Multiplication as scaling'],[
 s('Multiply a whole number by10','Find62×10.','Six tens become six hundreds and two ones become two tens. The number becomes620.','620','Appends zero without being able to explain the changed value.','Uses a chart to shift each digit one column of greater value.','Explains each digit has ten times its previous value.'),
 s('Multiply a decimal by100','Find3.48×100.','Three ones become300, four tenths become40 and eight hundredths become8. Add them.','348','Adds100 or appends zeros after the decimal.','Moves digits correctly with a place-value chart.','Explains the scale change and checks348÷100=3.48.'),
 s('Divide by100','Find857÷100.','Eight hundreds become8 ones, five tens become5 tenths, seven ones become7 hundredths.','8.57','Divides by10 instead or loses the decimal places.','Finds8.57 with a chart.','Explains each digit now has one hundredth of its former value.')]),
 estimate:lesson('Round deliberately and use estimates to check size.',['Locate a number between multiples','Know the operation being checked'],[
 s('Round to the nearest ten','Round462 to the nearest ten.','462 lies between460 and470. It is2 from460 and8 from470, so460 is nearer.','460','Rounds every number up or checks the tens digit.','Finds bounding tens with a number line.','Uses distance to justify460.'),
 s('Estimate a total','Estimate287+512 by rounding each to the nearest hundred.','287 is nearer300;512 is nearer500. Add rounded values300+500.','800','Rounds to tens or adds before following the stated method.','Rounds one value correctly and corrects the other with help.','Follows the specified rounding method and calls800 an estimate.'),
 s('Match the operation when checking size','Could31×19 be5,890?','31 is about30 and19 about20, so the product should be about600. Exact31×19=589, making5,890 unreasonable.','No; about600','Checks using addition instead of multiplication.','Uses the matching operation after a prompt.','Chooses useful nearby numbers and rejects the tenfold error.')]),
 negative:lesson('Order signed values and move through zero.',['Order positive numbers','Count steps on a number line'],[
 s('Compare temperatures','Which is colder:−6°C or−2°C?','−6 lies farther left on the temperature line. It is six degrees below zero, not just a larger digit.','−6°C','Chooses−2 because2 is smaller than6.','Orders the values on a supplied number line.','Explains colder using signed position rather than digit size.'),
 s('Count a rise through zero','Temperature rises from−2°C to5°C. Find the rise.','Two steps reach0, then five more reach5. The increase is2+5=7 degrees.','7 degrees','Subtracts2 from5 instead of counting across zero.','Uses a number line to find seven.','Explains both parts of the rise and checks−2+7=5.'),
 s('Model a downward movement','A lift goes down6 floors from floor1. Include floor0.','Count1→0→−1→−2→−3→−4→−5. Six downward moves end at−5.','Floor−5','Skips floor0 or counts the starting floor as a move.','Tracks moves accurately using marked floors.','Explains1−6=−5 and checks the reverse journey.')]),
 sequences:lesson('Recognise a stated pattern, then devise and test rules.',['Addition and multiplication','Keep a table of terms'],[
 s('Continue a constant difference','Continue9,14,19,24 using the same step.','Each difference is5. Continue with24+5, then add5 again if needed.','29','Guesses without comparing successive differences.','Finds the difference with prompts.','States add5 and checks every displayed step.'),
 s('Continue a multiplicative pattern','Continue5,15,45 using the same multiplier.','15÷5=3 and45÷15=3. Multiply45 by3 for the next term.','135','Adds10 repeatedly despite the changing difference.','Recognises ×3 with help using division.','Explains the multiplier and checks prior terms.'),
 s('Make and test alternating rules','Start at2; alternate add3 then double. Give five terms.','The starting2 is the first term. Add3→5,double→10,add3→13,double→26. Another starting value would make a different sequence.','2,5,10,13,26','Applies both rules at every step or loses their order.','Keeps the order using a labelled two-rule card.','Generates terms and explains which rule follows each one.')]),
 factors:lesson('Investigate divisibility, prime numbers and powers.',['Multiplication and division','Difference between a factor and a multiple'],[
 s('List positive factors without duplication','List all factors of18.','Pair divisors:1×18,2×9,3×6. The next candidates give no new pairs.','1,2,3,6,9,18','Lists multiples instead of numbers dividing18.','Finds pairs but repeats or misses a factor.','Lists six factors systematically and explains why they divide18.'),
 s('Test primality','Is29 prime?','Try possible divisors up to5:2,3 and5 do not divide29. Any larger factor pair would have a partner below the square root. Only1 and29 remain.','Yes','Calls odd numbers prime without testing.','Tests small divisors with guidance.','Justifies two positive factors; uses a factor-pair search rather than oddness alone.'),
 s('Distinguish square from cube','Find3 cubed minus4 squared.','3³=3×3×3=27. 4²=4×4=16. The difference is11.','11','Multiplies3 by3 for cubing or multiplies a base by its power.','Builds repeated products with support.','Explains the powers and calculates27−16 independently.')]),
 machines:lesson('Follow ordered rules and undo them in reverse order.',['Four operations','Inverse operations'],[
 s('Apply one machine rule','A machine adds9. Input4 enters.','Follow the arrow once:4+9=13. The rule changes the input to an output.','13','Treats the rule number as an output.','Applies the rule using an input-output table.','Distinguishes input,rule and output and checks the calculation.'),
 s('Follow two ordered rules','A machine triples then adds2. Input5 enters.','First5×3=15, then15+2=17. Adding2 before multiplying would make a different rule.','17','Reverses or combines the order incorrectly.','Follows a two-arrow diagram with support.','Explains why the ordered rule gives17 rather than21.'),
 s('Work backwards','A machine doubles then subtracts4. Output18 appears. Find the input.','Undo subtract4 by adding4:22. Then undo doubling by dividing2:11.','11','Undoes in the original order.','Uses reversed arrows to find11.','Checks11×2−4=18 and explains reverse order.')]),
 unknown:lesson('Keep equality true when finding an unknown.',['Equality means same value','Inverse operations'],[
 s('Undo an addition','x+6=17. Find x.','Subtract6 from17. Eleven plus6 gives17, so both sides match.','11','Treats the letter as a label rather than a number.','Uses counters or a bar to find the missing part.','Finds11 and substitutes it to check equality.'),
 s('Undo a multiplication','5×y=40. Find y.','Five equal groups total40, so each has40÷5=8.','8','Subtracts5 instead of dividing.','Shares40 into five groups with help.','Connects5×8=40 and40÷5=8.'),
 s('Undo two operations','4×z+3=31. Find z.','Remove the added3 first:28. Four equal groups total28, giving7 per group.','7','Divides31 before removing3.','Works backwards with a two-stage diagram.','Explains and checks4×7+3=31.')]),
 mental:lesson('Adjust to friendly numbers without changing the answer.',['Number bonds','Decimal hundredths'],[
 s('Add a near-ten number','Calculate46+19 mentally.','Add20 to get66. This added one too many, so subtract1.','65','Adds20 but forgets to compensate.','Uses a written adjustment to reach65.','Explains why subtraction corrects the added extra one.'),
 s('Subtract a near-hundred number','Calculate305−99 mentally.','Subtract100 to get205. This took one too many away, so add1 back.','206','Subtracts another1 after subtracting100.','Finds the direction of compensation with support.','Justifies adding1 back and checks206+99=305.'),
 s('Compensate by a hundredth','Calculate6.35+1.99.','Add2 to make8.35, then remove0.01 because1.99 is0.01 less than2.','8.34','Adjusts by0.1 or uses the wrong direction.','Uses a hundredths chart to identify0.01.','Explains the amount and direction of compensation.')]),
 tables:lesson('Build multiplication facts and connect them to division.',['Equal groups','Skip counting without a timer'],[
 s('Build familiar2,5 and10 groups','Six bags hold2 shells each. How many?','Count2,4,6,8,10,12. Six groups of2 make12; doubling6 is another route.','12','Counts bags and shells as one collection.','Skip-counts accurately with objects.','Explains6×2=12 and can reverse to12÷2=6.'),
 s('Derive facts from known facts','Find6×7 using5×7.','Five sevens are35. One more seven makes42, so six sevens are42.','42','Cannot identify how one extra group changes the total.','Adds7 after a prompt or an array.','Derives the fact and checks by another grouping; speed is not required.'),
 s('Use inverse facts across all tables','Forty-eight counters fill8 equal groups. How many each?','Find the missing factor in8×?=48. Eight sixes make48, so each group has6.','6','Confuses number of groups with total objects.','Finds the matching multiplication with an array.','Explains48÷8=6 and48÷6=8 as related but different groupings.')]),
 operations:lesson('Respect brackets and use decimals in problems.',['Four operations','Place value to hundredths'],[
 s('Complete a bracketed group first','Find(18+6)÷3.','The brackets group18+6 as24. Divide the whole24 by3.','8','Divides6 before completing the bracket.','Marks the bracketed result with guidance.','Explains why(18+6)÷3 differs from18+6÷3.'),
 s('Multiply a decimal by a whole number','Four lengths are0.75m each. Find their total.','75 hundredths four times is300 hundredths. That is3 whole metres.','3m','Loses the place value of75 hundredths.','Adds four copies correctly with aligned decimals.','Connects repeated addition to multiplication and estimates a result below4m.'),
 s('Divide then change each equal share','Share8.4L into3 equal jugs, then remove0.6L from each.','Each initially has8.4÷3=2.8L. One jug then has2.8−0.6=2.2L.','2.2L each','Subtracts0.6 from the total instead of each share.','Separates the two steps after a diagram prompt.','Explains the unit at each step and verifies the remaining total6.6L.')]),
 'fraction-links':lesson('Connect equal parts, fractions of quantities and hundredths.',['Equal-sized parts','Division and multiplication'],[
 s('Find an equivalent fraction','Why is3/6 equal to1/2?','Split six equal parts into two equal groups. Three parts form one group, so3 of6 is half. Divide both numerator and denominator by3.','3/6=1/2','Changes only the denominator.','Uses a six-part strip to see the equivalence.','Explains equal proportions using a model and matching division.'),
 s('Find several equal parts of a quantity','Find three quarters of28.','One quarter is28÷4=7. Three of those quarters make3×7=21.','21','Divides by3 or stops after finding one quarter.','Completes the two steps with a bar model.','Explains why the denominator divides the whole and numerator selects parts.'),
 s('Connect fifths to hundredths','Express2/5 as a decimal and percentage.','Multiply numerator and denominator by20:2/5=40/100. Forty hundredths is0.40 and40%.','0.4 and40%','Confuses2/5 with0.2 or2.5.','Builds equivalent hundredths using a grid.','Links all representations and distinguishes40% from0.4%.')]),
 budget:lesson('Make choices within limits and compare costs fairly.',['Money totals','Division into equal units'],[
 s('Leave room for all needs','A pretend snack budget is£7. Fruit costs£2 and sandwiches£3. Can a£1 drink fit?','The food total is£5. Adding the drink makes£6, leaving£1. Needs can be met without spending everything.','Yes;£1 remains','Chooses items without keeping a total.','Finds a total after adult prompts.','Explains a choice and shows the total stays within budget.'),
 s('Compare a common unit','Five crayons cost£1.50; four cost£1.40. Which is cheaper per crayon?','Use pence:150÷5=30p,140÷4=35p. Compare one crayon with one crayon, not just pack totals.','Five-pack:30p each','Chooses the lower pack price without considering quantity.','Computes one unit price and needs help with the other.','Justifies the unit comparison and considers whether all crayons are needed.'),
 s('Plan saving over weeks','A puzzle costs£18. You have£8 and save£2 weekly.','The shortfall is£10. Five lots of£2 fill it. Check a running total8,10,12,14,16,18.','5 weeks','Divides the whole price rather than the remaining need.','Finds the shortfall but needs a weekly table.','Plans the time and explains that changing weekly savings changes the plan.')]),
 currency:lesson('Name currency and use an explicitly stated practice rate.',['Money symbols','Equal groups and inverse operations'],[
 s('Identify the unit before calculating','A label reads€9 and another£9. Do these name the same currency?','The numerals match, but the symbols name different units: euros and pounds. A rate is needed to compare their monetary value.','No;euros and pounds','Treats the symbol as decoration.','Names either euro or pound with a prompt.','Names both and explains why equal numerals do not establish equal value.'),
 s('Convert with a given invented rate','In this practice only,£1 buys€1.10. What does£4 buy with no fee?','There are four one-pound groups. Four lots of€1.10 total€4.40. This is not a live rate.','€4.40','Adds1.10 to4 or switches the currency direction.','Uses an equal-groups table to calculate.','Explains the direction and labels the result in euros.'),
 s('Reverse a given conversion','In this practice only,£1 buys€1.50. How many pounds buy€9, ignoring fees?','Count how many€1.50 groups fit into€9:6. Each group costs£1.','£6','Multiplies the euro amount by the rate.','Finds groups using repeated addition.','Explains division and verifies£6×1.50=€9.')]),
 'measure-estimate':lesson('Estimate, select a tool and report sensible precision.',['Understand length,mass,capacity and time','Read simple scales'],[
 s('Estimate before looking at a ruler','You estimate a card is10cm; a ruler shows12cm. What did you learn?','The estimate is2cm short. Estimation is a sensible prediction; the later measurement improves the information. Use the zero mark.','The card is about12cm;estimate2cm low','Reads from the ruler edge rather than zero.','Measures accurately after help aligning the card.','Explains the estimate–measurement difference without treating estimation as failure.'),
 s('Match a tool and unit to a quantity','Choose tools for juice capacity,a potato’s mass and a short song’s duration.','A measuring jug uses mL,a scale uses g,and a clock uses seconds or minutes. Each tool answers a different question.','Jug:mL;scale:g;clock:seconds','Confuses mass with capacity or selects an unrelated tool.','Chooses tools with prompts but units need correction.','Selects tools and sensible units,estimates first and records readings.'),
 s('Reason about intervals and accuracy','A ruler is marked every millimetre. One reading is52mm and another53mm. Should you report52.437mm?','The tool and repeated readings do not justify so many digits. Record about52–53mm and explain the small variation in alignment.','No;about52–53mm','Assumes more digits always mean a better measurement.','Notices differing readings with support.','Connects scale resolution and repeat variation to sensible reporting.')]),
 units:lesson('Convert to a common unit before calculating.',['Place value and ×10,×100,×1000','Metric unit relationships'],[
 s('Use100 centimetres per metre','Convert3m to centimetres.','Each metre contains100cm. Three equal groups of100 give300.','300cm','Uses10 rather than100cm per metre.','Converts using three labelled metre strips.','Explains3×100 and keeps the correct unit.'),
 s('Use1000 millilitres per litre','Convert2.35L to millilitres.','2L=2000mL and0.35L=350mL. Add to make2350mL.','2350mL','Treats decimal digits as whole millilitres.','Partitions whole and fractional litres with help.','Explains the conversion and checks the result is between2000 and3000mL.'),
 s('Subtract measures in one unit','A3kg bag loses850g. What mass remains in grams?','Convert3kg to3000g,then3000−850=2150g. Subtracting3−850 would mix units.','2150g','Subtracts numbers expressed in unlike units.','Converts with a prompt,then subtracts.','Shows a common unit and checks2150+850=3000g.')]),
 volume:lesson('Build volume from equal cubes and layers.',['Area of a rectangle','Cubic units differ from square units'],[
 s('Count filled cubic units','Five unit cubes exactly fill a one-row,one-layer box. What volume?','Each cube occupies one cubic unit. Five such cubes occupy five cubic units,with no gaps counted.','5 cubic units','Counts visible faces rather than cubes.','Counts five cubes after handling a model.','Distinguishes volume from surface area and states cubic units.'),
 s('Count cubes in layers','A cuboid is5cm long,2cm wide and3cm high. Find its volume.','Each layer has5×2=10 one-cubic-centimetre cubes. Three layers give30.','30cm³','Adds the three edge lengths.','Finds a layer but needs help counting layers.','Explains length×width×height in cubic units.'),
 s('Infer the number of layers','A cuboid has volume48cm³ and base4cm by3cm. Find height.','The base area is12cm². Each1cm-high layer occupies12cm³. 48÷12=4 layers.','4cm','Divides by only one base edge.','Finds base area with support.','Explains the inverse volume calculation and checks4×3×4=48.')]),
 scale:lesson('Use one consistent relationship between drawing and real lengths.',['Multiplication and division','Centimetres and metres'],[
 s('Scale a drawing length up','At1cm to3m,a path is5cm on a drawing. Find its real length.','Every centimetre stands for3m. Five equal scale units make15m.','15m','Adds the scale numbers or labels15cm.','Uses a ratio table with support.','Explains5×3 and labels the real length in metres.'),
 s('Scale a real length down','At1cm to4m,how long should a20m wall be on the drawing?','Twenty metres contains five groups of4m. Each group becomes1cm.','5cm','Multiplies when finding the smaller drawing length.','Counts groups with support.','Explains division and checks5cm represents20m.'),
 s('Keep one scale across a plan','Draw a15m by9m space at1cm to3m. Include a6m path.','Divide every real length by3:5cm by3cm,and a2cm path. Label the scale and symbols so a reader can interpret it.','5cm×3cm;path2cm','Changes the scale between objects.','Gets dimensions but needs help with labels or a key.','Uses consistent lengths,labels and a clear symbol key.')]),
 time:lesson('Read clock positions,convert formats and calculate duration.',['Count minutes in fives','60 minutes in one hour'],[
 s('Read a half-hour position','Minute hand points to6;hour hand is halfway between8 and9. What time?','The minute hand has travelled30 minutes. The hour hand is still within the eighth hour.','8:30','Reads the minute-hand number as the hour.','Finds30 minutes after counting round the clock.','Explains both hands,including the hour hand’s intermediate position.'),
 s('Convert afternoon time','Express20:15 in12-hour form.','20 hours is12+8,so the time is8:15pm. The minute part does not change.','8:15pm','Changes minutes or omits am/pm.','Subtracts12 with support.','Converts both ways and explains why pm is required.'),
 s('Cross an hour boundary','A journey starts11:42 and ends12:18. How long?','18 minutes reach12:00,then18 more reach12:18. Add36 minutes;clock minutes use60,not100.','36 minutes','Subtracts times as ordinary decimals.','Uses a timeline to bridge12:00.','Explains both intervals and checks the end time.')]),
 shapes:lesson('Use properties,not orientation or appearance,to classify shapes.',['Straight sides and corners','Equal lengths and right angles'],[
 s('Count boundary sides','A closed shape has six straight sides. What is it called?','Trace the complete boundary once. A polygon with six sides is a hexagon,whether it is regular or irregular.','Hexagon','Counts internal lines or corners inconsistently.','Traces sides with a starting mark.','Names a six-sided polygon in different orientations.'),
 s('Identify necessary properties','Does rotating a rectangle remove its right angles?','Rotation changes its position,not its angles or side lengths. Four right angles remain; a square is also a rectangle.','No','Classifies by upright appearance only.','Recognises the rotated example using a corner tester.','Explains invariant properties rather than visual orientation.'),
 s('Distinguish regularity from congruence','A square has4cm sides. Is a square with5cm sides congruent to it?','Both are regular:equal sides and angles within each shape. Congruence also requires matching size;4cm and5cm do not match.','No;both regular,but different sizes','Uses same shape alone as a test for congruence.','Finds the size difference with measurement.','Explains regularity and congruence as different properties.')]),
 symmetry:lesson('Test reflection,rotation and tiling with matching parts.',['Compare distances','Quarter and half turns'],[
 s('Use folding to test a reflection line','A non-square rectangle is folded through the midpoints of its short sides. Do the halves match?','This line runs along the middle of the longer direction. Folding overlays corresponding corners and edges. The two halves coincide.','Yes;it is a line of symmetry','Assumes any line through the centre is a reflection line.','Checks overlay using paper with help.','Explains matching points at equal distances from the line.'),
 s('Reflect by perpendicular distance','A point is2 squares left of a vertical mirror line. Where is its image?','Keep the same height and move2 squares right of the line. The line is midway between original and image.','2 squares right at the same height','Moves the point along the line rather than across it.','Counts perpendicular squares with support.','Explains equal distances and checks by folding or overlay.'),
 s('Separate turning symmetry from tiling','How many times does a non-square rectangle match itself in a full turn? Can rectangles tile?','It matches at180° and360°,so order2. Copies can also cover a plane edge to edge without gaps. Tiling is a separate test.','Order2;yes,rectangles tessellate','Counts the starting position and360° twice.','Tests turns with a tracing and avoids double-counting after a reminder.','Justifies both turning order and a gap-free tiling arrangement.')]),
 solids:lesson('Describe solids using faces,edges and vertices.',['2-D polygons','Difference between a flat face and a solid'],[
 s('Connect a solid to its faces','A square-based pyramid has one square base and four triangular faces. How many faces?','Count the base once and each triangle once:1+4=5. Faces are flat surfaces,not edge lines.','5 faces','Confuses faces with corners.','Handles a model and labels each face.','Describes one square plus four triangles and totals five.'),
 s('Count vertices systematically','A triangular prism has two triangular ends. How many vertices?','Each triangle has three corners. Join corresponding corners with rectangular faces;there are3+3 distinct vertices.','6 vertices','Counts a shared vertex repeatedly.','Marks corners on a model with support.','Explains six vertices and distinguishes them from the nine edges.'),
 s('Check whether a net can fold','Why do six squares in a straight row fail to make a cube net?','Folding successive edges wraps the row around;faces overlap before forming a closed top and bottom. Having six squares is necessary but not sufficient.','It overlaps and does not close into six distinct faces','Assumes any six connected squares form a cube.','Tests folding with help and notices overlap.','Explains the failed closure and compares with a working cross arrangement.')]),
 directions:lesson('Connect compass turns to a sequence of drawing commands.',['Right angle','Read a sequence in order'],[
 s('Turn anticlockwise','Face east and turn one quarter turn anticlockwise. Where now?','From east,turn against clock motion through90° to north. The turn is a change in direction,not a forward movement.','North','Confuses clockwise and anticlockwise.','Acts out a quarter turn using a compass card.','Explains the direction and distinguishes turning from moving.'),
 s('Name intermediate compass points','Which direction is halfway between north and west?','The eight points divide a full turn equally. The intermediate point combines north and west.','North-west','Uses a direction in the opposite quadrant.','Finds the point on a labelled compass.','Names the point and places it between its two neighbours.'),
 s('Trace commands before running them','Start facing up:FORWARD2,RIGHT90,FORWARD5,RIGHT90,FORWARD2,RIGHT90,FORWARD5. What path?','The sides alternate2 and5. Right-angle turns make opposite sides parallel;the final movement reaches the start.','A2-by-5 rectangle','Treats turn angles as forward distances.','Traces commands with a pointer and spots a wrong turn.','Predicts a closed rectangle and explains how changing a length changes the path.')]),
 angles:lesson('Classify turns and reason about angle totals.',['Right angle and full turn','Use a protractor baseline'],[
 s('Compare with known benchmarks','Classify an angle of135°.','135° is more than90° and less than180°,so it is obtuse. The marked region determines which angle is meant.','Obtuse','Calls every non-right angle acute.','Uses right/straight angle benchmarks with support.','Explains the bounds and identifies the intended region.'),
 s('Use the triangle interior sum','Triangle angles are35° and85°. Find the third.','Known angles total120°. All three interior angles total180°,leaving60°.','60°','Subtracts from360° rather than180°.','Recalls the triangle total with a diagram.','Explains35+85+60=180° and checks plausibility.'),
 s('Identify the larger reflex region','Two rays make an80° smaller angle. Find the reflex angle around the other way.','A full turn is360°. Remove the80° smaller part:360−80=280°. Mark the larger region explicitly.','280°','Labels the smaller region with a reflex measure.','Finds280° with a full-turn diagram.','Connects both regions and can draw/measure the intended turn.')]),
 coordinates:lesson('Use ordered pairs on equally scaled axes.',['Horizontal and vertical','Origin and positive directions'],[
 s('Read across before up','How do you reach(2,5) from(0,0)?','The first coordinate is horizontal:two right. The second is vertical:five up. Order matters.','2 right,5 up','Swaps the two coordinates.','Follows arrows on labelled axes.','Explains the order and distinguishes(2,5) from(5,2).'),
 s('Plot and close a polygon','Plot(2,1),(6,1),(6,4),(2,4),then return to the first. Name and size it.','Horizontal sides span6−2=4 units;vertical sides span4−1=3. Corners are right angles.','A4-by-3 rectangle','Joins points out of order or does not close the shape.','Plots correctly with a labelled grid.','Explains side lengths using coordinate differences.'),
 s('Translate every point consistently','Move(2,3),(5,3),(2,6) one unit right and two down.','Add1 to each x;subtract2 from each y. Use the same change for every vertex.','(3,1),(6,1),(3,4)','Moves only one coordinate or one vertex.','Uses arrows for each vertex with help.','Explains that translation preserves shape,size and relative positions.')]),
 'collect-data':lesson('Choose a fair question,record consistently and acknowledge limits.',['Counting and categories','One observation per agreed record'],[
 s('Make categories that can be used consistently','Count toy cars,blocks and balls. Where should a ball-shaped block go?','Decide the category rule before counting,then use it consistently. For example,classify by toy type rather than shape and record each object once.','Agree a non-overlapping rule before counting','Counts one object in two categories.','Uses an adult-agreed rule with reminders.','Explains the rule and checks category totals against all objects.'),
 s('Repeat observations fairly','Measure classroom temperature at9am on four days. Why keep the time the same?','A fixed time reduces one source of variation. Record date,time,temperature and units. It does not remove all weather or heating differences.','It makes comparisons more consistent','Changes observation times without recording them.','Keeps a record using a supplied sheet.','Explains a fair comparison and notes remaining limitations.'),
 s('Separate a sample from a whole population','Ten club members prefer apples. Does that prove all pupils prefer apples?','Club members may differ from other pupils. Record the question and who could respond without collecting names;explain whose views are missing.','No;the sample may not represent all pupils','Generalises a small group to everyone.','Recognises missing views after a prompt.','Explains a sample limitation and suggests a fairer collection plan.')]),
 frequency:lesson('Organise counts and interpret frequency groups.',['Tally groups of five','Add selected categories'],[
 s('Convert grouped tallies to a count','A tally has three complete groups of five and two extra marks. Find frequency.','Three groups of five make15;the extra two make17. Frequency means how many observations are in the category.','17','Counts groups as single observations.','Expands each group of five with support.','Explains3×5+2 and uses frequency correctly.'),
 s('Combine exclusive categories','Each child picks one fruit. Pear4,apple7,plum5. How many choose apple or plum?','Because each child appears once,add the two selected counts:7+5=12. Do not include pear.','12','Adds all categories or overlooks possible double-counting.','Identifies the requested categories with a prompt.','Explains why exclusivity allows addition of7 and5.'),
 s('Interpret interval boundaries','Whole-minute reading times:0–9 has3 children,10–19 has6,20–29 has4. How many read at least10 minutes?','Select the last two groups;6+4=10. Whole-minute recording ensures the labelled groups cover every possible recorded value.','10','Includes the first group or excludes10 minutes.','Selects intervals after marking the boundary.','Explains inclusive lower bounds and the loss of individual values inside groups.')]),
 'data-tools':lesson('Keep records intact and use calculations and conditions.',['Rows and columns','Safe fictional data only'],[
 s('Structure a data table','Record Willow4,Pine7 andElm3 in a spreadsheet.','Use headings Tree and Count. Each row is one record;the tree name and its count stay together. Save a named file for your own use.','Two columns and three data rows','Mixes several records into one cell without structure.','Enters data using a supplied layout.','Creates clear headings and checks every record against the source.'),
 s('Calculate and sort without breaking records','Using Willow4,Pine7,Elm3,find a total and sort ascending.','4+7+3=14. Sort complete rows,not the Count column alone:Elm3,Willow4,Pine7. A formula should update if a count changes.','Total14;Elm3,Willow4,Pine7','Sorts counts away from their names.','Calculates14 but needs help selecting whole records.','Uses a working formula and verifies label-value relationships after sorting.'),
 s('Apply two conditions together','Records:Aster25cm/sun,Fern30cm/shade,Rose15cm/sun. Select height≥20cm AND needs sun.','Aster meets both. Fern fails the sun condition;Rose fails the height condition. AND means both tests must pass.','Aster only','Treats AND as either condition.','Checks two conditions separately with a table.','Explains why each included or excluded record passes or fails.')]),
 averages:lesson('Distinguish spread from an equal-share average.',['Order numbers','Add and divide whole numbers'],[
 s('Find the range','Find the range of2,8,5,11.','The largest is11 and the smallest2. Their distance is11−2=9. Order of the original list does not matter.','9','Uses number of values or subtracts neighbouring entries.','Identifies extremes with a sorted list.','Explains the range as spread from least to greatest.'),
 s('Calculate and interpret a mean','Find the mean of3,9 and12.','The total24 shared among three values gives8. It summarises the data but need not appear in the list.','8','Divides by the largest value instead of three.','Finds the total and needs help choosing the divisor.','Explains equal sharing and checks8×3=24.'),
 s('Use a mean to recover a missing value','Four values have mean9. Three are7,8 and10. Find the fourth.','Four values total4×9=36. Known values total25. The missing value is36−25=11.','11','Treats the mean as the total.','Finds total36 after a prompt.','Uses the inverse relationship and verifies the completed mean.')]),
 chance:lesson('Describe likelihood under fair random selection.',['Compare counts','Understand equally likely outcomes'],[
 s('Distinguish impossible and certain','A bag holds only green beads. Could a fair draw give a red bead?','No bead is red,so red has no possible outcome. Green is certain in this stated model.','Red impossible;green certain','Treats impossible as merely unlikely.','Uses the bag contents to choose a word.','Explains certain and impossible by the available outcomes.'),
 s('Recognise an even chance','A well-mixed bag has three blue and three orange identical counters. Is blue an even chance?','Each counter is equally likely. Three of six outcomes are blue:half. That does not guarantee every pair of draws contains one blue.','Yes;3/6=1/2','Predicts a guaranteed alternating pattern.','Recognises equal counts with support.','Explains evens while acknowledging uncertainty for a single draw.'),
 s('Compare with evens','A fair bag has five red,three yellow andtwo blue counters. Is yellow more or less likely than evens?','Yellow has3 of10 outcomes;evens would be5 of10. Three is below five,so yellow is less likely than evens.','Less likely than evens','Confuses most likely with certain.','Compares3/10 to5/10 using objects.','Orders the colours and compares each probability with half.')]),
 reasoning:lesson('Organise a search and justify a general conclusion.',['Explain a method','Check with objects or a diagram'],[
 s('List possibilities systematically','Split eight counters into two groups;reversed pairs count as the same.','Start0+8,then1+7,2+6,3+5,4+4. The next pair reverses3+5,so stop. State the convention before counting.','Five different unordered pairs','Lists random examples and cannot check completeness.','Uses a table but needs help deciding when to stop.','Explains a systematic list and why no permitted pair is missing.'),
 s('Compare feasible plans','A group needs22 seats. Tables seat4 or6. Compare4 six-seat tables with3 six-seat and1 four-seat table.','The first gives24 seats with2 spare. The second gives18+4=22 with none spare. Both fit,but one uses the exact number of seats.','Second plan has fewer empty seats','Compares table counts without considering capacities.','Finds both totals with a prompt.','Explains feasibility and the chosen comparison criterion.'),
 s('Explain a general statement','Why does adding two even whole numbers give an even number?','Each even number can be arranged entirely in pairs. Combining both collections leaves only pairs,with no single object. Examples illustrate this but the pairing argument applies generally.','The combined collection still consists entirely of pairs','Treats a few examples as proof of always.','Builds paired examples with support.','Gives a general paired-object argument and distinguishes it from testing cases.')]),
};

// Finite, deterministic banks. Bank items are additional practice, not worked examples.
const num=(prompt:string,answer:number,hint:string,explanation:string):Task=>({prompt:tidy(prompt),answer:Math.round(answer*100)/100,hint:tidy(hint),explanation:tidy(explanation)});
const choice=(prompt:string,answer:string,wrong:[string,string],hint:string,explanation:string):Task=>({prompt:tidy(prompt),answer:tidy(answer),options:[answer,...wrong].map(tidy),hint:tidy(hint),explanation:tidy(explanation)});
export const mathsPractice:Record<string,Task[]>={};
const add=(key:string,task:Task)=>{(mathsPractice[key]??=[]).push(task);};
const money=(pence:number)=>(pence/100).toFixed(2);
for(let i=0;i<4;i++){
 const a=i+2,b=i+3;
 for(let level=0;level<3;level++){
  const q=level+2, second=level===2?2:1,price=level===0?30+i*10:115+i*20,drink=level===0?80:95+i*10,budget=level===0?500:1500;
  const cost=q*price+second*drink;
  add(`shop:${level}`,{...num(`Buy ${q} card${q===1?'':'s'} and ${second} drink${second===1?'':'s'}. You have £${money(budget)}. What change in pounds?`,(budget-cost)/100,'Multiply each price by its quantity, add the costs, then subtract from the wallet.',`${q} × ${price}p + ${second} × ${drink}p = ${cost}p. ${budget}p − ${cost}p = ${budget-cost}p, or £${money(budget-cost)}.`),budget,items:[{name:'Card',price,quantity:q},{name:'Drink',price:drink,quantity:second},{name:'Badge',price:65,quantity:0}]});
 }
 const w=i+2,h=3;add('garden:0',{...num(`Build a ${w}m by ${h}m rectangle. What is its area in m²?`,w*h,'Count equal square units in rows.',`${w} × ${h} = ${w*h}m².`),width:w,height:h});
 add('garden:1',{...num(`Build a ${w}m by ${h+1}m rectangle. What is its perimeter in metres?`,2*(w+h+1),'Include both pairs of opposite sides.',`2 × (${w} + ${h+1}) = ${2*(w+h+1)}m.`),width:w,height:h+1});
 add('garden:2',{...num(`Build a ${w}m by 4m rectangle. One quarter is a pond. What area remains in m²?`,w*3,'Find all the area, then remove one quarter.',`Area ${w*4}m²; pond ${w}m²; remaining ${w*3}m².`),width:w,height:4});
 for(let level=0;level<3;level++){const parts=level===0?2:4,total=(level===0?[4,6,10,12]:level===1?[8,16,20,24]:[8,12,16,24])[i];add(`fractions:${level}`,{...num(`Tap ${level===0?'half':level===1?'one quarter':'25%'} of the ${total} equal tiles. How many is that?`,total/parts,`Share the whole into ${parts} equal groups.`,`${total} ÷ ${parts} = ${total/parts}. ${level===2?'25% is one quarter.':''}`),total,parts});}
 const bars=[{label:'Watch 1',value:a},{label:'Watch 2',value:a+2},{label:'Watch 3',value:a+4}];
 add('data:0',{...num('These are pretend bird counts. How many more blackbirds than wrens?',b,'Compare the two counts by subtraction.',`${a+b} − ${a} = ${b}.`),bars:[{label:'Blackbirds',value:a+b},{label:'Wrens',value:a},{label:'Robins',value:a+1}]});
 add('data:1',{...num('These equal-length watches recorded bird sightings. What is the total?',3*a+6,'Add each watch count once.',`${a} + ${a+2} + ${a+4} = ${3*a+6}.`),bars});
 add('data:2',{...num('These equal-length watches recorded bird sightings. What is the mean per watch?',a+2,'Add the counts, then divide by three watches.',`Total ${3*a+6}; ${3*a+6} ÷ 3 = ${a+2}.`),bars});
 const digit=i+3,whole=2000+digit*100+41;add('place-value:0',num(`What is the value of ${digit} in ${whole}?`,digit*100,'Identify the hundreds column.',`${digit} hundreds is ${digit*100}.`));
 const decimals=[`${a}.03`,`${a}.3`,`${a}.33`];add('place-value:1',choice(`Which list is in ascending order?`,decimals.join(', '),[[decimals[1],decimals[0],decimals[2]].join(', '),[...decimals].reverse().join(', ')],'Write tenths with a final zero to compare hundredths.',`${a}.03 < ${a}.30 < ${a}.33.`));
 add('place-value:2',num(`Combine ${a*10000} + ${b*100} + 7 + 0.08. Enter no commas.`,a*10000+b*100+7.08,'Keep zero placeholders for the absent places.',`The sum is ${(a*10000+b*100+7.08).toFixed(2)}.`));
 add('decimal-scaling:0',num(`Calculate ${21+i*14} × 10.`,(21+i*14)*10,'Each digit takes a place ten times as valuable.',`${21+i*14} tens = ${(21+i*14)*10}.`));
 const hundredths=123+i*111;add('decimal-scaling:1',num(`Calculate ${(hundredths/100).toFixed(2)} × 100.`,hundredths,'A hundredth becomes a whole one.',`${hundredths} hundredths × 100 = ${hundredths}.`));
 const dividend=321+i*117;add('decimal-scaling:2',num(`Calculate ${dividend} ÷ 100.`,dividend/100,'Each digit has one hundredth of its previous value.',`${dividend} ÷ 100 = ${(dividend/100).toFixed(2)}.`));
 const v=213+i*21;add('estimate:0',num(`Round ${v} to the nearest ten.`,Math.round(v/10)*10,'Find the two neighbouring multiples of ten.',`${v} is nearer ${Math.round(v/10)*10}.`));
 const first=183+i*100,other=412+i*100;add('estimate:1',num(`Estimate ${first} + ${other} by rounding each to the nearest hundred.`,600+i*200,'Round each number before adding.',`${200+i*100} + ${400+i*100} = ${600+i*200}.`));
 const near=29+i*10,near2=21;add('estimate:2',choice(`Which multiplication estimate checks ${near} × ${near2}?`,`${near+1} × 20 = ${(near+1)*20}`,[`${near+1} + 20 = ${near+21}`,`${near+1} × 200 = ${(near+1)*200}`],'Keep the operation and round to nearby tens.',`${near} is close to ${near+1} and21 close to20,so the product is near ${(near+1)*20}.`));
 add('negative:0',choice(`Which temperature is coldest?`,`−${a+2}°C`,[`−${a}°C`,`${a}°C`],'Further left on a temperature line means colder.',`−${a+2} is less than −${a},which is less than ${a}.`));
 add('negative:1',num(`A temperature rises from −${a}°C to ${b}°C. What is the rise in degrees?`,a+b,'Count up to zero,then beyond it.',`${a} + ${b} = ${a+b} degrees.`));
 add('negative:2',choice(`A lift starts at floor ${a+1} and goes down ${a+b+1} floors,including floor zero. Where is it?`,`Floor −${b}`,[`Floor ${b}`,`Floor −${a+b+1}`],'Count movements,including the move to floor zero.',`${a+1} − ${a+b+1} = −${b}.`));
 const step=i+3;add('sequences:0',num(`Continue with the same step: ${a}, ${a+step}, ${a+2*step}, ${a+3*step}, …`,a+4*step,'Compare neighbouring terms.',`Add ${step} each time; next is ${a+4*step}.`));
 add('sequences:1',num(`Continue by doubling each time: ${a+7}, ${(a+7)*2}, ${(a+7)*4}, …`,(a+7)*8,'Multiply the last term by2.',`${(a+7)*4} × 2 = ${(a+7)*8}.`));
 const factorsOf=[16,20,24,30][i],divisors=Array.from({length:factorsOf},(_,j)=>j+1).filter(d=>factorsOf%d===0);add('factors:0',num(`How many different positive whole-number factors does ${factorsOf} have?`,divisors.length,'List factor pairs without repeating a factor.',`Factors:${divisors.join(', ')}; ${divisors.length} in total.`));
 const prime=[11,13,17,19][i];add('factors:1',choice('Which of these numbers is prime?',String(prime),[String(12+i*6),String(15+i*10)],'A prime has exactly two positive factors.',`${prime} has only1 and itself. The alternatives are composite.`));
 add('factors:2',num(`Calculate ${a+1} cubed minus ${a} squared.`,(a+1)**3-a*a,'Write the repeated multiplications before subtracting.',`${(a+1)**3} − ${a*a} = ${(a+1)**3-a*a}.`));
 add('machines:0',num(`A machine adds ${a+4}. Input ${b+3} enters. What is the output?`,a+b+7,'Apply the stated rule once.',`${b+3} + ${a+4} = ${a+b+7}.`));
 add('machines:1',num(`A machine doubles then adds ${a}. Input ${b+1} enters. What is the output?`,2*(b+1)+a,'Multiply first,then add.',`${b+1} × 2 + ${a} = ${2*(b+1)+a}.`));
 add('machines:2',num(`A machine multiplies by3 then subtracts ${a}. Its output is ${3*(b+2)-a}. Find its input.`,b+2,'Undo subtraction,then multiplication.',`(${3*(b+2)-a} + ${a}) ÷ 3 = ${b+2}.`));
 add('unknown:0',num(`x + ${a+6} = ${a+b+9}. Find x.`,b+3,'Subtract the known addend.',`${a+b+9} − ${a+6} = ${b+3}.`));
 add('unknown:1',num(`${a+1} × y = ${(a+1)*(b+2)}. Find y.`,b+2,'Divide total by the known factor.',`${(a+1)*(b+2)} ÷ ${a+1} = ${b+2}.`));
 add('unknown:2',num(`3 × z + ${a+1} = ${3*(b+1)+a+1}. Find z.`,b+1,'Remove the addition before dividing.',`(${3*(b+1)+a+1} − ${a+1}) ÷ 3 = ${b+1}.`));
 add('mental:0',num(`Calculate ${26+i*11} + 9 mentally.`,35+i*11,'Add10,then remove1.',`${26+i*11}+10−1=${35+i*11}.`));
 add('mental:1',num(`Calculate ${302+i*101} − 99 mentally.`,203+i*101,'Subtract100,then give1 back.',`${302+i*101}−100+1=${203+i*101}.`));
 add('mental:2',num(`Calculate ${(a+.35).toFixed(2)} + 1.99.`,a+2.34,'Add2,then subtract0.01.',`${(a+.35).toFixed(2)}+2−0.01=${(a+2.34).toFixed(2)}.`));
 add('operations:0',num(`Calculate (${a*3} + ${b*3}) ÷ 3.`,a+b,'Complete the brackets first.',`${a*3+b*3} ÷ 3 = ${a+b}.`));
 const length=85+i*15;add('operations:1',num(`Three ribbons are ${(length/100).toFixed(2)}m each. Find total length in metres.`,length*3/100,'Multiply the hundredths by3.',`3 × ${(length/100).toFixed(2)} = ${(length*3/100).toFixed(2)}m.`));
 const litres=(a+.5)*4;add('operations:2',num(`Share ${litres} litres equally among4 jugs,then remove0.25 litres from each. How many litres remain per jug?`,a+.25,'Divide total into four,then subtract from one share.',`${litres}÷4=${a+.5}; ${a+.5}−0.25=${a+.25}L.`));
 const halfNumerator=i+3;add('fraction-links:0',choice('Which fraction is equivalent to one half?',`${halfNumerator}/${halfNumerator*2}`,[`${halfNumerator-1}/${halfNumerator*2}`,`${halfNumerator+1}/${halfNumerator*2}`],'The numerator must be half the denominator.',`${halfNumerator} is half of ${halfNumerator*2},so ${halfNumerator}/${halfNumerator*2}=1/2.`));
 const total=24+i*8;add('fraction-links:1',num(`Find three quarters of ${total}.`,total*3/4,'Find one quarter first,then three such groups.',`${total}÷4=${total/4}; ${total/4}×3=${total*3/4}.`));
 const numerator=[1,2,4,5][i];add('fraction-links:2',choice(`Which decimal and percentage match ${numerator}/5?`,`${(numerator/5).toFixed(1)} and ${numerator*20}%`,[`${(numerator/10).toFixed(1)} and ${numerator*10}%`,`${(numerator/5).toFixed(1)} and ${numerator*2}%`],'Change fifths into hundredths.',`${numerator}/5=${numerator*20}/100=${(numerator/5).toFixed(1)}=${numerator*20}%.`));
 const pound=i+2;add('currency:1',num(`For this pretend rate only,£1 buys€1.40. How many euros do£${pound} buy? Ignore fees.`,pound*1.4,'Use the stated practice rate,not a live rate.',`${pound}×€1.40=€${(pound*1.4).toFixed(2)}.`));
 add('currency:2',num(`For this pretend rate only,£1 buys€1.50. How many pounds buy€${(pound*1.5).toFixed(2)}? Ignore fees.`,pound,'Find the number of€1.50 groups.',`€${(pound*1.5).toFixed(2)}÷€1.50=${pound} groups,so£${pound}.`));
 add('units:0',num(`How many centimetres are in ${a+2} metres?`,(a+2)*100,'There are100cm in1m.',`${a+2}×100=${(a+2)*100}cm.`));
 add('units:1',num(`Convert ${(a+.25).toFixed(2)} litres to millilitres.`,a*1000+250,'Multiply litres by1000.',`${a}L=${a*1000}mL;0.25L=250mL;total${a*1000+250}mL.`));
 add('units:2',num(`A ${a+1}kg bag loses ${450+i*50}g. How many grams remain?`,(a+1)*1000-450-i*50,'Convert kilograms to grams first.',`${(a+1)*1000}−${450+i*50}=${(a+1)*1000-450-i*50}g.`));
 add('volume:0',num(`${a+3} unit cubes exactly fill a box in one row and one layer,without gaps. What is its volume in cubic units?`,a+3,'Count cubes,not faces.',`${a+3} cubes each occupy1 cubic unit,total${a+3}.`));
 add('volume:1',num(`A cuboid is ${a+1}cm long,${b+1}cm wide and3cm high. What is its volume in cm³?`,(a+1)*(b+1)*3,'Find cubes in a layer,then count layers.',`${a+1}×${b+1}×3=${(a+1)*(b+1)*3}cm³.`));
 add('volume:2',num(`A cuboid has volume${a*b*(i+2)}cm³ and base${a}cm by${b}cm. What is its height in cm?`,i+2,'Divide by the base area.',`Base${a*b}cm²; ${a*b*(i+2)}÷${a*b}=${i+2}cm.`));
 add('scale:0',num(`A map uses1cm for3m. A path is ${a+1}cm on the map. Find its real length in metres.`,(a+1)*3,'Multiply map units by the real distance per unit.',`${a+1}×3=${(a+1)*3}m.`));
 add('scale:1',num(`A drawing uses1cm for4m. How many centimetres represent ${4*(a+2)}m?`,a+2,'Divide the real length by4.',`${4*(a+2)}÷4=${a+2}cm.`));
 const hour=i+5;add('time:0',choice(`An analogue clock has its minute hand on6 and hour hand halfway between${hour} and${hour+1}. What time is it?`,`${hour}:30`,[`${hour+1}:30`,`${hour}:00`],'The hour is the one the short hand has passed.',`Minute hand6 means30 past;the time is${hour}:30.`));
 add('time:1',choice(`Convert ${14+i}:20 to12-hour time.`,`${2+i}:20 pm`,[`${2+i}:20 am`,`${4+i}:20 pm`],'Subtract12 from the hour and retain minutes.',`${14+i}−12=${2+i};it is afternoon.`));
 const start=43+i*3,end=14+i*2;add('time:2',num(`A journey starts09:${start} and ends10:${end}. How long in minutes?`,60-start+end,'Bridge10:00,then add the second interval.',`${60-start}+${end}=${60-start+end} minutes.`));
 const firstAngle=40+i*5,secondAngle=65;add('angles:1',num(`Two interior angles of a triangle are${firstAngle}° and${secondAngle}°. Find the third in degrees.`,180-firstAngle-secondAngle,'Triangle interior angles total180°.',`180−${firstAngle}−${secondAngle}=${180-firstAngle-secondAngle}°.`));
 add('coordinates:0',choice(`How do you reach (${a},${b}) from the origin in the first quadrant?`,`${a} right, ${b} up`,[`${b} right, ${a} up`,`${a} left, ${b} down`],'Read the horizontal coordinate first.',`x=${a} is right; y=${b} is up.`));
 add('frequency:0',num(`Tallies show ${a} complete groups of five marks and ${i+1} extra marks. What is the frequency?`,a*5+i+1,'Multiply the number of complete groups by5,then add extras.',`${a}×5+${i+1}=${a*5+i+1}.`));
 add('frequency:1',num(`Each child chooses one fruit. Apple${a+3},pear${b+2},plum${i+2}. How many choose apple or pear?`,a+b+5,'Add only the two requested,non-overlapping groups.',`${a+3}+${b+2}=${a+b+5}.`));
 add('frequency:2',num(`Times recorded in whole minutes:0–9:${a} children;10–19:${b};20–29:${a+2}. How many read for at least10 but less than30 minutes?`,a+b+2,'Use the last two intervals.',`${b}+${a+2}=${a+b+2}.`));
 add('averages:0',num(`Find the range of ${a},${a+7},${a+2},${a+10+i}.`,10+i,'Subtract the least value from the greatest.',`${a+10+i}−${a}=${10+i}.`));
 add('averages:1',num(`Find the mean of ${a},${a+3},${a+6}.`,a+3,'Add three values and divide by3.',`${3*a+9}÷3=${a+3}.`));
 const mean=a+4,known=[mean-2,mean-1,mean+1];add('averages:2',num(`Four counts have mean${mean}. Three counts are${known.join(', ')}. Find the missing count.`,mean+2,'Recover the total using four times the mean.',`Total${mean*4};known${known.reduce((x,y)=>x+y,0)};missing${mean+2}.`));
}
// Familiar facts, then less familiar products, then inverse division. All1–10
// tables include multipliers1–10 across the multiplication banks (100 products).
for(const factor of [1,2,5,10,3,4,6,7,8,9])for(let groups=1;groups<=10;groups++){
 const product=factor*groups,level=[1,2,5,10].includes(factor)?0:1;
 if(!((factor===5&&groups===4)||(factor===8&&groups===7)))add(`tables:${level}`,num(`There are ${groups} equal groups of ${factor} counters. How many counters altogether?`,product,'Use equal groups,an array,or a related fact;there is no timer.',`${groups} groups × ${factor} counters = ${product}. Check by repeated addition.`));
 if(!(factor===10&&groups===9))add('tables:2',num(`${product} counters are shared equally among ${factor} groups. How many counters per group?`,groups,`Find the missing factor in ${factor} × ? = ${product}.`,`${product} ÷ ${factor} = ${groups}; ${factor} × ${groups} = ${product}.`));
}
// Representation/classification banks use distinct examples,not random shuffles.
for(const [angle,label] of [[25,'Acute'],[80,'Acute'],[110,'Obtuse'],[225,'Reflex']] as const)add('angles:0',choice(`Classify an angle of${angle}°.`,label,(label==='Acute'?['Obtuse','Reflex']:label==='Obtuse'?['Acute','Reflex']:['Acute','Obtuse']),'Compare with90°,180° and360°.',`${angle}° is ${label.toLowerCase()}: ${label==='Acute'?'below90°':label==='Obtuse'?'between90° and180°':'between180° and360°'}.`));
for(const [sides,name,wrong] of [[4,'Quadrilateral',['Triangle','Pentagon']],[5,'Pentagon',['Hexagon','Triangle']],[6,'Hexagon',['Pentagon','Octagon']],[8,'Octagon',['Hexagon','Quadrilateral']]] as [number,string,[string,string]][])add('shapes:0',choice(`What is a polygon with exactly${sides} straight sides called?`,name,wrong,'Trace its boundary once and count the sides.',`${name} names a${sides}-sided polygon,whether regular or irregular.`));
for(const [start,turn,result,wrong] of [['South','clockwise','West',['East','North']],['West','clockwise','North',['South','East']],['East','anticlockwise','North',['South','West']],['North','anticlockwise','West',['East','South']]] as [string,string,string,[string,string]][])add('directions:0',choice(`Face ${start.toLowerCase()} and turn one quarter turn ${turn}. Which direction now?`,result,wrong,'Use90° and the stated direction of turning.',`A quarter turn ${turn} from ${start.toLowerCase()} points ${result.toLowerCase()}.`));
for(const [pair,answer,wrong] of [['north and east','North-east',['North-west','South-east']],['east and south','South-east',['North-east','South-west']],['south and west','South-west',['North-west','South-east']],['west and north','North-west',['North-east','South-west']]] as [string,string,[string,string]][])add('directions:1',choice(`Which compass point is halfway between ${pair}?`,answer,wrong,'Combine the names of the adjacent cardinal directions.',`${answer} lies between ${pair}.`));
// Append extension items so all existing saved practice indices retain their meaning.
for(let factor=1;factor<=12;factor++)for(let groups=1;groups<=12;groups++){
 if(factor<=10&&groups<=10)continue;
 const product=factor*groups;
 const split=factor===11||factor===12?factor:groups,other=split===factor?groups:factor;
 const explanation=`${split} × ${other} = 10 × ${other} + ${split-10} × ${other} = ${10*other} + ${(split-10)*other} = ${product}.`;
 add('tables:1',num(`Extra table practice: ${factor} × ${groups} = ?`,product,'Build from ten equal groups, then add one or two more groups.',explanation));
 add('tables:2',num(`Extra related division: ${product} ÷ ${factor} = ?`,groups,`Use the related fact ${factor} × ? = ${product}.`,`${factor} × ${groups} = ${product}, so ${product} ÷ ${factor} = ${groups}.`));
}
// Check structural invariants at authoring time; this never assesses children.
for(const [key,bank] of Object.entries(mathsPractice)){
 if(bank.length<4)throw Error(`Insufficient equivalent practice:${key}`);
 for(const task of bank){
  if(typeof task.answer==='number'&&(!Number.isFinite(task.answer)||task.answer<0))throw Error(`Invalid numeric key:${key}`);
  if(task.options&&(new Set(task.options).size!==task.options.length||task.options.filter(x=>x===task.answer).length!==1))throw Error(`Invalid options:${key}`);
 }
}
