import {trail as t,number as n,choice as c,practical as p} from './authoring.ts';
export const maths = [
 t('place-value','Number neighbourhood','Maths','Number','Read, order and partition whole numbers and decimals.',[
 n('What is the value of the 7 in 3,742?',700,'Look at its column: thousands, hundreds, tens, ones.','The 7 is in the hundreds column, so its value is 700.'),
 c('Which list goes from smallest to largest?',['4.05, 4.5, 4.55','4.5, 4.05, 4.55','4.55, 4.5, 4.05'],'4.05, 4.5, 4.55','Write 4.5 as 4.50 to compare hundredths.','4.05 < 4.50 < 4.55. A final zero does not change the value.'),
 n('Write the number made from 40,000 + 600 + 8 + 0.03. Do not use commas.',40608.03,'Keep a place for each zero.','40,608.03 has four ten-thousands, six hundreds, eight ones and three hundredths.')]),
 t('decimal-scaling','The number lift','Maths','Number','Multiply and divide numbers by 10 and 100 using place value.',[
 n('What is 34 × 10?',340,'Each digit represents ten times its previous value.','34 tens are 340. The value of each digit becomes ten times larger.'),
 n('What is 7.25 × 100?',725,'Hundredths become ones when multiplied by 100.','7.25 × 100 = 725. Digits take places worth 100 times as much.'),
 n('What is 643 ÷ 100?',6.43,'Each digit represents one hundredth of its previous value.','643 hundredths are 6.43.')]),
 t('estimate','The sensible answer','Maths','Number','Estimate and round to judge whether a calculation is reasonable.',[
 n('Round 347 to the nearest ten.',350,'Look at the ones digit.','347 is 3 away from 350 and 7 away from 340.'),
 n('Estimate 198 + 403 by rounding each number to the nearest hundred.',600,'Round first, then add.','198 rounds to 200 and 403 to 400. The estimate is 600, close to the exact total 601.'),
 c('A pupil says 49 × 21 = 10,029. Which estimate best shows a problem?',['50 × 20 = 1,000','50 + 20 = 70','49 − 21 = 28'],'50 × 20 = 1,000','Choose an estimate using the same operation.','The product should be near 1,000, not 10,000. The exact answer is 1,029.')]),
 t('negative','Below zero','Maths','Number','Use negative numbers in temperature and other contexts.',[
 c('Which temperature is colder?',['−3°C','2°C','0°C'],'−3°C','On a number line, colder temperatures are further left.','−3°C is below zero and colder than 0°C or 2°C.'),
 n('The temperature rises from −4°C to 3°C. By how many degrees does it rise?',7,'Count 4 steps to zero, then 3 more.','4 + 3 = 7 degrees of increase.'),
 c('A lift is at floor 2 and goes down 5 floors. Where is it?',['Floor −3','Floor 3','Floor −7'],'Floor −3','Count down: 1, 0, −1, −2, −3.','2 − 5 = −3. Floor zero counts as a floor in this model.')]),
 t('sequences','Pattern paths','Maths','Number','Follow, explain and devise rules for number sequences.',[
 n('Continue the sequence: 6, 10, 14, 18, …',22,'Find the same step between neighbouring numbers.','Add 4 each time: 18 + 4 = 22.'),
 n('Continue the sequence: 3, 6, 12, 24, …',48,'The next number is twice the previous one.','The rule is multiply by 2. 24 × 2 = 48.'),
 p('Make a sequence of five whole numbers using two alternating rules. Ask a partner to predict two more. Explain your rules and test their prediction.','For example, you might alternate adding and multiplying. State the starting value.', ['I wrote five numbers','My partner predicted two more','We checked both alternating rules'],'Adult review: accept any consistent alternating rules with correct calculations. Ask whether a different rule could also fit the short sequence.')],'practical'),
 t('factors','Number connections','Maths','Number','Use multiples, factors, primes, squares, cubes and inverse operations.',[
 n('How many factors does 12 have? Count each different positive whole-number factor once.',6,'List factor pairs without repeating a number.','The factors are 1, 2, 3, 4, 6 and 12: six factors.'),
 c('Which number is prime?',['21','23','25'],'23','A prime has exactly two positive factors: 1 and itself.','23 has only 1 and 23 as factors. 21 = 3 × 7 and 25 = 5 × 5.'),
 n('Calculate 4 cubed minus 5 squared.',39,'Cubed means multiply three copies; squared means two.','4³ = 64 and 5² = 25. 64 − 25 = 39. Division can check the multiplication.')]),
 t('machines','Function factory','Maths','Number','Use function machines and generalise simple relationships.',[
 n('A machine adds 7. What is its output for input 8?',15,'Follow the rule once.','8 + 7 = 15.'),
 n('A machine doubles a number and then adds 3. What is its output for input 6?',15,'Do the operations in the stated order.','6 × 2 = 12, then 12 + 3 = 15.'),
 n('A machine multiplies by 3 then subtracts 2. Its output is 19. What was its input?',7,'Undo the last step first.','19 + 2 = 21, then 21 ÷ 3 = 7. Check: 7 × 3 − 2 = 19.')]),
 t('unknown','The missing number','Maths','Number','Use a letter to represent an unknown number.',[
 n('a + 8 = 15. What is a?',7,'Use subtraction to undo addition.','15 − 8 = 7; 7 + 8 = 15.'),
 n('4 × b = 36. What is b?',9,'Divide 36 into four equal groups.','36 ÷ 4 = 9.'),
 n('3 × c + 5 = 26. What is c?',7,'Subtract 5, then divide by 3.','26 − 5 = 21 and 21 ÷ 3 = 7.')]),
 t('mental','Clever calculation','Maths','Number','Choose mental addition and subtraction strategies.',[
 n('Work out 38 + 9 mentally.',47,'Add 10, then adjust.','38 + 10 − 1 = 47.'),
 n('Work out 203 − 98 mentally.',105,'Subtract 100 and give 2 back.','203 − 100 + 2 = 105.'),
 n('Work out 4.75 + 2.99.',7.74,'Add 3 and subtract 0.01.','4.75 + 3 − 0.01 = 7.74. Explain why the adjustment is subtraction.')]),
 t('tables','Equal groups','Maths','Number','Recall multiplication facts to 10 × 10 and their related division facts.',[
 n('There are 4 trays with 5 buns on each. How many buns?',20,'Count in fives four times.','4 × 5 = 20.'),
 n('Seven groups have 8 counters each. How many counters?',56,'You can use 5 × 8 plus 2 × 8.','40 + 16 = 56, so 7 × 8 = 56.'),
 n('90 counters are shared equally among 10 groups. How many per group?',9,'Use the matching multiplication fact.','10 × 9 = 90, so 90 ÷ 10 = 9.')]),
 t('operations','Calculation workshop','Maths','Number','Use four operations, brackets and decimal calculations in problems.',[
 n('Find (12 + 8) ÷ 4.',5,'Complete the brackets first.','12 + 8 = 20; 20 ÷ 4 = 5.'),
 n('Three ribbons are each 1.25 m long. What is their total length in metres?',3.75,'Add three copies of 1.25.','1.25 × 3 = 3.75 m.'),
 n('Share 9.6 litres equally among 4 jugs, then pour 0.35 litres out of each jug. How much remains in each jug?',2.05,'Divide first, then subtract from one jug.','9.6 ÷ 4 = 2.4; 2.4 − 0.35 = 2.05 litres per jug.')]),
 t('fraction-links','Different names, same share','Maths','Number','Connect fractions, decimals and percentages and use fractions of quantities.',[
 c('Which fraction is equal to one half?',['2/4','1/4','3/4'],'2/4','Imagine two out of four equal pieces.','2/4 and 1/2 name the same proportion.'),
 n('What is three quarters of 20?',15,'Find one quarter, then take three of them.','20 ÷ 4 = 5; 3 × 5 = 15.'),
 c('Which list contains three equal values?',['3/5, 0.6, 60%','3/5, 0.3, 30%','3/5, 0.6, 6%'],'3/5, 0.6, 60%','Express fifths as tenths or hundredths.','3/5 = 6/10 = 60/100, so it is 0.6 and 60%.')]),
 t('budget','Plan a class picnic','Maths','Number','Prioritise a budget, compare value and discuss safe ways to pay.',[
 p('With an adult, plan a pretend £6 picnic. Apples cost £1 each, rolls £2 and water £1. Choose food and a drink within the budget. Explain your choices.','Write quantities and costs before adding them.', ['My total is at most £6','I included food and a drink','I explained one spending choice'],'Adult review: verify quantities × prices and the total. Invite discussion of needs and wants.'),
 p('A pack of 4 pencils costs £1.20. A pack of 6 costs £2.10. Find each price per pencil. Decide which offers better value, then discuss how to keep money or a payment card safe.','Convert to pence and divide by the number of pencils.', ['I calculated both unit prices','I justified my choice','We discussed safe handling of money'],'Adult review: 30p versus 35p per pencil; the four-pack is cheaper per pencil. Also discuss whether all the pencils are needed. Never ask children for real payment details.'),
 p('You want a £15 book. You have £6 and save £3 each week. Make a savings plan and compare paying cash with paying by card, with an adult.','Work out the shortfall and the number of equal weekly savings.', ['I found how much more is needed','I made a weekly plan','We compared payment methods safely'],'Adult review: £9 more is needed, taking 3 weeks at £3 per week. Both payment methods have advantages; discuss receipts and keeping account details private.')],'practical'),
 t('currency','A trip across the border','Maths','Number','Recognise pounds and euros and calculate with a stated example exchange rate.',[
 c('Which symbol represents the euro?',['€','£','%'],'€','A euro symbol looks like an E with two lines.','€ is the euro symbol; £ is the pound symbol.'),
 n('For this pretend exchange only, £1 buys €1.20. How many euros does £5 buy? Ignore fees.',6,'Multiply the stated rate by 5.','5 × €1.20 = €6. Real exchange rates vary; this is an invented practice rate.'),
 n('For this pretend exchange only, £1 buys €1.25. How many pounds buy €10? Ignore fees.',8,'Find how many groups of €1.25 fit into €10.','10 ÷ 1.25 = 8. £8 buys €10 at this practice rate; no live rate is being quoted.')]),
 t('measure-estimate','Measure like a scientist','Maths','Measures','Estimate measures and choose units, instruments and appropriate accuracy.',[
 p('Estimate the length of a book in centimetres, then measure it with a ruler. Compare the two values.','Line up the object with zero, not the edge of the ruler.', ['I estimated before measuring','I used the ruler from zero','I compared my estimate and measurement'],'Adult review: check the zero point, centimetre units and sensible accuracy. Estimation need not be exact.'),
 p('With an adult, choose tools to measure a cup’s capacity, an apple’s mass and a short walk’s duration. Estimate first, measure, then record units.','Think measuring jug, kitchen scales and a clock. Use safe household objects.', ['I chose suitable tools','I recorded estimates and measurements','I used capacity, mass and time units'],'Adult review: discuss ml, g and seconds/minutes. A measuring tool has a resolution; do not report more precision than it supports.'),
 p('Measure one object’s length twice. Then discuss how a temperature such as 18.5°C can lie between 18°C and 19°C. Explain why measurements are not limited to whole numbers.','A scale can be divided into smaller intervals.', ['I compared repeated measurements','I explained a value between two whole numbers','I discussed useful accuracy'],'Adult review: check understanding of continuous measures and uncertainty. Distinguish measurement precision from exact counting.')],'practical'),
 t('units','Unit explorers','Maths','Measures','Convert metric units and solve measurement problems.',[
 n('How many centimetres are in 2 metres?',200,'One metre is 100 centimetres.','2 × 100 = 200 cm.'),
 n('How many millilitres are in 1.75 litres?',1750,'One litre is 1,000 ml.','1.75 × 1,000 = 1,750 ml.'),
 n('A bag holds 2 kg of rice. After using 650 g, how many grams remain?',1350,'Convert the starting mass to grams first.','2 kg = 2,000 g; 2,000 − 650 = 1,350 g.')]),
 t('volume','Pack the parcel','Maths','Measures','Calculate volumes of simple cuboids using unit cubes.',[
 n('Three unit cubes exactly fill a box without gaps. There is one row and one layer. What is its volume in cubic units?',3,'Count the cubes, not just their faces.','The 3 cubes each occupy one cubic unit: volume 3 cubic units.'),
 n('A cuboid is 4 cm long, 3 cm wide and 2 cm high. What is its volume in cm³?',24,'Find cubes in one layer, then multiply by the layers.','4 × 3 × 2 = 24 cm³.'),
 n('A cuboid has volume 60 cm³, length 5 cm and width 4 cm. What is its height in cm?',3,'Divide volume by the area of the base.','The base area is 5 × 4 = 20 cm². 60 ÷ 20 = 3 cm.')]),
 t('scale','Map makers','Maths','Measures','Interpret and create simple scale drawings.',[
 n('On a map, 1 cm stands for 2 m. A path is 4 cm on the map. How long is the real path in metres?',8,'Multiply the map length by 2.','4 × 2 = 8 m.'),
 n('On a drawing, 1 cm stands for 5 m. How many centimetres represent 35 m?',7,'Divide the real distance by 5.','35 ÷ 5 = 7 cm on the drawing.'),
 p('Draw a 12 m by 8 m garden using a scale of 1 cm to 2 m. Add a 4 m straight path and a key explaining your symbols.','Divide each real length by 2 for drawing lengths.', ['I labelled the scale','My garden and path use the same scale','I included a clear key'],'Adult review: garden 6 cm × 4 cm; path 2 cm. Check ruler use and the distinction between map and real units.')]),
 t('time','Time travellers','Maths','Measures','Read analogue and digital time, convert clock formats and use timetables.',[
 c('An analogue clock has its minute hand on 6 and hour hand halfway from 3 to 4. What time is it?',['3:30','6:15','4:30'],'3:30','The minute hand on 6 means 30 minutes past.','It is half past three; the hour hand is between 3 and 4.'),
 c('What is 17:45 in 12-hour time?',['5:45 pm','7:45 pm','5:45 am'],'5:45 pm','For hours after 12, subtract 12 and use pm.','17 − 12 = 5, so 17:45 is 5:45 pm.'),
 n('A bus timetable shows departure 09:48 and arrival 10:25. How long is the journey in minutes?',37,'Count to 10:00 and then to 10:25.','12 minutes + 25 minutes = 37 minutes.')]),
 t('shapes','Shape detectives','Maths','Shape and Space','Construct and classify regular and irregular 2-D shapes by their properties.',[
 c('Which shape has exactly three straight sides?',['Triangle','Rectangle','Pentagon'],'Triangle','Count sides around the boundary.','Every triangle has three straight sides and three angles.'),
 c('Which statement must be true of every rectangle?',['It has four right angles','All four sides have the same length','It has exactly one pair of parallel sides'],'It has four right angles','A square is a special rectangle, but many rectangles have unequal adjacent sides.','Rectangles have four right angles and two pairs of parallel sides.'),
 p('Draw a regular pentagon and an irregular pentagon. Compare sides and angles. Draw a congruent copy of one shape and explain what congruent means.','Regular means all sides and angles are equal. Congruent means the same shape and size.', ['I made two five-sided shapes','I compared regular and irregular properties','I made and explained a congruent copy'],'Adult review: both shapes must have five sides. Check equality for the regular example and matching dimensions in the congruent copy. Use a template if needed.')]),
 t('symmetry','Patterns in the tiles','Maths','Shape and Space','Explore reflection, line and rotational symmetry, and tessellation.',[
 p('Fold paper and cut a safe shape with adult help. Open it and draw the fold line. Explain how the halves match.','The fold is a possible line of symmetry.', ['I made a symmetrical shape','I marked a line of symmetry','I explained matching halves'],'Adult review: folding along the line should make the halves coincide. Use safe scissors or draw on folded paper instead.'),
 p('Draw an L shape on squared paper and a mirror line beside it. Reflect each corner across the line at the same distance. Test whether the L has rotational symmetry before a full turn.','Count perpendicular distances to the mirror line.', ['I reflected matching corners','I checked equal distances','I tested turns of the L'],'Adult review: the reflected L reverses orientation. A usual block L matches itself only after a full turn, so has rotational symmetry order 1.'),
 p('Use paper squares and equilateral triangles to try tiling a flat surface without gaps or overlaps. Then rotate a square and record how many times it matches itself in one full turn.','Count the starting orientation only once, or count the ending orientation instead.', ['I tested tiling without gaps or overlaps','I recorded the square’s matching turns','I explained my findings'],'Adult review: either shape can tessellate on its own. A square has rotational symmetry order 4, at 90°, 180°, 270° and 360°.')],'practical'),
 t('solids','From flat to solid','Maths','Shape and Space','Describe 3-D shapes and connect faces, edges, vertices and nets.',[
 n('How many square faces does a cube have?',6,'Think top, bottom, front, back, left and right.','A cube has 6 square faces.'),
 n('How many vertices (corners) does a cuboid have?',8,'Count 4 on the top and 4 on the bottom.','A cuboid has 8 vertices, 12 edges and 6 faces.'),
 p('With adult help, make a cube net from six paper squares. Fold or imagine folding it. Label faces, edges and vertices, and explain why some arrangements of six squares are not nets.','Start with four squares in a row and attach one above and one below the second square.', ['I tried folding a net','I connected flat faces to a solid','I counted faces, edges and vertices'],'Adult review: a cube has 6 faces, 12 edges and 8 vertices. The suggested net folds without overlapping faces. Check safe cutting and explain failed nets.')]),
 t('directions','Compass code','Maths','Shape and Space','Use compass points, turns and simple programs to generate shapes.',[
 c('You face north and turn a quarter turn clockwise. Which way do you face?',['East','West','South'],'East','Clockwise follows the hands of a clock.','North to east is a quarter turn clockwise.'),
 c('Which compass direction lies halfway between south and west?',['South-west','North-west','South-east'],'South-west','Combine the two adjacent cardinal directions.','The eight points include south-west between south and west.'),
 p('In the drawing pad below, act as a drawing robot. Start facing up. Write FORWARD 3 then RIGHT 90 on separate lines, four times. Draw the path, then change your commands to draw a rectangle that is not a square.','Write every command on its own line. For a rectangle, alternate longer and shorter sides, keeping each turn at 90 degrees.', ['I followed the square program','I wrote a rectangle program','I tested the turns and explained the result'],'Adult review: the first program draws a 3-by-3 square and returns to the start. A possible rectangle program repeats forward 4, right 90°, forward 2, right 90° twice. Use the live drawing to check the path and compare it with a paper sketch.')]),
 t('angles','Turn and discover','Maths','Shape and Space','Recognise, calculate, measure and draw angles up to a full turn.',[
 c('An angle is 60°. Which type is it?',['Acute','Obtuse','Reflex'],'Acute','Compare it with a 90° right angle.','60° is less than 90°, so it is acute. Obtuse angles lie between 90° and 180°; reflex angles between 180° and 360°.'),
 n('Two angles of a triangle are 50° and 60°. What is the third angle in degrees?',70,'Angles inside a triangle total 180°.','180 − 50 − 60 = 70°.'),
 p('Use a protractor to draw 120° and a reflex angle of 240°. Draw a quadrilateral, measure its four interior angles and add them.','For 240°, mark a 120° turn in the other direction and label the larger angle.', ['I measured and drew both angles','I identified the reflex region','I investigated the quadrilateral’s angle sum'],'Adult review: check correct scale, vertex and baseline alignment. A simple quadrilateral’s interior angles total 360°, allowing small measurement error.')]),
 t('coordinates','Find the treasure','Maths','Shape and Space','Plot coordinates and draw shapes in the first quadrant.',[
 c('For the point (3, 2), how do you travel from the origin?',['3 right, 2 up','2 right, 3 up','3 left, 2 down'],'3 right, 2 up','The horizontal coordinate comes first.','x = 3 means right 3; y = 2 means up 2.'),
 p('On squared paper, label axes from 0 to 6. Plot (1,1), (5,1), (5,3), (1,3) and join them in order. Name the shape.','Use the same scale on both axes.', ['I labelled and scaled both axes','I plotted all four points','I described the shape'],'Adult review: the result is a rectangle 4 units wide and 2 units high.'),
 p('Plot a triangle with vertices (1,1), (4,1), (1,5). Move every vertex 2 units right and 1 unit up. Record the new coordinates.','Add 2 to each x and 1 to each y.', ['I plotted the original triangle','I moved each vertex by the same amounts','I recorded and checked the new coordinates'],'Adult review: new vertices are (3,2), (6,2), (3,6). The triangle keeps its shape and size.')]),
 t('collect-data','Your own investigation','Maths','Handling Data','Plan an investigation, collect and classify data, and explain conclusions.',[
 p('Count three kinds of objects in one room. Make a tally table and describe which kind is most common. Do not record people’s names.','Use clear categories that do not overlap.', ['I chose three categories','I counted using tallies','I described the largest count'],'Adult review: tally totals should match the objects. Discuss whether each object belongs in exactly one category.'),
 p('Observe the weather at the same time for five days with an adult. Design a record sheet with categories, then make a bar chart using your data.','Use one agreed main weather category per observation.', ['I designed a record sheet','I recorded five observations','I labelled a chart and explained it'],'Adult review: discuss consistent observation rules, labels and a suitable scale. The app saves your reflection; keep your paper record between sessions.'),
 p('Ask a small willing group to choose one of three proposed garden plants. Record anonymous votes, present them in a chart and explain why the result may not represent the whole school.','Make the question neutral and allow one choice per person.', ['I collected anonymous responses fairly','I presented my data clearly','I explained a limitation'],'Adult review: inspect the data collection method and totals. A small convenience sample is not the same as a representative school survey.')],'practical'),
 t('frequency','Read the record','Maths','Handling Data','Interpret lists, tables and grouped frequency information.',[
 n('A tally record shows 5 + 5 + 3 marks for apples. What is the frequency?',13,'Frequency means the number counted.','5 + 5 + 3 = 13 apples.'),
 n('Each child chooses exactly one book category. Choices: adventure 8, animals 6, mystery 9. How many children chose animals or mystery?',15,'Combine just the two requested categories.','6 + 9 = 15 children.'),
 n('Reading times recorded in whole minutes are grouped: 0–9 minutes: 4 children; 10–19: 7; 20–29: 5. How many children read for at least 10 but less than 30 minutes?',12,'Include the last two groups.','7 + 5 = 12. Grouped data do not tell us each individual reading time.')]),
 t('data-tools','The data desk','Maths','Handling Data','Organise, query and interpret data using a spreadsheet or database.',[
 p('With an adult, enter this table into a spreadsheet: Oak 8, Ash 5, Birch 6. Give the columns clear headings. Save the sheet with a sensible title.','Use one row per tree type and one column for its count.', ['I entered the three records','I added headings','I saved and reread the table'],'Adult review: confirm accurate entry and appropriate headings such as Tree type and Count. This activity needs a separate spreadsheet application; no account or file is uploaded to this app.'),
 p('With an adult, open a spreadsheet and enter Tree type and Count as headings, followed by Oak 8, Ash 5, Birch 6. Use a total formula for the three counts. Sort the records by count, keeping names attached to their values.','Select both columns before sorting.', ['I used a working total formula','I sorted complete records','I checked the largest count'],'Adult review: total 19; Oak 8 is largest. Check that sorting did not separate labels from values.'),
 p('Make a small plant table with columns Plant, Height in cm, Needs sun. Add five imaginary records. Filter for plants at least 20 cm high that need sun. Explain how a database query can use two conditions.','Use fictional plants or ordinary names; never enter personal information.', ['I made five consistent records','I applied both conditions','I explained which records matched'],'Adult review: inspect both filter conditions and matched rows. Discuss the difference between a row/record and a column/field.')],'practical'),
 t('averages','What is typical?','Maths','Handling Data','Calculate and interpret the mean and range of discrete data.',[
 n('Find the range of these scores: 3, 7, 4, 9.',6,'Range = greatest minus smallest.','9 − 3 = 6.'),
 n('Find the mean of 4, 6, 8.',6,'Add the values and divide by how many values there are.','(4 + 6 + 8) ÷ 3 = 18 ÷ 3 = 6.'),
 n('The mean of four counts is 8. Three counts are 6, 7 and 9. What is the missing count?',10,'The total must be four times the mean.','Total = 4 × 8 = 32. Known counts total 22. Missing count = 32 − 22 = 10.')]),
 t('chance','Could it happen?','Maths','Handling Data','Describe possible outcomes, likelihood, certainty, impossibility and evens.',[
 c('A bag contains only red counters. What is the chance of drawing a blue counter?',['Impossible','Certain','Evens'],'Impossible','Think about which colours are actually in the bag.','There are no blue counters, so drawing one is impossible.'),
 c('A bag has 4 blue and 4 yellow counters of the same size. They are well mixed and each counter is equally likely to be drawn. One is drawn without looking. Drawing blue is…',['Evens','Certain','Impossible'],'Evens','There are equal numbers of the two colours.','Blue and yellow are equally likely; blue has an even chance.'),
 c('A bag has 6 red, 3 blue and 1 green equal-sized counters. They are well mixed and each is equally likely to be drawn. Which colour order goes from least to most likely?',['Green, blue, red','Red, blue, green','Blue, red, green'],'Green, blue, red','More counters of a colour mean a greater chance, not a guarantee.','1 green < 3 blue < 6 red. Red is more likely than evens but is not certain.')]),
 t('reasoning','Make a plan, test an idea','Maths','Processes in Mathematics','Select information and strategies, explain reasoning and check generalisations.',[
 p('You have 12 counters. Find different ways to split them into two groups. Record your pairs systematically and explain how you know none are missing.','Start with 0 and 12; move one counter at a time.', ['I chose a useful representation','I recorded pairs in a clear order','I explained how I checked completeness'],'Adult review: pairs run from 0+12 to 12+0, or through 6+6 if reversed pairs count as the same. The child should state their rule.'),
 p('A club needs 18 seats. Tables seat either 4 or 6 people. Find two arrangements with enough seats. Compare your methods with a partner and say which uses fewer empty seats.','List possible combinations, then calculate seats.', ['I selected the useful information','I found and checked two arrangements','We compared methods and conclusions'],'Adult review: examples include three six-seat tables (18 seats), or two six-seat and two four-seat tables (20). Accept other justified arrangements.'),
 p('Investigate this claim: adding two odd whole numbers always gives an even number. Test examples, draw pairs of counters, and explain why examples alone do not prove “always”.','Each odd number can be arranged in pairs with one left over.', ['I tested several examples','I used a diagram or objects','I gave a general explanation and checked it'],'Adult review: the two leftovers form a new pair, explaining the general case. Invite counterexample searching and comparison with another explanation.')],'practical')
];
