/** Guided curriculum investigations authored with AI assistance. Human NI KS2
 * specialist validation, practical classroom trials and device accessibility
 * checks remain pending. A saved reflection is evidence to review, not mastery.
 */
export type MathsProject={title:string;source:'maths';goal:string;materials:string[];steps:string[];model:string;evidence:string[];rubric:{support:string;developing:string;secure:string};tool?:'reading'|'writing'|'table'|'coordinates';text?:string;stages?:string[];audio?:string;starterRows?:string[][]};
const readable=(value:string)=>value.replace(/([a-zA-Z])([0-9])/g,'$1 $2').replace(/([0-9])([a-zA-Z])/g,'$1 $2').replace(/([,;])(?=[a-zA-Z0-9])/g,'$1 ');
const project=(title:string,goal:string,materials:string[],steps:string[],model:string,evidence:string[],support:string,developing:string,secure:string,extra:Partial<MathsProject>={}):MathsProject=>({title:readable(title),source:'maths',goal:readable(goal),materials:materials.map(readable),steps:steps.map(readable),model:readable(model),evidence:evidence.map(readable),rubric:{support:readable(support),developing:readable(developing),secure:readable(secure)},tool:'writing',...extra});
export const mathsProjects:Record<string,MathsProject>={
MP1:project('Choose your mathematical toolkit','Choose resources for a task and justify why they help.',['Optional counters, squared paper, ruler or multiplication grid'],[
 'Task A: share 24 seeds equally between 6 pots. Choose counters, a drawing or a number fact. Explain your choice before solving.',
 'Task B: design a rectangular bed with area 24m² and whole-metre sides. Choose a table, squared diagram or ruler drawing. Find three possibilities.',
 'Compare the resources: which revealed a pattern, which was quick, and which helped you check? Repeat with 30 seeds and a 30m² bed.'
],'A: 24÷6=4 seeds per pot. B: 1×24, 2×12, 3×8, 4×6 all have area 24. A factor-pair table helps avoid missing a rectangle; a diagram helps distinguish its area from its boundary. Resource choice depends on the question.',['Chosen resource and reason for each task','Two checked solutions and one changed resource choice'],'Needs an adult to select and use a resource.','Selects a useful resource but needs a prompt to explain its purpose.','Chooses, compares and evaluates resources while checking answers.'),
MP2:project('What information is missing?','Identify needed facts and choose a suitable way to obtain them.',['Optional ruler or tape measure','Adult help for measuring furniture; no personal data'],[
 'A class wants a paper strip around a rectangular display board. What must you find out before working out the strip length? List useful and irrelevant facts.',
 'Choose a source: measure a safe accessible board with an adult, ask an adult for its dimensions, or use this supplied record: width 80cm, height 50cm. Explain why your source fits.',
 'Find the boundary length. The strip is sold in 1m lengths; decide how many whole lengths cover the boundary if joins are allowed. State any extra allowance you would need if overlaps were required.',
 'New enquiry: enough cups for a group event. Identify two missing facts and explain how you would obtain them without recording names.'
],'For the board, width and height matter; colour does not. 2×(80+50)=260cm=2.6m, so three 1m lengths cover it when joins are allowed and no overlap is required. A cup enquiry needs an expected number of drinkers and whether each needs one cup or replacements.',['Useful facts and rejected facts','Named source and reason','Calculation with assumptions'],'Uses all supplied numbers without deciding relevance.','Identifies dimensions but needs help choosing a source or assumptions.','Obtains appropriate facts and explains limits or assumptions.'),
MP3:project('Organise two searches','Work systematically in number and money situations.',['Saved table or paper'],[
 'List every unordered pair of whole numbers that totals 14, including zero. State why reversed pairs count once.',
 'A snack costs 50p for an apple and £1 for a roll. Spend exactly £4. Make a table of roll quantities 0 to 4 and the needed apple quantities.',
 'Explain how your chosen order ensures no solution is missed. Change the snack budget to £5 and repeat.'
],'Pairs: (0,14) through (7,7), eight possibilities. For £4, rolls 0,1,2,3,4 require apples 8,6,4,2,0. Increasing rolls by one lowers apples by two. For £5, rolls 0 to 5 require apples 10,8,6,4,2,0.',['Complete pair list','Budget table with totals','Explanation of stopping rule'],'Lists isolated examples without an order.','Uses an ordered table with an adult checking omissions.','Explains completeness and applies the system in a second context.',{tool:'table',starterRows:[['Rolls','Apples','Total pence'],['0','',''],['1','',''],['2','',''],['3','',''],['4','','']]}),
MP4:project('A useful mistake','Recover from an error by representing, explaining and checking.',['Optional counters or squared paper'],[
 'A learner says a 7m by 3m rectangle needs 21m of fence. Do not just replace the answer: draw or describe what 21 measures.',
 'Use the recovery sequence: reread what is asked; label the needed quantity; sketch it; choose an operation; calculate; check units and plausibility.',
 'Work an easier related example, a 2m by 1m rectangle. Find both area and perimeter, then retry the 7m by 3m fence.',
 'Try the same routine on this error: “£5 minus 75p is £4.75.” Explain the error and check the corrected change by addition.'
],'21m² is area, not the fence length. The easy rectangle has area 2m² and perimeter 6m. The original fence is 7+3+7+3=20m. Convert £5 to 500p: 500−75=425p=£4.25; 425+75=500.',['Initial explanation','Easier example','Corrected solution and inverse check'],'Needs the error located and the relevant quantity named.','Follows the recovery sequence with reminders.','Independently identifies the misconception, selects a representation and checks a retry.'),
MP5:project('Say what the numbers mean','Use mathematical language to explain a garden calculation.',['Squared paper optional'],[
 'For a 6m by 3m garden, find area and perimeter. Write two sentences explaining why their units differ.',
 'A third of the garden becomes a path. Explain how you find the planting area, using whole, equal parts and remaining.',
 'Read your explanation to a partner or reread it yourself. Replace “times it” or “that number” with precise quantities. Record your revised explanation.'
],'Area 18m² counts square units covering the surface. Perimeter 18m measures the boundary: the equal numeral does not mean the quantities are the same. One third is 6m², leaving 12m². A clear explanation names which area is being divided and why.',['Calculations with units','Before-and-after explanation','Reason the equal numerical answers describe different measures'],'Uses area and perimeter interchangeably.','Calculates correctly but needs prompts to name quantities.','Explains operations and units clearly, including the one-third step.'),
MP6:project('Compare two sensible methods','Evaluate different correct approaches across contexts.',['Optional partner; solo comparison available'],[
 'For 58+27, compare Method A: 58+20+7. Method B: 60+27−2. Complete both and explain why each preserves the answer.',
 'For 24 seats using tables seating 4 or 6, compare six four-seat tables, four six-seat tables and two six-seat plus three four-seat tables.',
 'Decide what “better” means in each task: fewer steps, an easier known fact, fewer tables or another stated criterion. A partner can propose a different criterion; record both.'
],'Both sums equal 85. Compensation adds 2 then removes 2. All three table plans seat 24; their table counts are 6,4,5. Four six-seat tables use the fewest of those options, but furniture availability can change the decision.',['Two completed calculation methods','Comparison using a stated criterion','Reason another person might choose differently'],'Declares a method wrong simply because it differs.','Finds equal answers but needs help comparing efficiency or constraints.','Explains validity of both methods and evaluates a stated criterion.'),
MP7:project('One situation, several representations','Translate between a story, a table, a diagram and symbols.',['Optional squared paper'],[
 'A club charges £2 entry plus £3 per craft kit. Represent the cost for 0,1,2,3 kits in a table.',
 'Write a rule using k for the number of kits. Draw or describe an arrow machine matching the rule.',
 'Someone pays £14. Use the story, rule and reverse machine to find the number of kits. Explain what each number in your work represents.'
],'Rule cost=3×k+2. Table costs 2,5,8,11. Forward machine multiplies by 3 then adds 2; reverse subtracts 2 then divides by 3. (14−2)÷3=4 kits. A diagram with one £2 block and k £3 blocks represents the same situation.',['Complete table','Rule and described/drawn machine','Reverse calculation with labels'],'Mixes entry cost and per-kit cost.','Builds a table but needs help connecting it to symbols.','Connects all representations and interprets the reverse result.',{tool:'table',starterRows:[['Kits','Cost pounds'],['0',''],['1',''],['2',''],['3','']]}),
MP8:project('Present an investigation clearly','Retain numerical records and explain a suitable display.',['In-app table/chart or squared paper'],[
 'Enter this fictional seedling count: Monday 3, Tuesday 5, Wednesday 4, Thursday 8. Give both columns headings.',
 'Create a bar chart with a zero baseline and equal intervals. State a title and the meaning of one scale interval. Do not treat bar length as a decoration.',
 'Write two true statements and one question the data cannot answer. Save the table and your explanation so another person can check them.'
],'Total 20 seedlings were counted across the records, but the table does not say whether the same seedlings were counted again. Thursday’s count exceeds Monday’s by 5. A display needs named categories, counts and an honest equal scale. Growth rate cannot be inferred without knowing the collection method.',['Saved source table','Chart title and scale description','Two justified statements and one limit'],'Produces an unlabelled display or changes the data.','Records values correctly but needs help with labels or scale.','Presents consistent data and qualifies conclusions.',{tool:'table',starterRows:[['Day','Seedlings counted'],['Monday','3'],['Tuesday','5'],['Wednesday','4'],['Thursday','8']]}),
MP9:project('Growing square borders','Generalise a spatial pattern using a number table.',['Squared paper or optional counters'],[
 'Draw square grids with side lengths 3,4 and5 unit squares. Count only the outer border squares; count each corner once.',
 'Record side length and border count. Predict the border for side 6 and test with a drawing.',
 'Explain a rule for any whole side length n at least2. Compare “four sides minus repeated corners” with “all squares minus inner squares”.'
],'Border counts are 8,12,16,then20. Counting four sides counts each corner twice,so subtract4: 4n−4. Alternatively n²−(n−2)² gives the same border for n≥2. A few examples suggest the rule; the corner explanation justifies it.',['Table and prediction','Labelled count showing corners counted once','General explanation'],'Double-counts corners without noticing.','Finds the pattern with a drawing and prompt.','Explains the rule structurally and checks a new case.',{tool:'table',starterRows:[['Side length','Border squares'],['3',''],['4',''],['5',''],['6','']]}),
MP10:project('Many rectangles, one boundary','Explore an open problem and state its constraints.',['Squared paper optional'],[
 'Design rectangles with whole-metre sides and perimeter 20m. Neither side can be zero. Treat rotations as the same rectangle.',
 'List all possibilities and their areas. Which has the greatest area? Explain how you know your list is complete.',
 'Change the perimeter to 24m and investigate again. Ask one new question rather than assuming the original conclusion is a proof for all perimeters.'
],'For perimeter20, width+length=10: 1×9,2×8,3×7,4×6,5×5. Areas9,16,21,24,25m². The square is largest in this set. For perimeter24, pairs1×11 through6×6 give a largest area36m². These finite searches do not by themselves prove a universal statement.',['Constraints','Complete table','Conclusion and new question'],'Offers one rectangle and treats it as the only answer.','Lists several options but needs a stopping rule.','Explains completeness and limits the conclusion to the investigation.',{tool:'table',starterRows:[['Width m','Length m','Area m²'],['1','',''],['2','',''],['3','',''],['4','',''],['5','','']]}),
MP11:project('Invent and justify a rule','Formulate a machine from examples and explain its limits.',['Saved table'],[
 'A machine gives input/output pairs 1→5,2→8,3→11,4→14. Propose a simple rule and test every pair.',
 'Predict the output for 10 and the input that gives 32. Explain the reverse steps.',
 'Decide whether four pairs prove there is only one possible rule. Devise your own two-step machine, record its rule privately, then give a partner or yourself a fresh input to test.'
],'A simple rule is multiply by3 then add2. Input10 gives32; output32 reverses to10. Other specially constructed rules could fit four examples,so say “a rule that fits” rather than “the only rule”. Explain that the pattern increases by3 for each extra input.',['Proposed rule and all checks','Forward/reverse prediction','Own machine and recognition of non-uniqueness'],'Guesses from one pair without testing others.','Finds a working rule with prompts.','Tests and explains a general rule while acknowledging finite evidence.',{tool:'table',starterRows:[['Input','Output'],['1','5'],['2','8'],['3','11'],['4','14'],['10','']]}),
MP12:project('Does that everyday answer make sense?','Use estimation, units and inverse checks in varied problems.',['No special materials'],[
 'A child says 4 bags at £2.95 each cost £118. Estimate first,then calculate and locate the likely error.',
 'A 2m ribbon is cut into 25cm pieces with no waste. Estimate how many pieces and find the exact number.',
 'An adult says a short 600m walk took 2 seconds. Explain why the context makes that doubtful; identify information you would check rather than inventing a replacement time.'
],'Four near-£3 bags cost about£12; exact£11.80. The first answer is ten times too large. 2m=200cm;200÷25=8 pieces. Walking600m in2 seconds would mean300m each second,unreasonable for an ordinary walk; check units or the recorded start/end times.',['Estimate before exact calculation','Unit and inverse checks','A contextual reason and proposed verification'],'Accepts an answer without checking its size or unit.','Identifies an unlikely answer with prompts.','Chooses useful independent checks and explains what to verify.'),
MN1:project('Number journeys and ordering','Count,read,write and order whole numbers beyond a single place-value question.',['Optional place-value chart'],[
 'Count forward by 100 from 9,750 for six terms,then backwards by 25 from 1,050 for five terms. Record every term and explain crossing the thousand boundary.',
 'Write these in words: 4,080; 40,800; 40,080. Then write forty thousand and eight in digits.',
 'Order 40,008;4,800;40,080;4,080;40,800 from least to greatest. Compare the leftmost unequal place rather than the number of zeros.'
],'Forward:9750,9850,9950,10050,10150,10250. Backward:1050,1025,1000,975,950. In words:four thousand and eighty;forty thousand eight hundred;forty thousand and eighty. Forty thousand and eight=40,008. Order4080<4800<40008<40080<40800.',['Both count sequences','Number words and digits','Ordered list with comparison explanation'],'Loses place holders at a boundary.','Uses a chart to cross boundaries and compare values.','Counts across boundaries and explains whole-number notation and ordering.'),
MN2:project('Place-value transformations','Connect decimal columns to repeated scaling and inverse checks.',['Optional place-value chart'],[
 'Partition 6.04 and 6.40. Explain why they are different even though both use6 and4.',
 'Make a table for starting values 0.37,4.08,25.6 and306: calculate ×10,×100,÷10 and÷100.',
 'Choose two results and reverse the operation to check. Explain that digits take places of different value; do not describe an unexplained moving decimal point.'
],'6.04=6+4/100;6.40=6+4/10. Rows:0.37→3.7,37,0.037,0.0037;4.08→40.8,408,0.408,0.0408;25.6→256,2560,2.56,0.256;306→3060,30600,30.6,3.06. Thousandths here are an optional extension beyond the central two-decimal work; use whole starting values for ÷100 if not ready.',['Scaling table','Two inverse checks','Explanation of changed digit value'],'Confuses scaling with adding zeros anywhere.','Completes two-decimal examples with a chart.','Explains scale factors and inverse checks; extension only when appropriate.',{tool:'table',starterRows:[['Start','×10','×100','÷10','÷100'],['0.37','','','',''],['4.08','','','',''],['25.6','','','',''],['306','','','','']]}),
MN3:project('Pick an appropriate estimate','Choose rounding precision according to the question.',['No special materials'],[
 'Round 3,476 to the nearest10,100 and1,000. Identify the neighbouring multiples for each.',
 'Estimate 398×6 and £19.80+£10.15 using useful rounded values. Then find exact answers and compare.',
 'A hall has seats in18 rows of21. Explain why20×20 is a useful rough estimate but cannot decide whether exactly380 seats fit; calculate to decide.'
],'3476 rounds to3480,3500,3000. 398×6≈400×6=2400;exact2388. £19.80+£10.15≈£20+£10=£30;exact£29.95. 18×21=378,so there are fewer than380;the rough400 is insufficient for that close decision.',['Three rounded values','Estimates labelled as estimates','A decision about sufficient accuracy'],'Applies one rounding rule without considering the purpose.','Rounds correctly but needs help assessing whether precision suffices.','Chooses and justifies precision and checks borderline decisions exactly.'),
MN4:project('Fractions in several forms','Use equivalent fractions,decimals and percentages in quantities and measures.',['Paper strip or optional100-square grid'],[
 'Represent1/2,1/4,3/4,1/5,2/5 and1/10. Record an equivalent decimal and percentage for each.',
 'A30m path needs markers along two fifths of its length. Find that length. A£20 item has a25% discount;find the reduction and final cost.',
 'Compare0.7,2/3 and75% using a common representation. Explain why one rounded decimal comparison needs care.'
],'Matches:0.5/50%,0.25/25%,0.75/75%,0.2/20%,0.4/40%,0.1/10%. Two fifths of30m=12m. Discount£5;final£15. 2/3≈0.667<0.7<0.75;75%=0.75. Use fraction equivalence or enough decimal precision rather than treating0.67 as exact.',['Six equivalence rows','Two applied calculations','Comparison with an approximation label'],'Treats numerator and denominator as separate whole-number sizes.','Uses strips or hundred grids to connect familiar shares.','Connects representations and explains their use in quantities and money.',{tool:'table',starterRows:[['Fraction','Decimal','Percentage'],['1/2','',''],['1/4','',''],['3/4','',''],['1/5','',''],['2/5','',''],['1/10','','']]}),
MN5:project('Signed values in context','Compare and change negative values without losing the meaning of zero.',['Drawn number line optional'],[
 'At four times the temperature is−5°C,−1°C,3°C and0°C. Order coldest to warmest and find the rise from−5°C to3°C.',
 'A submarine is at−12m relative to sea level. It rises7m,then descends4m. Record both positions and explain each direction.',
 'Make your own floor or temperature problem crossing zero. Provide a solution and an inverse check.'
],'Order−5,−1,0,3. Rise8 degrees. Submarine rises to−5m,then descends to−9m. Zero is sea level,not the bottom of the range. Reversing the moves:−9+4−7=−12.',['Ordered signed values','Both submarine positions','Original contextual problem and check'],'Orders negative numbers by unsigned digit size.','Uses a marked number line to calculate.','Explains signed direction and verifies a new contextual problem.'),
MN6:project('A sequence laboratory','Explore additive,decreasing,multiplicative and alternating patterns.',['Saved table or paper'],[
 'Extend each by two terms:40,34,28,22;2,6,18,54;1,4,9,16. State a rule for each and check prior terms.',
 'Start at3 and alternate add4 then multiply by2. Write six terms,including the starting value.',
 'Devise your own sequence,write its rule before testing a prediction,and explain why a short list can fit more than one rule.'
],'Extensions:16,10 by subtract6;162,486 by multiply3;25,36 as successive squares. Alternating:3,7,14,18,36,40. “Add successive odd numbers” also generates squares;many artificial rules fit a finite list.',['Three rule-and-term pairs','Alternating sequence','Own rule and checked prediction'],'Finds a rule fitting only one step.','Continues familiar patterns with reminders.','Checks a stated rule across all terms and acknowledges non-uniqueness.'),
MN7:project('Factors,multiples and inverse families','Connect properties through examples and counterexamples.',['Optional counters or multiplication grid'],[
 'List the positive factors of24 and the first six positive multiples of6. Explain how factors and multiples differ.',
 'Sort1,2,9,13,16,27 into prime,composite or neither. Identify squares and cubes without assuming these are exclusive groups.',
 'For6×8=48,write related division facts. Use factor pairs to explain why36 is square and why27 is cube.'
],'Factors24:1,2,3,4,6,8,12,24. Multiples6:6,12,18,24,30,36. Prime2,13;composite9,16,27;1 neither. Squares1,9,16;cubes1,27. 48÷6=8 and48÷8=6. 36=6²;27=3³. One has one positive factor,so is not prime.',['Factor/multiple lists','Classification including1','Inverse facts and power explanations'],'Interchanges factor and multiple or calls1 prime.','Classifies with a factor table and prompts.','Justifies classifications and explains inverse relationships.'),
MN8:project('A practical relationship','Generalise the length of a row of joined squares.',['Optional square tiles or squared paper'],[
 'Place1,2,3,4 unit squares side by side in a single row. Count the outside edge lengths;shared edges are inside.',
 'Make an input-output table linking number of squares to perimeter. Find a rule and predict for10 squares.',
 'A row has perimeter26 units. Find how many squares it contains. Explain the relationship with a drawing or words,not just the table.'
],'Perimeters4,6,8,10. A row of n squares is n units long and1 unit wide,so perimeter=2n+2. Ten squares give22. If2n+2=26,then n=12. Each extra tile adds two outside unit edges because one old edge becomes internal.',['Table','Spatial explanation for rule','Forward and inverse predictions'],'Counts internal shared edges as perimeter.','Finds numerical increments but needs help explaining the geometry.','Connects spatial structure,rule and inverse use.',{tool:'table',starterRows:[['Squares','Outside perimeter'],['1',''],['2',''],['3',''],['4',''],['10','']]}),
MN9:project('Unknowns and equality','Diagnose common equation errors and check substitutions.',['Optional balance sketch'],[
 'Solve x+9=23 and5×y=45. Substitute each answer into its equation.',
 'A learner solves3×z+4=25 by doing25÷3−4. Explain why that reverses operations in the wrong order;solve correctly.',
 'Write a story for2×n+6=20. Find n and explain why the letter has the same value each time it appears.'
],'x=14;y=9. For z,remove4 first:21÷3=7. The wrong route divides the added4 as though it were part of the multiplication. n=7;for example two equal tickets plus a£6 fee total£20. Check2×7+6=20.',['Solutions and substitutions','Error explanation','Original matching story'],'Uses the equals sign as an instruction to calculate only one side.','Solves single steps and needs a reverse-order prompt.','Preserves equality,diagnoses the order error and checks a contextual equation.'),
MN10:project('Choose a mental strategy','Compare partitioning,bridging and compensation instead of following one fixed method.',['No timer or special materials'],[
 'Calculate67+28 by partitioning28 and by adding30 then adjusting. Explain both.',
 'Calculate402−197 by compensation and by finding the difference through200 and400.',
 'Calculate3.65+2.75 by making the next whole number or by partitioning whole parts and hundredths. Select a preferred method for each calculation and give a reason.'
],'67+20+8=95;67+30−2=95. 402−200+3=205;197→200 adds3,then200 to400 adds200,then2:205. 3.65+0.35=4;remaining2.40 gives6.40. Partitioning gives5+1.40=6.40. Preference can depend on known facts.',['Two methods per calculation','Chosen strategy and reason','Check that adjustments preserve value'],'Applies a remembered trick without compensating correctly.','Uses two methods with a visual or verbal prompt.','Chooses efficiently,explains why methods agree and checks the result.'),
MN11:project('Build a complete fact map','Use facts through12×12 with related division;11 and12 extend the Northern Ireland10×10 minimum.',['Multiplication practice bank','Optional counters or array drawing'],[
 'Start with the1-times facts:1×n=n for n from1 to10. Explain using one group,then reverse n÷1=n and n÷n=1 for n≠0.',
 'In the multiplication banks,work across factors2 through10. Use arrays,known facts or decomposition for unfamiliar products;speed is not a requirement. Mark which facts need another unseen practice item.',
 'Extend to11 and12:derive11×n as10×n+n and12×n as10×n+2×n. Try11×7,12×8,11×11,11×12 and12×12;write the related divisions. The extra table practice appears in Finding your stride;related divisions are in Extra challenge.',
 'Choose a fact from each table and write both related divisions. Explain why a correct remembered answer and an explained method are both useful evidence;neither one trial nor one session proves lasting recall.'
],'For7×6,5×6+2×6=30+12=42. Related divisions42÷7=6 and42÷6=7. For1×8=8,the divisions are8÷1=8 and8÷8=1. Commuted products have the same total but different group interpretations. The banks together with the original questions cover all144 ordered1–12 products and144 inverse group questions. Examples:11×7=77;12×8=96;11×11=121;11×12=132;12×12=144. Derive12×12 as120+24,not by assuming every11-times result repeats a digit.',['Fact map showing practiced tables','A derived fact with an array or words','Related divisions and later revisit notes'],'Needs equal-group models to interpret multiplication.','Derives products with known facts and checks related divisions.','Explains flexible strategies and demonstrates independent recall across varied later practice;adult checks breadth.'),
MN12:project('Four-operation workshop','Choose and explain whole-number and decimal methods.',['Paper for written methods optional'],[
 'Calculate304−178 and23×6. Show partitioning,an expanded written method or another justified method;check by an inverse operation.',
 'Share156 counters equally among12 groups. Explain a grouping or division method. Then compare(18+12)÷6 with18+12÷6.',
 'Calculate4.75+2.60,8.20−3.65,1.35×4 and9.6÷3. Explain decimal alignment or units,not only final answers.'
],'Results126,138,13;checks126+178=304 and138÷6=23. 12×10=120 leaves36=12×3,so13. Bracketed result5;unbracketed20 because division first. Decimal results7.35,4.55,5.4,3.2. A whole number may be written with trailing decimal zeros for alignment.',['Method for each operation','Inverse checks','Bracket comparison','Decimal explanations'],'Selects operations without considering the problem or place value.','Produces correct results using guided layouts.','Explains methods,order and place value,and verifies answers.'),
MN13:project('Money in four operations','Use multiplication,addition,subtraction and division with a common money unit.',['Pretend prices only;no payment details'],[
 'A stall sells rolls at85p and drinks at£1.20. Find the price of3 rolls and2 drinks,and change from£10.',
 'Six identical pencils cost£2.10. Find one pencil’s price and compare with a four-pack costing£1.60.',
 'Two people share a£7.50 bill equally. Explain how you know each share and check by addition.'
],'255p+240p=495p=£4.95;change£5.05. Unit prices210÷6=35p and160÷4=40p;the six-pack is cheaper per pencil. £7.50÷2=£3.75;£3.75+£3.75=£7.50. These are pretend purchases.',['Itemised basket','Change check','Unit-price comparison','Equal bill share'],'Mixes pounds and pence or compares pack totals only.','Converts to pence with prompts and completes calculations.','Chooses operations,keeps units consistent and explains the comparison.'),
MN14:project('A safe spending decision','Discuss needs,limits,payment choices and safe handling without using real money.',['Adult discussion optional;fictional scenarios supplied'],[
 'You have a pretend£10 lunch budget. Sandwich£3,water£1,fruit£2,toy£6. Choose a lunch with food and drink,then explain whether the toy fits.',
 'Compare paying cash with paying by card in this fictional purchase. For each,give one practical benefit and one thing to check.',
 'A message asks a child for a payment card number to claim a free toy. Explain what to do and who can help. Do not enter or share any real payment information.'
],'Sandwich+water+fruit=£6,leaving£4,so the£6 toy does not also fit. Other justified food/drink choices may fit the budget. Cash offers a visible spending limit;cards give transaction records but still require permission and spending checks. Do not send details;show a trusted adult.',['Budget calculation','Reasoned payment comparison','Safe response to the fictional message'],'Focuses on the desired item without checking essentials or permission.','Stays within the budget but needs prompts to discuss trade-offs.','Explains priorities and safe choices using the supplied scenario.'),
MN15:project('Savings with a choice','Make and revise a plan instead of relying on a single worked example.',['Pretend prices only'],[
 'A craft set costs£24. You have£9 and save£3 weekly. Make a week-by-week plan.',
 'After two weeks,the set rises to£27. Keep the same weekly saving. Revise the plan and explain the extra time.',
 'A discount pack has8 sheets for£2.40;another has5 for£1.75. Compare unit prices,then decide which to buy if you need only5 sheets and have£2. Explain why cheapest per sheet need not fit your constraints.'
],'Initial shortfall£15 gives5 weeks. At week2 you have£15;new shortfall£12 takes4 further weeks,6 weeks in total. Prices30p versus35p per sheet. The8-pack has better unit value but exceeds the£2 budget;the5-pack fits and meets the need.',['Original and revised savings tables','Explanation of changed week count','Unit-price and budget decision'],'Treats the total price as the amount still needed.','Builds a plan with prompts but overlooks the changed price.','Revises the plan and distinguishes unit value from affordability.',{tool:'table',starterRows:[['Week','Savings pounds','Target pounds'],['0','9','24'],['1','','24'],['2','','27'],['3','','27'],['4','','27'],['5','','27'],['6','','27']]}),
MN16:project('Two currencies,clear units','Recognise currencies and discuss what a fair price comparison requires.',['Fictional price cards only'],[
 'Sort these price labels by currency:£4.50,€6,£12,€10. State the names and symbols.',
 'One notebook is£5;another is€6. Without an exchange rate,can you conclude the£5 notebook is cheaper? Explain the missing information.',
 'Optional extension:at the invented fee-free rate£1=€1.20,compare those two notebooks. Then describe how a fee could affect a real comparison without looking up or assuming a live rate.'
],'Pounds:£4.50 and£12;euros:€6 and€10. Numerals alone cannot compare different currencies. At the stated practice rate£5 equals€6,so their prices match before fees. Actual exchange rates and charges vary;no real purchase is requested.',['Currency sorting','Missing-information explanation','Optional rate calculation with units'],'Treats£ and€ as interchangeable symbols.','Names currencies but needs a reminder about exchange rates.','Explains the unit difference and the conditions of a price comparison.'),
MM1:project('Estimate six kinds of measure','Estimate area and temperature as well as length,mass,capacity and time.',['Ruler','Squared paper','Safe household object','Optional kitchen scales,measuring jug,room thermometer,clock','Adult help;no hot liquids or outdoor exposure'],[
 'Before using a tool,estimate a book’s length,a fruit’s mass,a cup’s capacity and the duration of a short chosen action. Record units and reasons for your estimates.',
 'Estimate the area of a rectangular card by imagining1cm² squares. Measure its sides and check using an array;record the estimate and measured area separately.',
 'Estimate a comfortable room’s temperature,then read a safe room thermometer with an adult. Never use touch to test hot or cold objects. If no thermometer is available,use the supplied practice reading21°C and label it simulated,not measured.',
 'Compare differences without calling sensible estimates failures. Choose a closer benchmark for a second estimate.'
],'A sample card8cm by5cm covers40cm². An estimate36cm² is4cm² low. A room estimate20°C compared with21°C is1 degree low. Your actual readings will differ;an adult checks sensible benchmarks,units and safe use rather than expecting the model values.',['Six estimates made before readings','Actual or clearly simulated values','Comparison and improved benchmark'],'Guesses without units or reads the tool before estimating.','Chooses reasonable units with prompts.','Uses benchmarks,records estimates honestly and compares with appropriate measurements.',{tool:'table',starterRows:[['Measure','Estimate','Reading','Unit'],['Length','','','cm'],['Mass','','','g'],['Capacity','','','mL'],['Time','','','seconds'],['Area','','','cm²'],['Temperature','','','°C']]}),
MM2:project('How precise can this tool be?','Compare scale resolutions and repeated readings.',['Ruler marked in centimetres and ruler marked in millimetres,or drawn scales','Optional safe room thermometer','Paper strip'],[
 'Measure the same paper strip with a centimetre-marked scale and a millimetre-marked scale. Record the smallest division of each tool.',
 'Use this supplied comparison if two rulers are unavailable:one reading is about8cm;the finer scale reads83mm. Explain why83mm does not mean the first reading was dishonest.',
 'Measure twice more,repositioning the ruler. Describe variation. Explain whether83.274mm is justified by a tool marked only every1mm.',
 'On a temperature scale,locate18.5°C between18°C and19°C. Explain that intermediate values exist even when a tool cannot display every one.'
],'The finer scale distinguishes tenths of a centimetre. 83mm=8.3cm. Repeated readings may vary with alignment;report precision supported by the scale and method. A1mm scale does not justify three decimal places in millimetres. Measurement is continuous,unlike counting whole objects.',['Tool resolutions','Repeated readings','Explanation of justified precision'],'Assumes extra written digits make a reading more accurate.','Notices scale differences with guidance.','Relates resolution and repeated variation to an honest report.',{tool:'table',starterRows:[['Tool/division','Reading1','Reading2','Reading3'],['1cm','','',''],['1mm','','','']]}),
MM3:project('Use a common measurement unit','Apply all four operations in metric contexts.',['No special materials'],[
 'Add1.25m and75cm. Subtract350mL from2L. Convert to a common unit before calculating.',
 'Four parcels each have mass0.65kg. Find total mass in grams. Share1.8L equally among6 containers;find millilitres per container.',
 'Create one new problem in a different metric unit. State the conversion relationship and use an inverse check.'
],'125cm+75cm=200cm=2m. 2000mL−350mL=1650mL. 650g×4=2600g. 1800mL÷6=300mL each. Check300×6=1800. Units must be compatible before addition or subtraction.',['Four operations with units','One original problem','Inverse check'],'Combines unlike units as though their numbers were comparable.','Converts with a reference then calculates.','Chooses a common unit and explains the relation between measures.'),
MM4:project('Inside,outside and filling','Compare perimeter,area and volume with a composite shape.',['Squared paper','Optional unit cubes'],[
 'Draw a5-by-4 rectangle of unit squares. Remove a2-by-1 rectangle from its top-right corner to make an L-shape. Find remaining area by subtraction.',
 'Trace every outside edge of the L. Compare its perimeter with the original rectangle. Explain why the area changes while this corner removal leaves the boundary length unchanged.',
 'A cuboid box is5cm by4cm by3cm and is exactly filled with1cm cubes. Find its volume by layers. Explain why the L-area and box-volume use different units.'
],'L-area=20−2=18 square units. Its six boundary segments total18 units,as did2×(5+4);the removed outer lengths are replaced by equal notch lengths. Volume=20 cubes per layer×3=60cm³. Area counts flat squares;volume counts filled cubes.',['Shape description or drawing','Boundary calculation','Layer explanation and units'],'Uses one formula for every quantity.','Finds area but needs help tracing the notch boundary.','Explains all three quantities and why this perimeter stays the same.'),
MM5:project('One scale,a complete map','Construct and interpret a map with consistent units and labels.',['Paper','Ruler','Pencil'],[
 'Use scale1cm represents2m. Draw a12m by10m garden,then a4m by2m shed in a corner and a6m straight path that fits inside.',
 'Add a north arrow,scale label and key. Mark your drawing dimensions before translating them back to real lengths.',
 'A second plan uses1cm for5m. A wall is7cm long on it. Explain why measuring both printed plans with the same conversion would be wrong.'
],'First garden6cm×5cm;shed2cm×1cm;path3cm. The second wall represents35m. Each plan’s own scale controls conversion;screen or printed resizing can invalidate physical ruler readings unless the scale is preserved.',['Labelled plan dimensions','Key and north arrow','Comparison of two scales'],'Changes scale between objects.','Uses the right lengths with a scale table.','Constructs a coherent plan and explains why scale must be checked each time.'),
MM6:project('Choose a bus from a timetable','Read multiple entries,compare journey times and plan against a deadline.',['Supplied fictional timetable','Optional clock sketch'],[
 'You need to arrive by10:10 and cannot depart before09:20. Examine the four buses in the table. Which services are possible?',
 'Choose the latest possible departure. Calculate its journey time and how long before10:10 it arrives.',
 'Write the chosen departure and arrival in12-hour format. Draw or describe the hands for09:45. Explain why arrival before a deadline matters more than the shortest journey alone.'
],'A leaves too early. B(09:25→10:05) works;C(09:40→10:15) arrives late;D(09:35→10:00) works. Latest feasible departure is D at09:35(9:35am),arriving10:00am. Journey25 minutes;10 minutes spare. At09:45,the minute hand is on9 and hour hand three quarters from9 to10.',['Feasibility decisions for all rows','Journey and waiting calculations','Clock-format explanation'],'Chooses the latest bus without checking the arrival.','Finds possible services with prompts about both constraints.','Uses both constraints,calculates duration and explains clock positions.',{tool:'table',starterRows:[['Service','Departure','Arrival'],['A','09:10','09:50'],['B','09:25','10:05'],['C','09:40','10:15'],['D','09:35','10:00']]}),
MS1:project('A shape-property workshop','Construct and classify a wider range of polygons and explore symmetry and congruence.',['Squared paper','Ruler','Optional tracing paper,scissors with adult help','Regular pentagon template optional'],[
 'Draw an equilateral,an isosceles and a scalene triangle. Label equal sides if any;compare angles without assuming every isosceles triangle is acute.',
 'Draw a square,a non-square rectangle,a rhombus with no right angles,a parallelogram and an irregular pentagon. Make a table of sides,parallel pairs,right angles and symmetry lines. Define a rhombus as four equal sides,so a square also qualifies.',
 'Trace one shape and rotate the copy. Explain why rotation preserves congruence. Enlarge it and explain why the result is no longer congruent.',
 'Tessellate with rectangles or equilateral triangles. Mark a symmetry line where one exists and test rotational matches,including the final full turn once.'
],'A non-square rectangle has2 symmetry lines and rotational order2;a square has4 lines and order4. An equilateral triangle has3 lines and order3. An ordinary scalene triangle has none and order1. Rhombus classification includes squares under the stated inclusive definition. A traced rotated copy is congruent;an enlargement changes size.',['Constructed examples','Property table','Congruence comparison','Gap-free tiling explanation'],'Classifies by orientation or a familiar picture alone.','Uses a property checklist and physical overlays.','Explains inclusive classes and verifies properties rather than appearance.',{tool:'table',starterRows:[['Shape','Parallel pairs','Right angles','Symmetry lines'],['Square','','',''],['Non-square rectangle','','',''],['Equilateral triangle','','',''],['Scalene triangle','','',''],['Chosen rhombus','','','']]}),
MS2:project('Build and compare common solids','Distinguish flat faces,curved surfaces,edges and vertices across familiar3-D shapes.',['Paper','Optional safe models or packaging','Tape','Adult help with scissors'],[
 'Compare a cube,cuboid,triangular prism and square-based pyramid. For each,count flat faces,straight edges and vertices. Mark counted parts to avoid repeats.',
 'Compare a cylinder,cone and sphere. Keep flat faces separate from curved surfaces;describe circular boundaries explicitly rather than silently using a different edge convention.',
 'Construct a triangular-prism net:draw three rectangles in a strip with common length5cm and widths3cm,4cm,5cm. Attach matching3-4-5 right triangles to opposite 3cm end edges of the3cm-wide rectangle. Fold with adult help.',
 'Explain which2-D faces make the3-D model and why a sphere cannot be covered exactly by a finite net of flat polygons.'
],'Cube/cuboid:6 flat faces,12 straight edges,8 vertices. Triangular prism:5,9,6. Square-based pyramid:5,8,5. Cylinder:2 flat circular faces and1 curved surface;cone:1 flat circular face,1 curved surface and1 apex;sphere:0 flat faces and1 curved surface,no vertices. Curved boundaries may be called edges in some classrooms;state the convention. The prism strip wraps its3,4,5 widths around the triangle.',['Solid-property table with convention','Prism construction notes','Connection between net and solid'],'Confuses flat faces,curves and vertices.','Counts with a marked model but needs convention prompts.','Describes a range of solids consistently and explains a valid net.',{tool:'table',starterRows:[['Solid','Flat faces','Straight edges','Vertices'],['Cube','','',''],['Cuboid','','',''],['Triangular prism','','',''],['Square-based pyramid','','','']]}),
MS3:project('Turns that make a pattern','Use clockwise and anticlockwise commands to predict and create drawings.',['Compass card optional','Live Compass code pad or paper'],[
 'Write all eight compass points clockwise from north. State the direction after a quarter turn anticlockwise from south and a half turn from north-east.',
 'On the code pad,start facing up. Repeat FORWARD2,RIGHT90 four times to make a square. Add RIGHT45,then repeat the square commands to draw a second square at a new orientation.',
 'Predict before running. Replace all RIGHT90 commands with LEFT90 while keeping forward distances. Compare the mirrored turning direction and the closed shapes. Record one correction you made.'
],'Compass:N,NE,E,SE,S,SW,W,NW. South turning anticlockwise90° reaches east;NE plus180° reaches SW. Four equal sides and four right turns close a square. The added45° changes the second square’s orientation. LEFT reverses turning direction without changing square side lengths. Expand repeated instructions one command per line in the current pad.',['Compass sequence','Program text and prediction','Comparison and revision'],'Treats turns as forward movement or confuses turn direction.','Traces commands using a pointer or adult support.','Predicts,tests and explains changes to a simple picture-making program.'),
MS4:project('Use a protractor with meaning','Develop line and angle vocabulary,construction and investigation.',['Ruler','Protractor','Paper','Optional adult demonstration'],[
 'Draw a line segment AB and two rays from a point O. Label vertex and arms of an angle. Show parallel lines and perpendicular lines;explain that line lengths do not determine the angle.',
 'Draw a baseline ray to the right. Put the protractor centre at its endpoint and choose the scale whose0 lies on that ray. Mark40°,join the mark to the vertex,and check it is acute. Repeat for130° and explain why it is obtuse.',
 'Draw a70° smaller angle and label the other region290° reflex. Sketch right90°,straight180° and full360° turns. Identify the marked region every time.',
 'Draw a triangle and a quadrilateral. Measure interior angles,add them and compare with180° and360°. Discuss small measurement errors;choose a simple convex quadrilateral for this first investigation.'
],'Correct protractor placement uses centre,baseline and the zero matching the starting ray. 40°<90°;90°<130°<180°. Reflex360−70=290°. Triangle interiors total180°;simple quadrilateral interiors total360°. Measuring may give near totals because drawing and reading have limited precision.',['Labelled geometry vocabulary','Construction steps and angle types','Triangle/quadrilateral measured sums'],'Reads the wrong scale or places the centre off the vertex.','Constructs after alignment prompts.','Explains placement,region and benchmark checks and interprets measurement error.'),
MS5:project('Coordinates you can explain','Plot varied polygons and check a translation on the same scale.',['Saved coordinate plot or squared paper'],[
 'Use axes from0 to8 with equal spacing. Plot(1,1),(4,1),(4,4),(1,4),join in that order and return to the first point. Describe the shape and dimensions.',
 'Translate every vertex2 units right and1 unit up. Replace or add the new coordinates in your saved record;keep the original list in notes.',
 'Create a different first-quadrant triangle. Give ordered coordinates to a partner or check by plotting yourself. Explain why swapping x and y can change a point.'
],'The original is a3-by-3 square. New vertices:(3,2),(6,2),(6,5),(3,5). Translation preserves the3-unit sides and right angles. Across then up is a convention for ordered pairs;for example(2,5) differs from(5,2).',['Original and translated coordinate lists','Shape description and dimensions','Own triangle and plotting check'],'Swaps coordinates or uses inconsistent axis spacing.','Plots correctly with across-then-up prompts.','Explains coordinate order,dimensions and translation invariants.',{tool:'coordinates',starterRows:[['x','y'],['1','1'],['4','1'],['4','4'],['1','4'],['1','1']]}),
MD1:project('From observations to a display','Classify,record and present meaningful data with a retained table.',['In-app table/chart','Optional safe objects for a repeat investigation'],[
 'Here are fictional litter counts from equal10-minute clean-ups:paper6,plastic4,metal2,other3. Enter the table and explain a classification rule for an item made of mixed materials.',
 'Create or describe a bar chart with separate categories,zero baseline,equal scale intervals and count label. Explain why a pie or pictogram would need a key or part-whole interpretation.',
 'Repeat with an observation you can safely make,such as types of books on one shelf. Do not handle litter. Keep categories mutually exclusive and record your actual or explicitly fictional data.'
],'Counts total15. If mixed items go in other,each item enters one category. Paper has2 more than plastic. A bar chart separates categorical counts;order need not imply time. Safety:the litter data are supplied fiction,not an instruction to collect waste.',['Retained category table','Classification rule','Display explanation and second investigation'],'Double-counts objects across categories.','Records counts but needs help with category rules or display labels.','Classifies consistently and presents a reproducible record.',{tool:'table',starterRows:[['Material','Count'],['Paper','6'],['Plastic','4'],['Metal','2'],['Other','3']]}),
MD2:project('A conclusion with a limit','Support written or spoken claims with data while avoiding overclaims.',['Supplied data table'],[
 'A fictional class survey allowed one choice per child:apples9,pears5,bananas6. Write two conclusions supported by exact counts.',
 'Consider “all children like apples best” and “apples were the most popular of these three choices in this survey”. Explain which is supported and why.',
 'Write an enquiry that the table cannot answer. Suggest one fair way to collect the needed information without names or contact details.'
],'There were20 responses;apples exceed pears by4. Apples had the most votes among the three supplied choices in this class survey. That does not establish every child’s preference,other fruit preferences or the whole school’s view. A neutral anonymous survey with more options could investigate a new question.',['Two numerical conclusions','Revised cautious claim','Unanswered question and collection plan'],'Copies a count without connecting it to a claim.','Uses evidence but needs prompts to limit generalisation.','Explains supported conclusions and the boundary of the evidence.',{tool:'table',starterRows:[['Choice','Votes'],['Apples','9'],['Pears','5'],['Bananas','6']]}),
MD3:project('Three ways to read a record','Create grouped frequencies and compare graph,table and pictogram interpretations.',['Saved table/chart','Optional squared paper'],[
 'Reading times recorded in whole minutes are4,7,9,10,12,12,18,20,24,27. Put them into0–9,10–19 and20–29 groups. Record tallies in words or marks and frequencies;check the total.',
 'Create a bar display for grouped frequencies. Keep interval widths equal and label what the counts mean. Explain why the grouped table cannot reveal every exact reading time.',
 'Interpret this pictogram key:one full book symbol stands for2 children. A row has3 full symbols and a half symbol. How many children? Explain the half symbol.',
 'A line graph joins temperatures recorded at09:00=12°C,10:00=15°C,11:00=14°C. Describe its rises and falls,and explain why connecting separate fruit categories with a line would imply an unhelpful ordering.'
],'Grouped frequencies3,4,3,total10. At least10 minutes gives7 children. The pictogram represents6+1=7. Temperature rises3 degrees then falls1. A line suits ordered time observations;category counts usually suit bars. The app chart may render bars only;describe or draw the line and pictogram until dedicated renderers are available.',['Grouped table and total check','Pictogram calculation','Line-versus-category explanation'],'Places boundary10 in the wrong interval or ignores a key.','Groups with prompts and reads a supplied key.','Creates consistent groups and explains what each representation can show.',{tool:'table',starterRows:[['Whole-minute interval','Frequency'],['0–9',''],['10–19',''],['20–29','']]}),
MD4:project('A small data desk inside the app','Design fields,sort whole records and use two-condition queries with supplied data.',['Editable saved table','No external account needed'],[
 'Use the supplied fictional plant records. Explain why one row is one plant record and why the headings are fields. Add one new fictional record using the same units.',
 'Find the total and mean height for the original four plants before adding your new row. Sort those original records by height while keeping names and sun needs attached.',
 'Select original records with height at least20cm AND needs sun=yes. Explain why each other record is excluded. Use a filtered copy in notes rather than deleting your source evidence.',
 'For a spreadsheet connection,describe a SUM formula over numeric height cells and explain how changing a cell should update it. If using a separate spreadsheet optionally,check the result against your saved calculation.'
],'Original total18+25+32+15=90cm;mean22.5cm. Ascending:Clover15,Aster18,Birch25,Fern32. Query matches Birch only:Aster too short,Fern needs no sun,Clover too short. A spreadsheet SUM over the four original numeric heights returns90. The app table stores values;do not claim it evaluates spreadsheet formulas unless that tool is implemented.',['Retained source and new record','Sorted order and total','Query decisions for every record'],'Sorts a single column away from the record.','Sorts or filters with a worked model.','Keeps records intact and justifies both conditions and the calculation.',{tool:'table',starterRows:[['Plant','Height cm','Needs sun'],['Aster','18','yes'],['Birch','25','yes'],['Fern','32','no'],['Clover','15','yes']]}),
MD5:project('When an average hides something','Interpret mean and range and investigate an unusually large value.',['Saved table or paper'],[
 'Five daily reading counts are4,5,5,6,5. Find mean and range. Explain what each summary tells you.',
 'Correct the final value to25 because it was a longer reading day. Recalculate both summaries. Are they still a helpful description of an ordinary day?',
 'Do not silently remove the unusual day. Report both the dataset and the context;explain why a reader needs that information.'
],'Original sum25,mean5,range2. Changed data4,5,5,6,25 have sum45,mean9,range21. The larger value raises mean and range. Nine is mathematically correct but unlike most days;the changed observation length affects comparisons. Context must accompany the summary.',['Both means and ranges','Explanation of changed summaries','A balanced report including the unusual value'],'Calculates a mean but treats it as a value every day must have.','Notices the effect with prompts.','Explains both summaries and qualifies their interpretation.'),
MD6:project('Probability words in different settings','Use chance vocabulary accurately across bags,coins and weather statements.',['Optional fair coin','Adult support if a physical coin is unsuitable'],[
 'Classify:rolling7 on a standard six-faced die;rolling a number1–6 on it;heads on a fair coin;rain tomorrow when no forecast is supplied. Explain what information permits each judgement.',
 'Compare possible,likely,certain and impossible. Write an example where an event is possible but not likely.',
 'If safely using a coin,predict before10 tosses,record results,and explain why a short run need not split5–5. Alternatively interpret supplied results:H,H,T,H,T,T,H,H,H,T.'
],'Die7 impossible;1–6 certain in the stated model;heads has an even chance;rain likelihood cannot be quantified from the supplied information. Supplied coin record has6H and4T. This is compatible with a fair coin;fair does not mean alternating or exactly half in every short run.',['Classification and reasons','Own possible-but-unlikely example','Trial record and uncertainty explanation'],'Uses certain to mean very likely.','Uses words correctly in familiar contexts with prompts.','Distinguishes information,possibility and uncertainty across contexts.'),
MD7:project('List outcomes before experimenting','Generate outcome lists and run a fair,limited trial.',['Two distinguishable fair coins or supplied trial data','No real-money game'],[
 'Call the coins A and B. List all ordered outcomes of one toss of both before doing any trial. Explain why HT and TH are different records.',
 'Predict the chance of exactly one head from your outcome list. Run12 safe toss-pairs or use these supplied pairs:HH,HT,TH,TT,HT,HH,TH,TT,HT,TH,HH,TT.',
 'Count results and compare with your prediction. Explain why you cannot guarantee the next result or prove fairness from12 trials.'
],'Equally likely ordered outcomes HH,HT,TH,TT. Exactly one head has2 of4 outcomes,an even chance. Supplied trials have3 of each pair and6 single-head trials. Real trials can differ;the list describes possible outcomes while the record describes what occurred.',['Complete ordered outcome list','Prediction before results','Retained tally and comparison'],'Omits an ordered outcome or confuses prediction with a guarantee.','Lists outcomes with a tree/table prompt.','Explains equal likelihood assumptions and contrasts theoretical outcomes with observations.',{tool:'table',starterRows:[['Outcome','Observed count'],['HH',''],['HT',''],['TH',''],['TT','']]}),
MD8:project('Compare each event with evens','Order probabilities and compare them with one half under a stated fair model.',['Optional identical coloured counters in an opaque bag','Supplied model can be used without equipment'],[
 'A well-mixed bag has6 red,3 blue and1 green identical counters,each equally likely to be drawn. Compare each colour with evens and order least to most likely.',
 'A second fair bag has2 red,3 blue and5 green counters. Compare green alone,red or blue,and not green with evens. Use the total each time.',
 'If conducting trials,replace the drawn counter and mix after every draw. Explain why replacement preserves the stated probabilities. Predict first,then record10 trials;do not expect guaranteed exact counts.'
],'First bag:green1/10<blue3/10<red6/10;green and blue below half,red above. Second:green5/10=half,red-or-blue5/10=half,not-green5/10=half. Replacement restores the composition. Without replacement,the next probabilities change. Short trials vary.',['Ordered probabilities','Three evens comparisons','Fair-method explanation and optional trial record'],'Uses a colour count without comparing with total or half.','Builds fractions with counters and prompts.','Explains order,half comparisons and how trial method preserves the model.')
};
