import React,{useEffect,useState} from 'react';
import {AppState,Pressable,StyleSheet,Text,TextInput,View} from 'react-native';
import Svg,{Circle,G,Line,Polygon,Rect,Text as SvgText} from 'react-native-svg';
import * as Speech from 'expo-speech';
import DiagramFrame from './DiagramFrame';

export type ProjectRating='support'|'developing'|'secure';
export type ProjectDraft={
 notes:string;rows:string[][];versions:{text:string;at:string}[];stage:number;checks:number[];
 rating?:ProjectRating;points?:{x:number;y:number}[];
 art?:{shape:'circle'|'square'|'triangle';x:number;y:number;label:string}[];
};
export type LearningProject={
 title:string;source:'maths'|'english';goal:string;materials:string[];steps:string[];model:string;
 evidence:string[];rubric:{support:string;developing:string;secure:string};
 tool?:'reading'|'writing'|'table'|'coordinates';text?:string;stages?:string[];audio?:string;starterRows?:string[][];
};
export type Project=LearningProject;
type Props={project:LearningProject;id:string;value:ProjectDraft|undefined;onChange:(draft:ProjectDraft)=>void;onAskAdult:()=>void;adultUnlocked:boolean};
export const blankProjectDraft=(project:LearningProject):ProjectDraft=>({notes:'',rows:project.starterRows?.map(row=>[...row])||[['','']],versions:[],stage:0,checks:[],points:[],art:[]});
const ink='#203E36',green='#244E40';
const number=(s:string)=>/^[+-]?(?:\d+(?:\.\d*)?|\.\d+)$/.test(s.trim())&&Number.isFinite(Number(s))?Number(s):null;
const fmt=(n:number)=>Number(n.toFixed(2)).toString();
function Copy({children}:{children:React.ReactNode}){return <Text style={s.copy}>{children}</Text>}
function Heading({children}:{children:React.ReactNode}){return <Text accessibilityRole="header" style={s.heading}>{children}</Text>}
function Action({label,onPress,disabled=false,selected=false}:{label:string;onPress:()=>void;disabled?:boolean;selected?:boolean}){return <Pressable accessibilityRole="button" accessibilityLabel={label} accessibilityState={{disabled,selected}} disabled={disabled} onPress={onPress} style={[s.action,disabled&&{backgroundColor:'#E4E8E1'},selected&&{borderWidth:3}]}><Text style={s.actionText}>{selected?'✓ ':''}{label}</Text></Pressable>}
function Input({label,value,onChange,multiline=false,numeric=false,maxLength=10000}:{label:string;value:string;onChange:(v:string)=>void;multiline?:boolean;numeric?:boolean;maxLength?:number}){return <View style={{gap:8,flexGrow:1}}><Text style={s.label}>{label}</Text><TextInput accessibilityLabel={label} value={value} onChangeText={onChange} multiline={multiline} inputMode={numeric?'decimal':'text'} maxLength={maxLength} style={[s.input,multiline&&{minHeight:150,textAlignVertical:'top'}]}/></View>}

export default function ProjectWorkspace({project,id,value,onChange,onAskAdult,adultUnlocked}:Props){
 const draft=value||blankProjectDraft(project);
 const [notice,setNotice]=useState(''),[example,setExample]=useState(false),[reading,setReading]=useState(false),[showSummary,setShowSummary]=useState(false);
 const [xText,setX]=useState(''),[yText,setY]=useState(''),[shape,setShape]=useState<'circle'|'square'|'triangle'>('circle'),[artLabel,setArtLabel]=useState(''),[editingArt,setEditingArt]=useState<number|null>(null);
 useEffect(()=>{setNotice('');setExample(false);setReading(false);setShowSummary(false);setX('');setY('');setArtLabel('');setEditingArt(null);const subscription=AppState.addEventListener('change',status=>{if(status!=='active'){void Speech.stop();setReading(false);}});return()=>{subscription.remove();void Speech.stop();};},[id]);
 const update=(patch:Partial<ProjectDraft>,workChanged=true)=>onChange({...draft,...patch,...(workChanged?{rating:undefined,checks:[]}: {})});
 const announce=(message:string)=>setNotice(message);
 const reservedVersions=Math.max(0,(project.stages?.length||1)-1-draft.stage);
 const canArchive=draft.versions.length<20-reservedVersions;
 const archive=()=>{if(!draft.notes.trim()||!canArchive)return;update({versions:[...draft.versions,{text:draft.notes,at:new Date().toISOString()}]},false);announce(`Version ${draft.versions.length+1} saved. Your working notes remain editable.`);};
 const nextStage=()=>{if(!draft.notes.trim()||draft.versions.length>=20||!project.stages||draft.stage>=project.stages.length-1)return;update({versions:[...draft.versions,{text:draft.notes,at:new Date().toISOString()}],stage:draft.stage+1});announce(`Your response was saved as version ${draft.versions.length+1}. Part ${draft.stage+2} is now revealed.`);};
 const currentText=[project.text,...(project.stages||[]).slice(0,draft.stage+1)].filter(Boolean).join('\n\n');
 // A supplied audio field contains text for synthetic speech, never a recording URL.
 // Staged passages are read only as far as the child has revealed them.
 const speechText=project.stages?.length?currentText:(project.audio||currentText);
 const read=async()=>{try{await Speech.stop();setReading(true);Speech.speak(speechText,{language:'en-GB',rate:.85,onDone:()=>setReading(false),onStopped:()=>setReading(false),onError:()=>{setReading(false);announce('Read-aloud is unavailable on this device. The full text is still on screen.');}});}catch{setReading(false);announce('Read-aloud could not start. Please use the text on screen.');}};
 const stop=()=>{void Speech.stop();setReading(false);};
 const x=number(xText),y=number(yText),validPoint=x!==null&&y!==null&&x>=0&&x<=10&&y>=0&&y<=10;
 const addPoint=()=>{if(!validPoint||(draft.points||[]).length>=50)return;update({points:[...(draft.points||[]),{x:x!,y:y!}]});announce(`Point (${fmt(x!)}, ${fmt(y!)}) added.`);};
 const addArt=()=>{if(!validPoint||!artLabel.trim()||(editingArt===null&&(draft.art||[]).length>=20))return;const item={shape,x:x!,y:y!,label:artLabel.trim()};update({art:editingArt===null?[...(draft.art||[]),item]:draft.art!.map((a,i)=>i===editingArt?item:a)});announce(editingArt===null?'Labelled shape added to your composition.':'Shape changes saved.');setArtLabel('');setEditingArt(null);};
 const coordinateInputs=<View style={s.stack}><Input label="Horizontal position x (0 to 10)" numeric maxLength={30} value={xText} onChange={setX}/><Input label="Vertical position y (0 to 10)" numeric maxLength={30} value={yText} onChange={setY}/><Copy>Enter coordinates instead of dragging. Across first, then up. Decimals are allowed. Use the Add or Save button to save these position controls; unfinished positions and labels are not saved until then.</Copy></View>;
 const grid=<>{Array.from({length:11},(_,i)=><G key={i}><Line x1={40+i*22} y1={20} x2={40+i*22} y2={240} stroke="#62796B"/><Line x1={40} y1={240-i*22} x2={260} y2={240-i*22} stroke="#62796B"/><SvgText x={40+i*22} y={261} fill={ink} fontSize={14} textAnchor="middle">{i}</SvgText><SvgText x={28} y={245-i*22} fill={ink} fontSize={14} textAnchor="end">{i}</SvgText></G>)}<SvgText x={283} y={246} fill={ink} fontSize={14}>x</SvgText><SvgText x={22} y={13} fill={ink} fontSize={14}>y</SvgText></>;
 const numericRows=draft.rows.map((row,index)=>({label:row[0]?.trim()||`Row ${index+1}`,value:number(row[1]||''),index})).filter((row):row is {label:string;value:number;index:number}=>row.value!==null);
 const total=numericRows.reduce((sum,row)=>sum+row.value,0),maxAbs=Math.max(1,...numericRows.map(row=>Math.abs(row.value)));
 const numericRange=numericRows.length?Math.max(...numericRows.map(r=>r.value))-Math.min(...numericRows.map(r=>r.value)):0;
 const canSummary=Number.isFinite(total)&&Number.isFinite(numericRange);
 const tableColumns=Math.max(2,...draft.rows.map(row=>row.length));
 return <View style={s.workspace}>
  <Text style={s.meta}>{id} · {project.source==='maths'?'Maths':'English'} project</Text>
  <Heading>{project.title}</Heading><Copy>{project.goal}</Copy>
  <View style={s.panel}><Heading>Before you begin</Heading><Copy>{project.materials.length?`You will need: ${project.materials.map(m=>m.replace(/[.]$/,'')).join('; ')}.`:'You can start with the tools in this app.'}</Copy><Copy>Your work is saved on this device through the app's save system. Use fictional names and avoid private information.</Copy></View>
  <View style={s.stack}><Heading>Your steps</Heading>{project.steps.map((step,index)=><Copy key={index}>{index+1}. {step}</Copy>)}</View>
  {!!project.text&&<View style={s.panel}><Heading>Text to explore</Heading><Text selectable style={s.passage}>{project.text}</Text></View>}
  {!!project.stages?.length&&<View style={s.panel}><Heading>Read, predict and revisit</Heading>{project.stages.slice(0,draft.stage+1).map((text,index)=><View key={index} style={s.stack}><Text style={s.label}>Part {index+1}</Text><Text selectable style={s.passage}>{text}</Text></View>)}<Copy>Write your first thoughts below before opening another part. Revealing a new part keeps a dated copy of your current response.</Copy></View>}
  {!!speechText&&<View style={s.panel}><Heading>Optional read-aloud</Heading><Copy>A device-generated voice can read this text. It is a synthetic reading aid, not a recording of a person or a model of expressive performance. Nothing is recorded. Voice availability depends on your device.</Copy>{!!project.audio&&!project.stages?.length&&project.audio!==currentText&&<View style={s.stack}><Text style={s.label}>Read-aloud transcript</Text><Text selectable style={s.passage}>{project.audio}</Text></View>}<View style={s.wrap}><Action label={reading?'Restart read-aloud':'Read the supplied text aloud'} onPress={()=>{void read();}}/><Action label="Stop read-aloud" onPress={stop} disabled={!reading}/></View></View>}
  <Input label={project.tool==='writing'?'My writing and picture caption':'My notes, predictions and explanation'} value={draft.notes} onChange={notes=>update({notes})} multiline/>
  <Copy>Up to 10,000 characters. Notes are saved as you edit; saved versions below are optional snapshots you can return to.</Copy>
  <View style={s.wrap}><Action label="Save a version of my writing" disabled={!draft.notes.trim()||!canArchive} onPress={archive}/>{!!project.stages?.length&&draft.stage<project.stages.length-1&&<Action label={`Save response and reveal part ${draft.stage+2}`} disabled={!draft.notes.trim()||draft.versions.length>=20} onPress={nextStage}/>}</View>
  {reservedVersions>0&&<Copy>{reservedVersions} version {reservedVersions===1?'slot is':'slots are'} reserved for the remaining reading parts so you can keep each prediction before revealing more.</Copy>}
  {draft.versions.length>=20&&<Copy>You have reached 20 saved versions. Existing versions are kept. You can continue editing your current notes, but cannot save another version or reveal another part.</Copy>}
  {!!draft.versions.length&&<View style={s.panel}><Heading>My saved versions</Heading><Copy>Restoring a version replaces the current notes. Save the current notes first if you want to keep both. Versions preserve writing only; tables, points and pictures remain as they are.</Copy>{draft.versions.map((version,index)=><View key={`${version.at}-${index}`} style={s.version}><Text style={s.label}>Version {index+1} · {new Date(version.at).toLocaleString()}</Text><Text selectable style={s.copy}>{version.text}</Text><Action label={`Restore writing version ${index+1}`} onPress={()=>{update({notes:version.text});announce(`Writing version ${index+1} restored. Any previous adult rating has been cleared.`);}}/></View>)}</View>}
  {project.tool==='table'&&<View style={s.panel}><Heading>My editable data table</Heading><Copy>Follow the supplied column headings, or use the first row to write your own. Cells can hold words or numbers. Extra supplied columns are saved too. An optional chart can display numeric values in column 2; use it only when those values represent comparable quantities with the same unit.</Copy>{draft.rows.map((row,index)=><View key={index} style={s.version}><Text style={s.label}>Row {index+1}</Text>{Array.from({length:tableColumns},(_,column)=><Input key={column} label={`Row ${index+1}, column ${column+1}${project.starterRows?.[0]?.[column]?`: ${project.starterRows[0][column]}`:''}`} maxLength={300} value={row[column]||''} onChange={cell=>{const rows=draft.rows.map(r=>[...r]);while(rows[index].length<tableColumns)rows[index].push('');rows[index][column]=cell;update({rows});}}/>)}<Action label={`Remove table row ${index+1}`} onPress={()=>update({rows:draft.rows.filter((_,i)=>i!==index)})}/></View>)}<Action label="Add table row" disabled={draft.rows.length>=50} onPress={()=>update({rows:[...draft.rows,Array.from({length:tableColumns},()=> '')]})}/><Copy>{draft.rows.length} of 50 available rows. Each cell holds up to 300 characters.</Copy>
   <Action label={showSummary?'Hide optional numerical display':'Show optional numerical display for column 2'} onPress={()=>setShowSummary(v=>!v)}/><Copy>Do not combine different units, dates, codes or unrelated quantities just because they contain numbers. A calculated result is useful only if it makes sense for your investigation.</Copy>
   {showSummary&&!numericRows.length&&<Copy>No rows currently contain a number in column 2. Your text table is saved without a numerical display.</Copy>}
   {showSummary&&!!numericRows.length&&<View style={s.stack}><Heading>Chart and numerical summary</Heading><Copy>{numericRows.length} numeric rows included; {draft.rows.length-numericRows.length} rows excluded because column 2 is blank or not numeric.</Copy>{canSummary?<Copy>Total of values: {fmt(total)}. Mean of these {numericRows.length} values: {fmt(total/numericRows.length)}. Range: {fmt(numericRange)}. These are summaries of column 2, not a weighted mean of category labels. Displayed decimals are rounded to two places.</Copy>:<Copy>These values are too large for a reliable summary. Reduce their size before interpreting the calculation.</Copy>}
   <Copy>Bars share a scale. Zero is in the centre; positive values extend right and negative values left. The scale extends to {fmt(maxAbs)} on each side of zero.</Copy>{numericRows.map(row=><View key={row.index} style={s.stack}><Copy>{row.label}: {row.value}</Copy><View accessible={false} accessibilityElementsHidden importantForAccessibility="no-hide-descendants" style={{height:26,position:'relative'}}><Svg width="100%" height={26} viewBox="0 0 300 26"><Line x1={150} y1={0} x2={150} y2={26} stroke={ink} strokeWidth={2}/><Rect x={row.value<0?150-Math.abs(row.value)/maxAbs*144:150} y={3} width={Math.abs(row.value)/maxAbs*144} height={20} fill={green}/></Svg></View></View>)}</View>}
  </View>}
  {project.tool==='coordinates'&&<View style={s.panel}><Heading>My coordinate investigation</Heading>{coordinateInputs}<Action label="Add coordinate point" disabled={!validPoint||(draft.points||[]).length>=50} onPress={addPoint}/><Copy>{(draft.points||[]).length} of 50 points used. The visible grid covers 0 to 10 on each axis.</Copy><DiagramFrame title="My first-quadrant points" canvasHeight={280} description={`Coordinates are measured right and up from (0, 0). Each grid interval is one unit. ${(draft.points||[]).length?draft.points!.map((p,i)=>`Point ${i+1}: (${fmt(p.x)}, ${fmt(p.y)}).`).join(' '):'No points have been added.'}`}>{grid}{(draft.points||[]).map((p,index)=><Circle key={index} cx={40+p.x*22} cy={240-p.y*22} r={5} fill={ink}/>)}</DiagramFrame>{(draft.points||[]).map((p,index)=><View key={index} style={s.version}><Copy>Point {index+1}: ({fmt(p.x)}, {fmt(p.y)})</Copy><Action label={`Remove point ${index+1}`} onPress={()=>update({points:draft.points!.filter((_,i)=>i!==index)})}/></View>)}</View>}
  {project.tool==='writing'&&<View style={s.panel}><Heading>Optional picture and caption</Heading><Copy>Compose a simple labelled diagram to accompany your writing. Choose shapes and enter their positions. Use your writing field for the complete caption and explain how the picture supports your message.</Copy><View style={s.wrap}>{(['circle','square','triangle'] as const).map(item=><Action key={item} label={`Choose ${item}`} selected={shape===item} onPress={()=>setShape(item)}/>)}</View><Input label="Label for this shape" maxLength={80} value={artLabel} onChange={setArtLabel}/>{coordinateInputs}<Action label={editingArt===null?"Add labelled shape":"Save changes to selected shape"} disabled={!validPoint||!artLabel.trim()||(editingArt===null&&(draft.art||[]).length>=20)} onPress={addArt}/>{editingArt!==null&&<Action label="Cancel shape editing" onPress={()=>{setEditingArt(null);setArtLabel('');}}/>}<Copy>{(draft.art||[]).length} of 20 shapes used. Numbered markers on the picture match the full labels in the list.</Copy><DiagramFrame title="My picture composition" canvasHeight={280} description={(draft.art||[]).length?draft.art!.map((a,i)=>`${i+1}. ${a.shape}, labelled ${a.label}, centre (${fmt(a.x)}, ${fmt(a.y)}).`).join(' '):'An empty composition grid. Add a labelled shape using the controls above.'}>{grid}{(draft.art||[]).map((a,index)=>{const cx=40+a.x*22,cy=240-a.y*22;return <G key={index}>{a.shape==='circle'?<Circle cx={cx} cy={cy} r={9} fill="#FAE3BE" stroke={ink} strokeWidth={2}/>:a.shape==='square'?<Rect x={cx-9} y={cy-9} width={18} height={18} fill="#DDECCB" stroke={ink} strokeWidth={2}/>:<Polygon points={`${cx},${cy-10} ${cx-10},${cy+8} ${cx+10},${cy+8}`} fill="#E5E2F4" stroke={ink} strokeWidth={2}/>}<SvgText x={cx} y={cy-13} fill={ink} fontSize={14} textAnchor="middle">{index+1}</SvgText></G>})}</DiagramFrame><Heading>Written text for my composition</Heading><Text selectable style={s.copy}>{draft.notes.trim()||'Write a caption or accompanying text in your writing field above.'}</Text>{(draft.art||[]).map((a,index)=><View key={index} style={s.version}><Copy>{index+1}. {a.label} — {a.shape} at ({fmt(a.x)}, {fmt(a.y)})</Copy><Action label={`Edit shape ${index+1}: ${a.label}`} onPress={()=>{setEditingArt(index);setShape(a.shape);setX(String(a.x));setY(String(a.y));setArtLabel(a.label);announce(`Shape ${index+1} selected. Change its label or position using the controls above, then save.`);}}/><Action label={`Remove shape ${index+1}: ${a.label}`} onPress={()=>{update({art:draft.art!.filter((_,i)=>i!==index)});setEditingArt(null);setArtLabel('');}}/></View>)}</View>}
  <View style={s.panel}><Action label={example?'Hide example and guidance':'Show an example and guidance'} onPress={()=>setExample(v=>!v)}/>{example&&<Copy>{project.model}</Copy>}</View>
  <View style={s.panel}><Heading>My evidence checklist</Heading><Copy>Tick what you have actually done. This is your own reflection; it does not automatically approve or assess the work.</Copy>{project.evidence.map((item,index)=><Pressable key={index} accessibilityRole="checkbox" aria-checked={draft.checks.includes(index)} accessibilityState={{checked:draft.checks.includes(index)}} accessibilityLabel={item} onPress={()=>update({checks:draft.checks.includes(index)?draft.checks.filter(i=>i!==index):[...draft.checks,index],rating:undefined},false)} style={s.action}><Text style={s.copy}>{draft.checks.includes(index)?'☑':'☐'} {item}</Text></Pressable>)}</View>
  <View style={s.panel}><Heading>Adult feedback</Heading><Copy>An adult can discuss the saved work using the guidance below. This is informal practice feedback, not teacher certification or a school assessment. Editing the work clears the previous rating.</Copy><Text style={s.label}>Needs support</Text><Copy>{project.rubric.support}</Copy><Text style={s.label}>Developing</Text><Copy>{project.rubric.developing}</Copy><Text style={s.label}>Secure for this project</Text><Copy>{project.rubric.secure}</Copy>{adultUnlocked?<><View style={s.wrap}>{(['support','developing','secure'] as const).map(rating=><Action key={rating} label={rating==='support'?'Record needs support':rating==='developing'?'Record developing':'Record secure for this project'} selected={draft.rating===rating} onPress={()=>{update({rating},false);announce('Adult feedback saved for this project.');}}/>)}</View><Copy>Adult access is open. Record a rating only after reviewing the child's actual work against this project's guidance.</Copy></>:<Action label="Ask an adult to unlock feedback" onPress={onAskAdult}/>}<Copy>{draft.rating?`Recorded adult feedback: ${draft.rating==='support'?'needs support':draft.rating==='secure'?'secure for this project':'developing'}.`:'No adult rating has been recorded.'}</Copy></View>
  {!!notice&&<Text accessibilityLiveRegion="polite" style={s.notice}>{notice}</Text>}
 </View>;
}
const s=StyleSheet.create({workspace:{gap:20},stack:{gap:10},wrap:{flexDirection:'row',flexWrap:'wrap',gap:10},panel:{padding:18,borderRadius:16,borderWidth:1,borderColor:'#A3B4A5',backgroundColor:'#F4F6EF',gap:14},version:{paddingVertical:12,borderTopWidth:1,borderColor:'#A3B4A5',gap:12},heading:{fontSize:22,lineHeight:30,fontWeight:'700',color:ink},copy:{fontSize:16,lineHeight:26,color:ink},passage:{fontSize:19,lineHeight:31,color:ink},label:{fontSize:16,lineHeight:25,fontWeight:'700',color:ink},meta:{fontSize:14,lineHeight:22,color:'#53665E'},action:{minHeight:48,maxWidth:'100%',padding:14,borderWidth:1.5,borderColor:green,borderRadius:12,backgroundColor:'white',justifyContent:'center'},actionText:{fontSize:16,lineHeight:24,fontWeight:'700',color:ink},input:{minHeight:50,padding:14,borderWidth:1.5,borderColor:'#617C68',borderRadius:12,fontSize:17,lineHeight:26,color:ink,backgroundColor:'white'},notice:{fontSize:16,lineHeight:25,padding:16,backgroundColor:'#E4EEDB',color:ink,borderRadius:12}});
