import React from 'react';
import {Image,Platform,Pressable,Text,View} from 'react-native';
export const APP_STORE_URL='https://apps.apple.com/app/id6797931376';
export const validPlayURL=(url:string)=>{try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password&&u.hostname==='play.google.com'&&u.pathname==='/store/apps/details'&&!!u.searchParams.get('id');}catch{return false;}};
export default function StoreButtons({androidURL='',androidVerified=false,open}:{androidURL?:string;androidVerified?:boolean;open:(url:string)=>void}){
 const stores=[{name:'App Store',detail:'For iPhone and iPad',url:APP_STORE_URL,enabled:true},{name:'Google Play',detail:'For Android',url:androidURL,enabled:androidVerified&&validPlayURL(androidURL)}];
 if(Platform.OS==='android')stores.reverse();
 return <View style={{gap:12}}><Text style={{fontSize:22,fontWeight:'700',color:'#203E36'}}>Transfer Trainer NI app</Text><Text style={{fontSize:16,lineHeight:25,color:'#203E36'}}>Looking for dedicated transfer-test practice? Explore our separate Transfer Trainer NI app. Check the store listing for current availability and pricing.</Text>{stores.map(store=><Pressable key={store.name} accessibilityRole="link" accessibilityLabel={`Transfer Trainer NI on ${store.name}. ${store.detail}${store.enabled?'':'. Coming soon'}`} accessibilityState={{disabled:!store.enabled}} disabled={!store.enabled} onPress={()=>open(store.url)} style={({pressed})=>({flexDirection:'row',alignItems:'center',gap:16,padding:16,minHeight:92,borderRadius:18,borderWidth:1,borderColor:'#CCD8C5',backgroundColor:store.enabled?'#F0F4E9':'#F0F0ED',opacity:pressed?.8:1})}><Image source={require('../assets/transfer-trainer-ni.png')} accessible={false} style={{width:60,height:60,borderRadius:13}}/><View style={{flex:1,gap:3}}><Text style={{fontSize:18,fontWeight:'700',color:'#203E36'}}>{store.enabled?`View on ${store.name} ↗`:`${store.name} — coming soon`}</Text><Text style={{fontSize:14,color:'#53665E'}}>{store.detail}</Text></View></Pressable>)}</View>;
}
